### ISSUE TITLE
App uses previous location on launch?

### ISSUE THREAD

**Issue by jamieshaw** [home-assistant/home-assistant-iOS#100]
As a bit of background context, I'm using both the HA iOS app and OwnTracks in an attempt at getting more accurate reports of location if one manages to fire an event when the other does not, etc. Both are pointing to the same device ID (`jamie_iphone`) within HA so the last update received from either is the one used.

I've noticed that if I launch the Home Assistant app from fresh (i.e. it's quit from iOS' multitasking screen) or after a long duration, the app reports my location inaccurately until manually pushing or _saving_ the Settings screen to reconnect to my server.

After my location is updated, I can quit the app from multitasking, open the app, and the location is back to the previous point before pushing an update as above. I can continue this behaviour repeatedly.

At first, I thought it might be the result of it defaulting to the retained OwnTracks location on the MQTT broker, but this doesn't appear to be the case as OwnTracks is showing the last known location for myself correctly at my current location – it definitely seems to be stemming from Home Assistant for some reason.

Any ideas on this one?

**Comment by robbiet480** [comment]
Please retest with 1.5.0 and report back, thanks!

**Comment by robbiet480** [comment]
Closing as stale, this was fixed via 1.5.0. Please re-open if you are still experiencing.
