### ISSUE TITLE
Regardless entering or leaving the ibeacon's coverage, it always notifies "Home exited via iBeacon"

### ISSUE THREAD

**Issue by xcray** [home-assistant/home-assistant-iOS#102]
And the state of iOS device in HA is always "Home".
The app is the newest version: 1.1.1.
The HA is also the newest: 0.72.0 (0.71.0 same issue).

configuration.yaml:

> zone:
>   - name: Home
>     latitude: xxxxxxx
>     longitude: xxxxxxx
>     radius: 50
>     icon: mdi:home
>     track_ios: false

customize.yaml:

> zone.home:
>   beacon:
>     major: 3786
>     minor: 3788
>     uuid: 08c89efa-7055-9755-9d36-fce0319a782a

could u please give any comments?

**Comment by mnoorenberghe** [comment]
This was fixed in 7ca200cdedd5a475ddabef10ec7b4cfbb4579391 a long time ago but wasn't released yet. This fix will be in the next release (version 1.1.2 or higher).

**Comment by xcray** [comment]
Thanks for your comment, I am looking forward for the new release........
