### ISSUE TITLE
Can't connect with Content-Security-Policy header in place

### ISSUE THREAD

**Issue by plinss** [home-assistant/home-assistant-iOS#106]
I added a CSP header to my Home Assistant server: `Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"` and it functions normally via a web browser, however the iOS app wont connect and reverts to the login screen. 

Attempting to log in gives the error "Unknown error: SecurityError: The Operation...". 

Removing the CSP header restores normal operation.

**Comment by robbiet480** [comment]
@plinss Can you provide a screenshot with the full error?

We use the native Safari in-app browser (WKWebView) and therefore have very limited control over things like respecting a CSP but i'll look into it for you!

**Comment by robbiet480** [comment]
Also, can you attempt to use the same interface via the native Safari browser?

**Comment by plinss** [comment]
Same problem with the native Safari, which then led me to test with Safari on macOS and I found the problem. I was testing the CSP header with Firefox and it allows the web socket connection, where Safari requires the wss:// url to be explicitly set in the CSP header as a connect-src. e.g. `Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://my.home.server/;"`

So not a problem on your end, sorry for the bother. But CSP header setting should probably be better documented somewhere on the Home Assistant site...

**Comment by robbiet480** [comment]
Glad I could help!
