### ISSUE TITLE
Feature request: Snips

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/home-assistant-iOS#107]
Would it be inside the scope of the app to implement snips?
https://github.com/snipsco/snips-platform-swift

**Comment by mnoorenberghe** [comment]
I would think that Siri integration would be preferred and Robbie mentioned that it was something he was looking into for iOS 12. I would guess it's out of scope but we'll see what Robbie says.

**Comment by bramkragten** [comment]
@robbiet480 I think siri shortcuts does most of what I was trying to achieve with this. :-) So I think we can close this.
