### ISSUE TITLE
Lovelace support 

### ISSUE THREAD

**Issue by traumtheater** [home-assistant/home-assistant-iOS#109]
I would like to use lovelace as the ui interface in the iOS app. Eventually a possibility to switch between default and lovelace ui would benefit all users.
Currently one needs to maintain two uis if you want to use Lovelace and the iOS app.

**Comment by mnoorenberghe** [comment]
You can already use Lovelace on iOS by going to the /dev-info aka. about page and clicking ">> Set lovelace as default page on this device <<"

Since it's experimental I'm not sure it's worth doing extra native UI work to support this.

**Comment by mnoorenberghe** [comment]
Lovelace is now the default and it works fine for me on my iPhone 6.
