### ISSUE TITLE
New Auth System

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/home-assistant-iOS#110]
I spoke with @blackgold9 about this in #devs_ios, short version is new auth system is coming fast and we need to get it implemented pretty quick otherwise my carefully curated 5 star rating will disappear almost overnight (mostly joking... mostly). More info is in [Discord](https://discordapp.com/channels/330944238910963714/377667559303938050/469645908292665345)

**Comment by respectTheCode** [comment]
Any progress on this?

**Comment by blackgold9** [comment]
I’m ready to merge phase one, with some more tweaks for the browser being
needed. Then will work with testers to find any corneres I missed and clean
that up too.

**Comment by benleb** [comment]
ready for testing here 👍

**Comment by mnoorenberghe** [comment]
Hey @blackgold9, thanks for all your work on this. What is the current state?
I just updated to the TestFlight build from today and now I'm getting 
> [homeassistant.components.http.ban] Login attempt or request with invalid authentication from … 

in my logs and the X aren't turning into ✔️ when I save… the webview authenticates fine though. I did a reset in the app and have the same issue.

**Comment by igloocube** [comment]
Hi

For new users since this new auth system was bought in, should we still be able to use this app if we enable legacy_api_password as per https://www.home-assistant.io/docs/authentication/providers/ ?

Thank you

**Comment by robbiet480** [comment]
@igloocube Yep, we support both styles!
