### ISSUE TITLE
iBeacon detection not working correctly

### ISSUE THREAD

**Issue by quthla** [home-assistant/home-assistant-iOS#113]
I get BeaconRegionExit both when beacon is detected and lost.

[homeassistant.core] Bus:Handling <Event call_service[L]: service_data=battery=100, hostname=X, gps=[1, 2], gps_accuracy=1, dev_id=X, battery_status=Unplugged, domain=device_tracker, service_call_id=123, service=see>

This is the service call received by HA on iBeacon event but shouldn't there be location_name=[home,not_home] for HA to know where the device currently is located?

**Comment by mnoorenberghe** [comment]
This was fixed in 7ca200c a long time ago but wasn't released yet. This fix will be in the next release (version 1.1.2 or higher).

**Comment by quthla** [comment]
@mnoorenberghe But unless I missed something, this will only fix half of the problem.

There's still no location_name=[home, not_home] in the service data. So it relies entirely on gps but if one leaves his home, he might still be in a 100m radius when the app notices Beacon is lost and will not be known to HA as not_home then.
