### ISSUE TITLE
Apple Watch Support

### ISSUE THREAD

**Issue by plinss** [home-assistant/home-assistant-iOS#114]
It would be great to have a companion app for the Apple Watch. While I don't expect the full HA UI on the watch, having a few buttons easily accessible from the watch would come in extremely handy, like door lock/unlock, lights, etc.

A simple version could perhaps just have, say, 4 buttons that can be configured from the app on the paired phone, each just calling a service, or triggering an event or automation.

**Comment by cmsimike** [comment]
Have you tried controlling hass via Siri? I thought an apple watch app would be nice too, but having to switch into the app, wait for it to load (which is a good amount of time when cold-launching any app), scroll to the location seems to time consuming vs just issuing the command via siri

**Comment by TheCellMC** [comment]
Couldn’t you simply use the HA HomeKit component and the HomeKit app on the Apple Watch?

**Comment by plinss** [comment]
Given that the entire reason I adopted HA is that I can automate my house without connecting to proprietary cloud services that leak private information, no, neither Siri or HomeKit are viable options.

**Comment by walthowd** [comment]
@plinss I'm not sure if "the man" or Tim Cook is very interested if your bathroom light is on or off! And Apple has been very privacy oriented to this point --- But -- You can do exactly what you want with the Workflow app -- Create some some workflows that go:

 URL:
https://yourduckdns.duckdns.org:8123/api/services/light/toggle

Get Contents of URL:
Advanced
Method: POST
Headers:
x-ha-access: your ha password
Content-Type: application/json

Request Body - JSON
entity_id light.bathroom

Get the work flow working on your phone, you can also add a widget to your Today View on your phone if you like -- then install the workflow app on your watch and you can just click on the button to toggle the light or do whatever else you would like.  Workflow also supports complications so you can add them to your watch face.

**Comment by uchagani** [comment]
wanted to jump in on this, a face complication would be nice to display some sensor data or such on the watch face.

**Comment by plinss** [comment]
Also relevant, the recent iOS upgrade replaced Workflow with Shortcuts, which for some unexplained reason dropped support for the Apple Watch.

**Comment by jeffehobbs** [comment]
> Also relevant, the recent iOS upgrade replaced Workflow with Shortcuts, which for some unexplained reason dropped support for the Apple Watch.

That's not _exactly_ true. You can access Shortcuts on the watch as long as they don't require interaction with the apps on your iPhone. For example, I put together a shortcut to Toggle our Sonos media_player:

![img_7944](https://user-images.githubusercontent.com/466625/50044522-abbb2e00-0052-11e9-9903-23d547d5a86e.jpg)

... it works, albeit glacially slow. Strongly agree that support in the HA iOS app is going to be a more effective way to solve for this.

**Comment by plinss** [comment]
So I have similar shortcuts set up, no interaction with apps on the phone, but there's no UI on the watch to activate them that I'm aware of, except Siri, and I want to have a button to push, not have to talk to the watch. Or is there another way to activate the shortcuts from the watch that I'm missing?

**Comment by jeffehobbs** [comment]
Sadly, no -- Siri seems like the sole way to trigger Shortcuts -- so yeah, you'll be dealing with Siri. :(

Not what you asked for, but something to consider: [Actionable Notifications](https://www.home-assistant.io/docs/ecosystem/ios/notifications/actions/). You can send the watch a notification and then prompt the user for a couple actions that trigger other HA automations. Worth playing with if you haven't checked it out.

**Comment by TomBrien** [comment]
The original feature request is now met and this issue is rather stale so I'm going to close
