### ISSUE TITLE
iOS 12 local DNS not resolving on LAN

### ISSUE THREAD

**Issue by jasonehines** [home-assistant/home-assistant-iOS#118]
I just wanted to give you a heads up that on iOS 12 (Beta 4), my duckdns domain will not resolve on the LAN. It works fine while on cellular. I have tested and I can ping the domain from the LAN using a ping app on my phone. I also can get to HA from my phone using a browser on the LAN. Sometimes, it will stay connected if I connect on cellular and then turn on wifi. But if I manually turn off cellular while connected to wifi I get disconnected and it won't reconnect.

**Comment by robbiet480** [comment]
Are you able to access the domain via the browser on cellular?

**Comment by robbiet480** [comment]
Oh and what error are you receiving?

**Comment by jasonehines** [comment]
This is looking more like an iOS bug. I think being able to see it in my browser before was just a cache. Everything worked fine on cellular. It seems to be some issue with iOS preferring IPv6. Even though I didn't have my DHCP/DNS server (Pi-hole) configured for IPv6, my iPhone was still getting an IPv6 address and DNS server from somewhere. I ended up enabling IPv6 for DNS and DHCP on my server. So far, it's working.
