### ISSUE TITLE
Reset webview when app switches between internal/external URLs

### ISSUE THREAD

**Issue by blackgold9** [home-assistant/home-assistant-iOS#122]
Right now, the app supports an internal and external URL. 
What i've seen is that the native networking layer makes the switch when the SSID changes, but the webview is still loaded to the original URL. We need to change the webview's url when we detect it does not match.

**Comment by johntdyer** [comment]
The app supports an internal and external URL ?

**Comment by johntdyer** [comment]
is there a testflight account or something I can get added too to help test the beta ?

**Comment by blackgold9** [comment]
Fixed
