### ISSUE TITLE
Hardcoded Domain!? (1.2.0 23)

### ISSUE THREAD

**Issue by benleb** [home-assistant/home-assistant-iOS#126]
Happily loaded the 23 version to try but... should these values really be hardcoded? @blackgold9?! :D

https://github.com/home-assistant/home-assistant-iOS/blob/d6416869856e3746e7d62b9b49f6fccc44142247/HomeAssistant/Authentication/AuthenticationController.swift#L38
https://github.com/home-assistant/home-assistant-iOS/blob/d6416869856e3746e7d62b9b49f6fccc44142247/Shared/Authentication/AuthenticationRoutes.swift#L12

**Comment by robbiet480** [comment]
They are only for right now during this beta testing. We are working on getting the necessary redirect onto home-assistant.io. Don't worry, @blackgold9 is not getting your credentials.

**Comment by blackgold9** [comment]
Temporary until we get the right headers deployed on the official site. In the meantime, I posted the right html in my github repo. All it does is point at an html file that provides the redirect url (A requirement of the new auth).

That file is here:
https://github.com/blackgold9/home-assistant-iOS/blob/master/index.html

**Comment by blackgold9** [comment]
fixed
