### ISSUE TITLE
Use Internal URL keeps activating

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/home-assistant-iOS#127]
On my iPad in a previous beta (before release today) I had enabled 'Use Internal URL' and now I can not switch it off. If I switch it off and save, authenticate, press done, if I go back into settings it is enabled again.

On my iPhone, I have never enabled internal URL and it stays off.

Commented out legacy_api in configuration.yaml and app works.

I turn off use internal, use legacy off, basic auth off. Hit save - enter user/pass and then 2FA token and then it goes back (and all are still off) and then DONE. If I go back into settings, use internal is on again.

I switched WiFi off forcing it to use 4G and I had to reauthenticate (connecting screen stayed on until I refreshed, then had to authenticate again). Works on 4G but still it has the use internal switch on.

All seems to be working.

**Comment by mnoorenberghe** [comment]
I think this was fixed by #129. Can you check in a newer beta?

**Comment by blackgold9** [comment]
Confirmed this is fixed
