### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Pattern91** [home-assistant/home-assistant-iOS#13]
I got some error during compiling for the simulator:

`Library/Developer/Xcode/DerivedData/HomeAssistant-bnkcrgnbhzihnjgteumtodaffhki/Build/Intermediates/HomeAssistant.build/Debug-iphonesimulator/HomeAssistant.build/Script-B641BC261E20BAF3002CCBC1.sh:`

it says: 

> line2: no such file or directory

can anybody help?

i cleared out my name in the filepaths

**Comment by robbiet480** [comment]
Is this still an issue?

**Comment by robbiet480** [comment]
Please reopen if this is still an issue, thanks!
