### ISSUE TITLE
Background fetch location can't be disabled 

### ISSUE THREAD

**Issue by quthla** [home-assistant/home-assistant-iOS#134]
Switch set to off but still getting notifications for it 

And maybe there should be another switch to disable visits too

**Comment by blackgold9** [comment]
Can you share why you want these disabled?

**Comment by robbiet480** [comment]
@quthla Can you confirm this was fixed in 1.5.0? It should have been.

**Comment by robbiet480** [comment]
@quthla I've confirmed that this was implemented in 1.5.0 ([here](https://github.com/home-assistant/home-assistant-iOS/blob/master/HomeAssistant/AppDelegate.swift#L43-L45) and [here](https://github.com/home-assistant/home-assistant-iOS/blob/master/HomeAssistant/AppDelegate.swift#L179-L182)). Please reopen this issue if you are still not seeing this as working.
