### ISSUE TITLE
Basic authentication toggle remains off even when using basic authentication

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/home-assistant-iOS#141]
I am currently using the basic authentication (on build 29), but in settings the toggle is still disabled. 

![image](https://user-images.githubusercontent.com/18319734/45231434-f2ea9380-b299-11e8-999a-f35e37dc333f.png)

**Comment by robbiet480** [comment]
Fixed in 2.0 via c6d10a13b751ddd220b266677c9d5e3110a71267
