### ISSUE TITLE
Feature Request: Add "On Phone" sensor

### ISSUE THREAD

**Issue by boojew** [home-assistant/home-assistant-iOS#144]
I believe it should be possible to use CallKit to see if we are on the phone - and create a HASS sensor to show the status. IFTTT and SimpleControl do something similar.

**Comment by robbiet480** [comment]
The problem with this is we can't get _notified_ when you are on the phone, so you are basically hoping that a location update happens at the same time as you are on the phone. Furthermore, i'd add that Verizon doesn't support data during phone calls anyway so for a large part of the US it would be pointless.

I'm always down to add more sensors and stuff but most of the ideas don't have a notification component like location does (or background fetch) so updating the sensor would be directly tied to a update being triggered by a loc update, background fetch etc.

**Comment by boojew** [comment]
Hmm.. I can't validate the details of how they do it, but simplecontrol does this quite well; however, it's designed for local network control, so only when Wifi is used. 

My use case would be to pause media when I'm on the phone and in the house on wifi.

**Comment by robbiet480** [comment]
@boojew Okay, I figured out how SimpleControl does this, it's via [`applicationWillResignActive`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622950-applicationwillresignactive) which we only get when our app is in the foreground. So this can't happen as a sensor, at least for now. Thanks for the suggestion!
