### ISSUE TITLE
Problems with location and my suggestion to solve

### ISSUE THREAD

**Issue by prsolucoes** [home-assistant/home-assistant-iOS#148]
Hi,

I have reported some location problems. You can see here on forum:
https://community.home-assistant.io/t/lots-os-problems-with-ios-and-homeassistant-app/68584/7

Basically is the authorization method used in the app. I want only enable location when i use the app, but the app only request for always mode.

![image](https://user-images.githubusercontent.com/395096/45567458-42980480-b830-11e8-8fb8-0a6b108d62b2.png)

My suggestion is show an alert with two options to the use "Always", "Using the app" (something like this). And based on the response, you will call:

```
self.authLocationManager.requestAlwaysAuthorization()
```

or

```
self.authLocationManager.requestWhenInUseAuthorization()
```

This will solve the problems.

The second solution is better, more require more work. On options menu the user can select between the modes, and it can be store on preferences. When the user change, you call the correct request method and if autorized change the selected option. On authorization error show the "not authorized" item as selected. [Not authorized, Always, When in use].

Thanks.

**Comment by blackgold9** [comment]
What's your use case for "When using the app" location?

**Comment by prsolucoes** [comment]
We develop apps in our business, and users hate apps that drain the battery or always access their location every time. You can get in background tasks or while the user is using it.

It will let the user choose what they wanna do.

In my case the location sign never hide, because the app is getting location in background. But i want only in background tasks or while im using it.

If the app dont support both methods, it will get unexpected behaviour like me, that when i send one shot location i got that error related on forum and the user dont have any idea about whats happen.

The iOS let you choose the location update mode without the app on configuration, because this i suggest the option list in my second suggestion and the problem that i related on forum was solved when i change the location update method on configuration.

**Comment by blackgold9** [comment]
I understand supporting user preferences. I'm just trying to get at specific use cases we're currently not considering (people do all sorts of different things with HASS)

**Comment by prsolucoes** [comment]
I think that this simple solution will finish with the problems and confusion about location and cover all cases.

**Comment by prsolucoes** [comment]
Any way thanks for all.

**Comment by robbiet480** [comment]
We'd welcome a pull request for this but don't foresee implementing this ourselves.
