### ISSUE TITLE
Remove native component UI and storage

### ISSUE THREAD

**Issue by mnoorenberghe** [home-assistant/home-assistant-iOS#15]
According to https://community.home-assistant.io/t/current-status/12118 the plan is to remove the native component/entity UI and storage.

I think the current master should go to a native_ui branch and then master can focus on the 1.0 plan from the forum.

@robbiet480: The main reason for filing is to ask if you would like help switching to the web view (hopefully WkWebView) or if you have already started?

**Comment by robbiet480** [comment]
Completed in 56dc62be954d82022584a85590e7f259c5c0baf7
