### ISSUE TITLE
Removing tokens within the app

### ISSUE THREAD

**Issue by towerhand** [home-assistant/home-assistant-iOS#156]
In the profile when you click on the "trash can" icon to remove one of the refresh tokens, the confirmation pop up doesn't show up. 

HA 0.79.0b2
iOS app 1.2.0 (35)

**Comment by mnoorenberghe** [comment]
Since that is the web UI within the app this should be moved to https://github.com/home-assistant/home-assistant-polymer/issues

**Comment by robbiet480** [comment]
We need to implement [`webView(_:runJavaScriptConfirmPanelWithMessage:initiatedByFrame:completionHandler:)`](https://developer.apple.com/documentation/webkit/wkuidelegate/1536489-webview) for this to work.

@balloob Do we call `alert()` anywhere? If so, I should also implement [`webView(_:runJavaScriptAlertPanelWithMessage:initiatedByFrame:completionHandler:)
`](https://developer.apple.com/documentation/webkit/wkuidelegate/1537406-webview)

**Comment by balloob** [comment]
yeah we do.

**Comment by robbiet480** [comment]
@balloob Thanks

@blackgold9 we'll need to get this in on 1.5.0

**Comment by robbiet480** [comment]
Also probably good to implement [`webView(_:runJavaScriptTextInputPanelWithPrompt:defaultText:initiatedByFrame:completionHandler:)`](https://developer.apple.com/documentation/webkit/wkuidelegate/1538086-webview)

**Comment by balloob** [comment]
We use prompt for long lived access tokens.

**Comment by towerhand** [comment]
Just a quick FYI, this issue wasn’t fixed for the 1.5.0 release.
