### ISSUE TITLE
Documentation for trying out new versions

### ISSUE THREAD

**Issue by lobradov** [home-assistant/home-assistant-iOS#162]
Hi, this is not a bug report but more a documentation enhancement request: 

Latest version (as of today) in App Store is 1.1.1 and I'd like to try out newer version on my phone, but have no clue how to compile/get it there. 
Step-by-step instructions for someone with minimal knowledge on building iOS apps would be more than appreciated.

Updating version on App Store also helps ;)

**Comment by Tomatom68** [comment]
Hi, you can try the beta version by clicking in the following link:[https://community.home-assistant.io/t/public-beta-testing-is-now-open/70450]. ;)
