### ISSUE TITLE
No sign of activity attributes

### ISSUE THREAD

**Issue by luca-angemi** [home-assistant/home-assistant-iOS#164]
Tested the 1.5 beta version in different ways (cycling, running, walking and driving a car) but I don't see any of the attributes related to Core Motion Activity (yes, I've granted all permissions!).

**Comment by Mike1082** [comment]
Same here, I would love to see the Core Motion attribute. Have been testing since 1.5.0 (10) through 1.5.0 (21). All permissions granted, and the location tracking has otherwise been deadly accurate!

**Comment by bbrendon** [comment]
I see something about it here but other than that nothing in the app or in HASS.

https://github.com/home-assistant/home-assistant-iOS/commit/7e161f79a5ad2d86c28f4e267ef304ac749bbbec

**Comment by robbiet480** [comment]
Fixed. Payload contains these attributes once more:

```json
{
  "activity_type": "Stationary",
  "activity_confidence": "High",
  "activity_start_date": "2019-02-20T02:30:50.628-0800"
}
```
