### ISSUE TITLE
Internal ip does not work

### ISSUE THREAD

**Issue by sendorm** [home-assistant/home-assistant-iOS#165]
Hass version 0.8.0
Ios app version: 1.5.0 (21)

On the ios app current network name is always “unknown”, even on wifi and the internal url does not work anymore. 

My router does not support nat forwading. So I use “https://hass.ip” outside and use https://hass.ip:8123” while on my home wifi.

**Comment by sendorm** [comment]
Uninstalled the beta version. Proceeded to install the non beta app first and then installed the beta again, which fixed the problem.

**Comment by mnoorenberghe** [comment]
Since you got this working and I don't see other reports I will close this for now. If you're still affected by this we can re-open.

**Comment by UYKV878ogfvkhc** [comment]
@robbiet480   is the internal url supposed to be used in with with https? I run https with Hassio/DuckDNS/LetsEncrypt add-on. When I try and to use internal url then the ios app reports invalid certificate. Can we get a `verify_ssl: Bool = false ` option to use the internal url. If this is not the intended function than can you point us to where we can read about how to use the internal url feature? 

 [HomeAssistant/Views/SettingsViewController.swift line 35](https://github.com/home-assistant/home-assistant-iOS/commit/930aef6987160c8400d06f3bf524568820e9c559#diff-e621301c03acd375e80ff9d7a50fd774R35)
