### ISSUE TITLE
Feature Request (1.5.0 Beta): Change device_tracker state when turning Airplane mode on/off for new iCloud3  device_tracker

### ISSUE THREAD

**Issue by gcobb321** [home-assistant/home-assistant-iOS#172]
**Background**...I have been working on an updated iCloud device tracker component (iCloud3) for more than 6 months that has many new features and exposes many new attributes.

-  It uses a dynamic polling interval based on distance from home, drive travel time using the Waze route mapper service, GPS accuracy, in-zone status, battery level, and other factors. 

- It checks to see if a devices polling update interval has elapsed every 15-seconds and, if so, updates the location information. Zones have a special interval time that defaults to every 2-hours and a Dynamic Stationary Zone is created if you haven't moved for a while. 

- Specific devices and device types can be included and excluded. 

- Distance is determined to a 100th of a mile/kilometer (eg. .25 miles) so distance based automations can be very specific (eg. If, .25 miles from home, open the garage door). 

- It updates the device's status automatically when you enter or exit a zone. No other device trackers are needed (OwnTracks, router based, NMAP, ping, etc.)

Current documentation is on my GitHub repositary at 
(https://github.com/gcobb321/icloud3). The code and automations are old so don't use them. I have it set up as a custom component on my rig and it's undergoing final testing (I hope). I'll be looking for others who want to try it out when it is ready. 

**Now for my request**...I would like to be able to automatically pause polling a device when it is put into Airplane mode and resume polling when Airplane mode is turned off. This could be done using a special device_tracker state (airplane_on, airplane_off) that is updated with a device_tracker.see service call.

**Comment by robbiet480** [comment]
@gcobb321 The issue here is that putting a device into Airplane Mode cuts off all communication, so there's no way for us to alert HA when we go into Airplane Mode. Furthermore, Apple doesn't provide a method to apps to determine when Airplane Mode is on/off.

**Comment by gcobb321** [comment]
Thought you'd like to know...

v1.0 of iCloud3 is now available for download

Go here  <https://github.com/gcobb321/icloud3>to download the latest 
version of iCloud3 and to review the documentation on the github.

A full list of changes enhancements since 0.86 are described in the 
ChangeLog.The Readme describes the functions and features of iCloud3 and 
contains many examples on how it provides a complete presence detection 
solution for Home Assistant.

Good luck. Let me know if you run into problems.

Gary Cobb



------ Original Message ------

**Comment by robbiet480** [comment]
@gcobb321 Congrats on the release!
