### ISSUE TITLE
Unable to delete hassio snapshot 

### ISSUE THREAD

**Issue by chartrand22** [home-assistant/home-assistant-iOS#174]
clicking the delete button when selecting a saved snapshot does nothing. 

Same works in a web browser, you get presented with a confirmation popup.

**Comment by KarimGeiger** [comment]
Can confirm. The app seems to get stuck every time a browser alert is being generated. Would be pretty cool to have alerts allowed in the app too.

By the way, great work so far! I really like the current beta version.

**Comment by mnoorenberghe** [comment]
This probably has the same root cause as #156
