### ISSUE TITLE
can't get to  "/dev-info aka. about page" on either my iPhone or iPad since release of 0.84.1

### ISSUE THREAD

**Issue by richpuch** [home-assistant/home-assistant-iOS#181]
Since .84.1 I can no longer get to the "/dev-info aka. about page" on either my iPhone or iPad.   It flashes up twice and then goes blank (white).  I want to change the setting to use lovelace as my default view. Any ideas?

**Comment by mnoorenberghe** [comment]
Does this happen with Safari on iOS too?

**Comment by richpuch** [comment]
Good idea, just tried Safari on my iPhone and am able to get to the "/dev-info aka. about page".  I then tried the iOS ap on both the iPhone and iPad and they are both working now.  As if it cleared some sort of cache on the home assistant server side.  Thanks for the input.

**Comment by richpuch** [comment]
Closing this...since it is now work.  👍
