### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by XusBadia** [home-assistant/home-assistant-iOS#183]
Would it be possible to implement custom icons to the app? I understand this is a very-low priority feature, but it'd be cool to have the option to change the app icon to different versions.

I've made a few color variations and a couple versions for the beta and dev versions.

![image](https://user-images.githubusercontent.com/1400863/50456400-6f41d900-0954-11e9-829f-e483a79a38d9.png)

If someone is willing to add the code necessary, let me know and I'll provide you with all the necessary assets!

For reference: https://developer.apple.com/documentation/uikit/uiapplication/2806818-setalternateiconname

**Comment by robbiet480** [comment]
@XusBadia Sure thing, I can try to work this into 2.0. Can you get me a zip of the original assets (PSD) as well as a 2048x2048 of each? I can drop them into fastlane to automake all the sizes if I have that.

Thanks

**Comment by XusBadia** [comment]
Here you go. 2048x2048 version for each icon and a PSD for each (also 2048x2048).

Let me know if I can help with anything else!

[Custom_Icons_HA_iOS.zip](https://github.com/home-assistant/home-assistant-iOS/files/2746237/Custom_Icons_HA_iOS.zip)

**Comment by robbiet480** [comment]
This is making it into 2.0!

**Comment by XusBadia** [comment]
Amazing news! 👍🏼 Let me know if I can be of any help.

**Comment by robbiet480** [comment]
![](https://cdn.discordapp.com/attachments/377667559303938050/546235202998108161/image0.png)

**Comment by XusBadia** [comment]
That was fast! Thanks!

**Comment by robbiet480** [comment]
@XusBadia Sorry to bring this back up but just realized that these should be in [home-assistant-assets](https://github.com/home-assistant/home-assistant-assets) so others can use them. Mind submitting a PR with them in a "Alternates" folder or something. If you don't have time I can do it. Thanks again, these look so good!

PS: Rebuild the launch screens tonight to use the environment specific icons, will be in the next beta as a surprise 😄

**Comment by XusBadia** [comment]
I just did! Hope I did it right!

**Comment by XusBadia** [comment]
Hi again,

I've been using the custom icons since you added them and I love them! And every friend that uses HA also uses them, so I thought it'd be nice to add some more variations. I've also improved the current ones (tweaked the gradients a bit). And since the long list can become unsustainable fairly quickly, maybe a grid would work better.
![Icon Mockup](https://user-images.githubusercontent.com/1400863/71473692-63dbf480-27d8-11ea-82a5-5e52e0e6b0c2.png)

Is it too difficult to add new icons, @robbiet480?

**Comment by robbiet480** [comment]
Nope, it’s easy. Feel free to submit new ones. I’ll also work on a grid.
