### ISSUE TITLE
Crash when opening settings in 1.5.0 beta

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/home-assistant-iOS#184]
App Version: 1.5.0  (32)
Device: iPad Air 2 (WiFi-only)
OS Version: iOS 12.0.1

When opening the settings screen in the 1.5.0 beta, the app crashes within approximately 1 second. The only way to prevent this appears to be disabling WiFi before opening the settings screen and then re-enabling it before saving any updated settings. Re-installing the app makes no difference - WiFi then needs to be disabled while doing the initial configuration or it will crash the same way.

Looking at the crash log, the exception type is EXC_BREAKPOINT (SIGTRAP).

**Comment by mnoorenberghe** [comment]
@gadgetchnnel Is this still a problem or did you workaround it by deleting the app and re-installing?

**Comment by gadgetchnnel** [comment]
The crash still happens for me in the the latest (non-beta) release of 1.5.0. Deleting and re-installing makes no difference. The only thing which works is disabling WiFi before opening the settings screen and then re-enabling it before saving any updating settings.
Searching the forum, there is a post dating back to January 2018 which appears to be the same issue:

https://community.home-assistant.io/t/app-crashes-when-i-click-on-settings-gear-icon/40296

One of the replies says:

> I’m experiencing the same issue - crash while trying to access the settings. It only happens on my wifi, not on LTE. I’m also using VLANs at home but my iPhone and HA are on the same VLAN. Also, it only crashes when I have the ios component loaded. If I remove ios: from my configuration.yaml and restart, the iOS app no longer crashes.

This is very similar to what I am seeing (except I can't use LTE as I have a WiFi-only iPad).

**Comment by gadgetchnnel** [comment]
I have just installed the 1.5.1 beta and this now appears to be resolved. I can now open the settings with WiFi enabled without it crashing.
