### ISSUE TITLE
1.5.0 Release schedule

### ISSUE THREAD

**Issue by gsdevme** [home-assistant/home-assistant-iOS#185]
Hi,

Is there any schedule or plan for the release of 1.5? If Im right in thinking Im stuck at a previous home assistant release until the user support lands?

Im not part of the testflight but Im wondering if the app will get released soon? I see there is a 2.0 testflight could I take from that that 1.5 is soon to be released?

**Comment by robbiet480** [comment]
It'll go to the store in the next few days!

**Comment by mnoorenberghe** [comment]
1.5.0 was released: https://itunes.apple.com/app/home-assistant-open-source-home-automation/id1099568401
