### ISSUE TITLE
iOS app needs to be updated?

### ISSUE THREAD

**Issue by wolverinevn** [home-assistant/home-assistant-iOS#187]
My system:
- Home assistant on Docker, version 0.84.6. Discovery enabled (and ios component also).
- iOS 12.1 with Home Assistant app

App used to work well until I removed and reinstalled the app.
Now it keeps asking me for server setup everytime I launch app even though I’ve already successfully signed in before (as owner).
App always asks for server address and password (?). If I input server address without password then press Save button, it complains about sign in error (for sure). After that, if I press done button, app move to home assistant ui.
I though it need an update.

**Comment by squircle12** [comment]
Agree - also forgets my settings and I've not been able to register for notifications - thought it was just me!

**Comment by robbiet480** [comment]
1.5.0 will go to the store in the next few days

**Comment by mnoorenberghe** [comment]
1.5.0 was released: https://itunes.apple.com/app/home-assistant-open-source-home-automation/id1099568401
