### ISSUE TITLE
Newest version of iOS app ask for location access constatly

### ISSUE THREAD

**Issue by h4nc** [home-assistant/home-assistant-iOS#196]
I don't want to use the location service, but I get "allow location access" after the is closed at the start up. 

I chose "Deny" but it will ask again.

Is this a known bug?

**Comment by arsaboo** [comment]
See https://github.com/home-assistant/home-assistant-iOS/issues/177

**Comment by h4nc** [comment]
Still no update available and still get those messaged all the time. Does anyone know when the update will be pushed?

**Comment by h4nc** [comment]
Fixed with the newest update. Thanks!
