### ISSUE TITLE
ios app reloads unexpectedly 

### ISSUE THREAD

**Issue by bmf7777** [home-assistant/home-assistant-iOS#197]
ios app version 1.5.0 and prior versions on iphone xs-max
app reloads page unexpectedly

this code added to ui-lovelace.yaml causes the reload ... without it all is well ... with the code, i typically can't scroll to half way point in my page before a reload is generated 

same issue on chrome, however safari does not seem to show the issue

      - type: picture-entity
        entity: camera.doorbird

**Comment by robbiet480** [comment]
@bmf7777 Failed to update this issue a few weeks ago when I investigated, but this is due to ongoing Safari on iOS bugs which should be fixed in the next iOS version. If you continue to have problems please open a issue in the home-assistant-polymer repo.
