### ISSUE TITLE
Location doesn't background update with an iPhone 6S

### ISSUE THREAD

**Issue by lancelon** [home-assistant/home-assistant-iOS#200]
I'm using an iPhone 6S and so is my wife. Since updating to 1.5.0 using Testflight, the iOS app doesn't background update our location unless we do a "one shot" update.

**Comment by garyak** [comment]
I'm seeing similar behavior on iPhone8, iOS 12.1.3, HassOS 1.9, iOS App 1.5. I receive zone enter/exit notifications, but when I open the App, current zone has not been updated. The App doesn't appear to update in the background as allowed.

**Comment by robbiet480** [comment]
Just confirming you are still experiencing this, yes?

**Comment by garyak** [comment]
Yes.

**Comment by lancelon** [comment]
Yes.

**Comment by robbiet480** [comment]
Mind taking a screenshot of your Settings.app view of Home Assistant like this one and posting it here?
![img_1689](https://user-images.githubusercontent.com/18516/53136883-8a386000-3535-11e9-9d25-017101d3aa97.PNG)

**Comment by garyak** [comment]
![settings](https://user-images.githubusercontent.com/47036329/53137397-e30cf600-353f-11e9-9a8c-2fddb55ece74.jpg)

**Comment by robbiet480** [comment]
@garyak While you're here, mind jumping on [Discord](https://discord.gg/RsQvRW) with me to do some quick one on one debugging?

**Comment by robbiet480** [comment]
@lancelon So I did some one on one debug with @garyak yesterday and he determined that he _was_ getting updates in the background. The easiest way to determine this is for you to turn on the "Background Fetch Notifications" setting in the app and then leave the app in the background and you should get notified shortly thereafter. Please note however that Background Fetch scheduling can vary from device to device, so I'd ask you to give it a full 24 hours without getting a notification before saying you are still having issues.

Let me know if you still aren't seeing the notification after 24 hours and i'll reopen this issue. Thanks!

**Comment by lancelon** [comment]
Hi @robbiet480  - hmmm - not sure - background fetch notifications are ALREADY turned on?

**Comment by robbiet480** [comment]
@lancelon Hmmm, if the background fetch notifications are already turned on in the app then I'm really not sure what's going on. If you would please reach out to me on [Discord](https://discord.gg/RsQvRW) so we can debug one on one that would be the next best step.

**Comment by garyak** [comment]
I've captured an iPhone screen video showing the app with a blank screen in the background and updating indicated location after becoming active (home/away). I was several miles from home when I opened the app. If nothing else, it's FYI.

![haupdate](https://user-images.githubusercontent.com/47036329/53444316-0f56c580-39cb-11e9-984b-ff93f35a65a5.gif)

**Comment by lancelon** [comment]
Hi Robbie - I don't know what,why or how - but for some reason the iOS app is now regularly telling me it's updating HA with background fetch updates. I haven't upgraded neither the app nor the iOS version. But something's happened. The ONLY thing I can think of is I left my phone on charge all night which I don't normally do, so my battery is at 90% now instead of the more usual 40%, 50% or 60%.
