### ISSUE TITLE
Better accuracy for GPS location

### ISSUE THREAD

**Issue by mildis** [home-assistant/home-assistant-iOS#207]
Current accuracy spans across multiple locations when zones are close (say home and kids school).
What about using `kCLLocationAccuracyBest` or `kCLLocationAccuracyNearestTenMeters` for CoreLocation settings ?

**Comment by robbiet480** [comment]
@mildis Just confirming what you are saying... you want to be able to set `desiredAccuracy` and `distanceFilter` [here](https://github.com/home-assistant/home-assistant-iOS/blob/211b704a5cecdf2caeb4296e35cd6456f0877b6d/HomeAssistant/Classes/OneShotLocationManager.swift#L23-L25) to any of the [CLLocationAccuracy](https://developer.apple.com/documentation/corelocation/cllocationaccuracy) values, right? You understand that the linked code only controls the one shot location manager which is used anytime we need a location that isn't region based? 

We don't have any accuracy filters on the region manager right now. Are you suggesting we add there?

**Comment by mildis** [comment]
I hadn't check back since the last test flight updates but while looking at the map view (the one accessed from the top-left burger menu), the GPS accuracy was low compared to the Apple Maps accuracy which was able to spot me more precisely.

Looking at the map now, it seems that the accuracy is now fine.
