### ISSUE TITLE
IOS Beta 12.2.2 breaks iOs app 1.5

### ISSUE THREAD

**Issue by jwelter1971** [home-assistant/home-assistant-iOS#211]
App starts and the settings page is populated but the app will not display the HA Lovelace UI.  Just a blank screen.

Safari on 12.2.2 also will not load the HA Lovelace UI so I suspect it's a javascript issue and not just the IOS app.

**Comment by MwC-Trexx** [comment]
Lovelace page working fine on IOS 1.5 for me.

**Comment by robbiet480** [comment]
@MwC-Trexx Is it loading okay for you on Safari?

**Comment by MwC-Trexx** [comment]
@robbiet480 it is working fine (other than issue with custom dark sky card)

**Comment by MwC-Trexx** [comment]
Does the OP have a 3rd party pop-up blocker installed maybe causing issues?

**Comment by robbiet480** [comment]
Content blockers wouldn't affect the app as we use WKWebView

**Comment by robbiet480** [comment]
@MwC-Trexx 	Just confirming, your Lovelace UI is working fine in both the HA iOS app _and_ Safari itself, right? (Other than the custom Dark Sky card)

**Comment by MwC-Trexx** [comment]
@robbiet480 Correct although 12.2b2 came out yesterday so I haven’t had a lot of time with that build yet.   I did use HA app though under 12.2b1 a fair amount though.   

As for safari use on iOS, I just did a spot test.  Had pop up blocker causing issues, but worked fine without from what I could tell. It is not my normal usage pattern.

**Comment by robbiet480** [comment]
@MwC-Trexx Can you provide a screenshot for us of what it looks like when not loaded?

**Comment by MwC-Trexx** [comment]
@robbiet480 I wasn’t the OP on this issue

**Comment by robbiet480** [comment]
@MwC-Trexx Sorry, you're right.

@jwelter1971 Can you provide a screenshot for us of what it looks like when not loaded?

**Comment by jwelter1971** [comment]
I got this working on 12.2.b2.

I reset the IOS device to clean state with 12.2.b2; reinstalled HA 1.5 released app, re-entered app settings and it is working.

I can only assume that because this phone was through many beta IOS and also beta HA app update cycles it had some crud still lurking.
