### ISSUE TITLE
Custom Dark Sky weather card broken

### ISSUE THREAD

**Issue by MwC-Trexx** [home-assistant/home-assistant-iOS#213]
Getting custom element doesn’t exist on IOS with 0.86, but works fine on PC browsers.

**Comment by robbiet480** [comment]
Is this an issue in Safari as well?

**Comment by MwC-Trexx** [comment]
Issue in safari and chrome both on iOS. Doesn’t matter whether connecting via IP, hassio.local, or external FQDN.

**Comment by balloob** [comment]
Is this a custom card or the weather card in Lovelace?

**Comment by MwC-Trexx** [comment]
@balloob it’s a custom card.  
https://community.home-assistant.io/t/custom-dark-sky-animated-weather-card/59816

**Comment by balloob** [comment]
You'll have to report that one to the custom card author. It's 99% certain not in our code.

**Comment by MwC-Trexx** [comment]
Updating the custom code for the dark-sky card to latest version resolved the issue.
