### ISSUE TITLE
Using URL Scheme will crash the app

### ISSUE THREAD

**Issue by daniarv** [home-assistant/home-assistant-iOS#216]
Hi,

I was planning to use the URL Scheme but when I tried  to use the function it always crashed the app.
A simple test is to open Safari and just type: `homeassistant://`
It will then ask me if I want to open the app Home Assistant, I press open and the app crashes.

iOS: 12.1.4
Home Assistant iOS: 1.5.0

Is it a known bug?
Do you have the same problem?

**Comment by robbiet480** [comment]
Fix will be in 1.5.1!
