### ISSUE TITLE
Quicker updating of status bar icon colors and header color to match newly set themes

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#219]
Home Assistant iOS app matches your theme colors, but it seems to be a little bit delayed. It would be nice if it could tie into Home Assistant's frontend.set_theme service or whatever to more instantly update these colors as the user changes the theme.

Here is a video demo showing what I mean. I cycled through 11 different themes and the top header/bottom settings icons never updated from the original blue color it was on. https://gfycat.com/earlyaromaticangwantibo

**Comment by robbiet480** [comment]
Fixed in 2.0
