### ISSUE TITLE
Cannot build in Xcode

### ISSUE THREAD

**Issue by TWilb** [home-assistant/home-assistant-iOS#22]
I cannot build the current Version. It is missing a target during pod install and that results in Dependency Analysis Errors during the build process in Xcode.

`pod install`
`Analyzing dependencies`
`[!] Unable to find a target named 'NotificationContentExtension', did find 'HomeAssistant', 'HomeAssistantTests', 'HomeAssistantUITests', 'APNSAttachmentService', 'CameraNotificationContentExtension', and 'MapNotificationContentExtension'.`

**Comment by robbiet480** [comment]
`git pull` && try again

**Comment by TWilb** [comment]
Thank you, it is running again.
