### ISSUE TITLE
iOS devices not getting push ID

### ISSUE THREAD

**Issue by junior466** [home-assistant/home-assistant-iOS#221]
**Home Assistant release with the issue:**

0.87.1
**Last working Home Assistant release (if known):**

0.87
**Operating environment (Hass.io/Docker/Windows/etc.):**

Ubuntu 16.04
Virtual environment
**Component/platform:**
iOS

**Description of problem:**

iOS component fails to get push ID.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
ios:
```

**Traceback (if applicable):**
```
The notify.ios platform was loaded but no devices exist! Please check the documentation at https://home-assistant.io/ecosystem/ios/notifications/ for more information
```

**Additional information:**

I've attempted the steps described [here](https://community.home-assistant.io/t/ios-devices-not-getting-push-id/99682/16?u=junior466) twice as a method of troubleshooting but had no success. 

Here's what my app looks like:

[Screenshot 1](https://i.imgur.com/n5hwb27.png)
[Screenshot 2](https://i.imgur.com/xS9EcLw.png)

**Comment by robbiet480** [comment]
Will look into this shortly. Can y'all provide your app version? (you can find it on Settings -> About under the logo)

**Comment by robbiet480** [comment]
Nevermind, this has been fixed, apologies y'all. Just force restart the app and it should register for notifications. Let me know if you're still having issues.

**Comment by eugenelai** [comment]
Wooo confirmed fixed! @robbiet480 out of curiosity can you outline the issue?

**Comment by robbiet480** [comment]
@eugenelai Had to make some changes to support the 2.0 beta and while they worked fine for beta and dev apps it silently broke the production app. A quick one line fix later and we were back in business.

**Comment by eugenelai** [comment]
Cheers!!!!!!!11

**Comment by aram535** [comment]
@robbiet480 I got the phones to generate a push id now -- thanks for that.  Now the push ids are not getting into HA (running 0.88 now).

**Comment by lancelon** [comment]
Anyone know if it's possible to setup the iOS companion app on the DuckDNS platform? I'm at working trying to figure out why notifications adamantly will not work anymore despite me changing/trying almost everything and I realised the one constant so far is that my phone and my HA instance are on separate IP networks...I've been using the DuckDNS addon to 'remote in' to my system and maybe (just for setup) you have to be on the same network??

**Comment by TomBrien** [comment]
@lancelon, is you’re problem the original issue here? Do you get the push-ID? What `service` are you sending to? Have you tried sending from dev tools?

**Comment by lancelon** [comment]
I have to confess my problem isn't the original issue, I do get push IDs, I just never get notifications on the device and the list of services on the HA side never shows in the list 'notify.mobile_app_[mydevice]' 
Mobile app otherwise works as advertised. And the odd thing is, it worked when I was on the various beta apps!

**Comment by TomBrien** [comment]
If you don’t see it in the services you probably need to restart home assistant

**Comment by lancelon** [comment]
Hi Tom

I wish it were that simple! Tried that lots of times. My new best idea, which I’m going to try tonight, is attempting the onboarding from the lan rather than duckdns. Few webhook errors in my logs so something’s definitely amiss.

Thanks
