### ISSUE TITLE
Theming of iOS app (feature request)

### ISSUE THREAD

**Issue by poldim** [home-assistant/home-assistant-iOS#225]
Not sure if this is possible, but can the iOS app pull the theme from within the HA instance?  Right now it uses the bright blue color which is the HA default.  I've set up a few themes for HA with `frontend` and it would be great if that could be synced to the color of the app.  I'm using an automation to switch themes between light and dark based on time of day.  Thanks.

![image](https://user-images.githubusercontent.com/16869713/53208064-59663280-35ea-11e9-9908-a90c5238c2e7.png)

**Comment by robbiet480** [comment]
Closing in favor of #219 which caused full theme support to be implemented in 2.0 via 4c8619650ca21b228e5929b6d524b88a9be26303
