### ISSUE TITLE
Default view setting

### ISSUE THREAD

**Issue by JulianKahnert** [home-assistant/home-assistant-iOS#23]
Hello and thank you for the great App! 👍

But one little feature request:
I think it would be very nice to have an option to add a string (e.g. `/group.livingroom`) to the default url. So you get to this tab right when you start the app:
```
https://<HA_URL>:8123/states/group.livingroom
```

**Comment by robbiet480** [comment]
Will try to get this into 1.0.4.

**Comment by mnoorenberghe** [comment]
What is the use case for this? Is it so you have different default views for iOS and web?

**Comment by JulianKahnert** [comment]
Hey, yes. My webui of HA shows several temperature sensors...and it would be awesome to start the app in a light/switch view.

**Comment by robbiet480** [comment]
Sadly, this is now unlikely without significant work in both frontend and iOS due to the way that authentication has been designed, we have to start on `/?externalAuth=1`.
