### ISSUE TITLE
Actionable notifications not working with live camera image

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#231]
In 2.0.0 (30) we found that actionable notification buttons are never loaded with a live camera view.

Works with static image or no camera entity but not the when camera view is there.

**Comment by olbjan** [comment]
Same notification works with live image and actionable notifications in 1.5, so this must be a regression.

**Comment by mgiako** [comment]
Same problem here. Also tried 1.5.1 with same config and there it works.

**Comment by robbiet480** [comment]
Should be fixed via 362bd1703c0b1dd0f560963c311b9d989cb1fbc4
