### ISSUE TITLE
Integrate with media controls API

### ISSUE THREAD

**Issue by postlund** [home-assistant/home-assistant-iOS#234]
I'm not sure how the media control API works in iOS, but would it be possible to integrate with that somehow? More or less pick a media_player entity and control it from the lock screen or so.

**Comment by robbiet480** [comment]
Very interesting idea! This could be enabled via [`MPNowPlayingInfoCenter `](https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter).

**Comment by postlund** [comment]
That would be awesome! Using this with a universal media player that "follows" the currently active media player at home (assuming that only one is used most of the time) would be very neat.

**Comment by robbiet480** [comment]
Tried to implement this just now because I'm doing some other media work today but turns out that I can't inspect now playing info of the system due to sandbox limitations, so sadly this is not possible to implement (at least for now). Sorry!

**Comment by imposibrus** [comment]
Maybe it became possible at least on macOS now?😁
