### ISSUE TITLE
Crash to Springboard on Hass.io add-on uninstall

### ISSUE THREAD

**Issue by derekbelrose** [home-assistant/home-assistant-iOS#235]
Home-Assistant IOS: 1.5.1
Home-Assistant: Hass.io 0.89.0

Problem: Tapping “Uninstall” on any Hass.io add on causes HA iOS to crash to springboard

Recreate: Connect to any Hass.IO instance running 0.89.0, tap Hass.io on the left, select a running add-on, tap “Uninstall”.

**Comment by robbiet480** [comment]
Fixed in 1.5.1 (4) I believe. Let me know if thats not the case!
