### ISSUE TITLE
no (easy?) way to get to ios app settings without killing app

### ISSUE THREAD

**Issue by maxandersen** [home-assistant/home-assistant-iOS#244]
trying to find a way to get to app settings on my ios 6s. the "gear" for ios app only shows after I have killed the app and starting it again. a few minutes later it slides away and I see no way to get it back. 

tried dragging and toucing on all edges, but no luck.

Bug or my error somewhere?

**Comment by martinhoess** [comment]
The problem is, you need a page where you can scroll up (back to top) then the toolbar is shown again.

But there is a general setting to disable the auto hide of the toolbar (Settings -> after "Device Id" -> General Settings -> Automatically hide toolbar)

**Comment by maxandersen** [comment]
Okey that works (find page that is scrollable) thanks
