### ISSUE TITLE
iOS app version 1.5.1 icons missing

### ISSUE THREAD

**Issue by rrubin0** [home-assistant/home-assistant-iOS#247]
Icons on the bottom row do not appear but can still be accessed by tapping. 

Additionally, service call notifications do not appear.

**Comment by arsaboo** [comment]
This affects both 1.5 and 2.0. Here's the [Discord reference](https://discordapp.com/channels/330944238910963714/551871772484698112/555946355000999956) for reproducing the bug and has been confirmed by a [few others](https://discordapp.com/channels/330944238910963714/551871772484698112/560459375316303872).

**Comment by robbiet480** [comment]
This affects both versions but in different ways.

**Comment by robbiet480** [comment]
Still an issue?

**Comment by rrubin0** [comment]
I’ve since moved to the 2.0 beta so I’m not able to check but 2.0 is coming
along nicely and working great, thanks!!

**Comment by arsaboo** [comment]
Still an issue with 1.5.1.
