### ISSUE TITLE
Make the beta public

### ISSUE THREAD

**Issue by benleb** [home-assistant/home-assistant-iOS#248]
What about making the beta app available to everyone interested? As iTunes Connect allows to do this via a simple link, it would be no additional effort for anyone.

**Comment by robbiet480** [comment]
The beta is public? [It's linked at the top of this thread](https://community.home-assistant.io/t/home-assistant-for-ios-2-0-beta-testing/107511?u=robbiet480). [Direct link to beta](https://testflight.apple.com/join/TUL8eu8N).

Can you point me to what gave you the idea that it is currently a closed beta? Thanks!

**Comment by benleb** [comment]
Hey Rob 😄 you told me in discord that you won’t add new people to the beta, around 3-4 weeks ago 😄✌️ I missed the thread as I am not very active in the forum. But it seems that I should change that... Thanks!
