### ISSUE TITLE
Beta: Toolbar obscures content and other issues

### ISSUE THREAD

**Issue by jamieshaw** [home-assistant/home-assistant-iOS#249]
**HA app version:**
2.0.0 (35)

**HA version:**
0.90.2

**iOS version:**
12.2 (16E227)

First and foremost, and most reproducible is that it obscures content on the page. In my scenario, with _hide toolbar_ set to **off**, scrolling to the bottom of a page view will obscure the bottom item of the page. It appears there is no 'padding' added to the page view to compensate for the new, fixed, floaty toolbar.

Additionally, but not as reproducable, I've had issues getting the toolbar to show again when _hide toolbar_ is set to **on**, as well as the controls being auto hidden despite the option being set to **off**.

**Comment by robbiet480** [comment]
Closing since, y'know, the toolbar is gone.

**Comment by jamieshaw** [comment]
Agreed just out of curiosity – is there a way to push location still, or is that an action specific thing now?

**Comment by robbiet480** [comment]
Pull to refresh also sends location.

**Comment by jamieshaw** [comment]
Noted – thanks!
