### ISSUE TITLE
App freezes or hangs when attempting to Enable location tracking

### ISSUE THREAD

**Issue by bagobones** [home-assistant/home-assistant-iOS#25]
Version: 0.42.3

I enabled notifications first, the app crashed but it did enable, then I went to enable location tracking and the app just freezes without prompting.

After using the Reset option in the app it worked the after subsequent attempts.

More testing on enabling these functions might be needed.

**Comment by jjpeet** [comment]
Hi, I've set up the app on three phones successfully (without an issue), and another two phones both which displayed the symptoms you mention.

The first three successful phones were a 7, SE & 5C. The ones with the problem were both 6S iPhones...

Hope that helps. Is there a way to capture logs from the app so I can send them in?
JP

**Comment by bagobones** [comment]
Deleting the app and doing it again it failed several times and succeeded others, I couldn't find a specific cause.

I am also not seeing anything in device trackers, the documentation is too incomplete right now, I assume I am missing a platform under the device_trackers section or something.

**Comment by robbiet480** [comment]
There's a fix coming out early this week. In the meantime, try [this](https://community.home-assistant.io/t/enable-location-tracking/15382/18?u=robbiet480) to fix the freeze when enabling location.

**Comment by jjpeet** [comment]
Other than ensuring I was on 0.42.4 and adding the code below to my config, everything works fine and all devices with the app working show up in known devices yaml,
```
# Enables iOS support
ios:
```

**Comment by Aaraeus** [comment]
Having the same problem on an iphone 6S right now. Will attempt to delete and redownload the app and see if that works.

FYI I've got the following in my configuration.yaml file:

```
# Enables iOS support
ios:
```

**Comment by bagobones** [comment]
FYI the app lost its state for both notifications and location when updating the iOS app to 1.0.4, it froze when trying to re-enable them.. Had to delete the app to enable them again.

**Comment by oldfart101** [comment]
tried all the above, iPhone 6 ios 10.3.2
nothing works, locks up when enable location tracking.

**Comment by boojew** [comment]
Same here. I’m running iOS 11 public beta 1 and  Home-assistant 0.48.1 and latest for the iOS app. On that note- should probably make the iOS app version number more obvious

**Comment by robbiet480** [comment]
I believe this might be fixed for good in the upcoming version. We shall see!

**Comment by talondnb** [comment]
I believe this is due to having Location Services access set to While Using. If you change this to Always, it becomes responsive again.

The While Using implementation seems to need some work..

**Comment by robbiet480** [comment]
Closing this as I haven't heard any issues reported about this and I've pinged a few users that I know had this problem.

Please comment if I'm wrong and this should be re-opened.
