### ISSUE TITLE
Add the ability to choose ringtones and other iOS device sounds when using the notify event 

### ISSUE THREAD

**Issue by FutureTense** [home-assistant/home-assistant-iOS#252]
Instead of the standard iOS notification sound when pushing a notify from an automation, add an extra field which will let you choose another sound.  I’m not sure how you would get custom ringtones from the device, but I believe push bullet allows you to use custom sounds.

**Comment by robbiet480** [comment]
@FutureTense [Let me know if this blew your mind.](https://www.home-assistant.io/docs/ecosystem/ios/notifications/sounds/)
