### ISSUE TITLE
After updating to beta 2.0.0 (39) I am getting an error every time I open the app

### ISSUE THREAD

**Issue by ikifar2012** [home-assistant/home-assistant-iOS#257]
The error I am getting is:
![image](https://user-images.githubusercontent.com/20800434/55687767-cfc2b800-593e-11e9-9212-d62f01c21f14.png)
I have added the mobile app component to HA (0.91.1) and after rebooting HA and restarting the app I get this error. 
I have tried changing the mobile app device id but it does not change in HA . So I think that would mean its not connecting to the mobile app component 
I don't know how I should send the logs as they do have the `base_url` in them

**Comment by ikifar2012** [comment]
I have tried resetting the app but it doesn't solve the issue

**Comment by robbiet480** [comment]
Known issue that will be fixed once 0.91.2 releases in the next hour or two.

**Comment by ikifar2012** [comment]
@robbiet480 I am still having the issue on version (40) of the app and (0.91.2) of HA

**Comment by ikifar2012** [comment]
Its a different error after resetting the app and updating 
![image](https://user-images.githubusercontent.com/20800434/55759540-95811580-5a27-11e9-9b79-511fbbf93c5d.png)

**Comment by robbiet480** [comment]
Build 41 will fix this, gonna release it tomorrow.

**Comment by ikifar2012** [comment]
How long does it take for me to be able to download build 41 has it been released already because I don't see it in testflight. Is that just testflight being slow?

**Comment by robbiet480** [comment]
41 didn't happen yet, it's gonna happen in the next 6-9 hours. Sorry!

**Comment by ikifar2012** [comment]
No problem!!

**Comment by robbiet480** [comment]
@ikifar2012 Assuming you aren't experiencing this anymore since we are now at build 44 and I haven't heard anything about this error anymore. Closing, let me know if it's still a problem.
