### ISSUE TITLE
HomeAssistant iOS1.5.0 can't work with homeassitant 0.91.1

### ISSUE THREAD

**Issue by chenyz1984** [home-assistant/home-assistant-iOS#259]
HomeAssistant iOS1.5.0 can't work with homeassitant 0.91.1，
I install the HA through docker on synology. After create user/password on PC(chrome) , the PC can work rightly.When  I login in the HA use home-assistant-iOS on iphone 6s(iOS 12.1) ,it login failed , the error message is "Error: invalid client id or redirect uri",but the username and the password are all both right.
If I install the HA throuth docker on synology ,then create user/password by home-assistant-iOS. it can work rightly for a little time, then raise "Error: invalid client id or redirect uri". But the pc can work rightly all the time
![111](https://user-images.githubusercontent.com/20869868/55709428-db83ac80-5a1a-11e9-9304-610f56411a69.png)

![222](https://user-images.githubusercontent.com/20869868/55709457-ea6a5f00-5a1a-11e9-827a-afec821279bd.png)

**Comment by robbiet480** [comment]
Hi ChenYingzi,

This is a problem with your computer. Usually, it's due to IPv6 being misconfigured, or your SSL certificates are incorrect. Can you SSH to your computer and run this: `curl -vL6 https://home-assistant.io/iOS`. If you get an error, that means your IPv6 configuration is bad and must be fixed.

Let me know!

**Comment by chenyz1984** [comment]
> Hi ChenYingzi,
> 
> This is a problem with your computer. Usually, it's due to IPv6 being misconfigured, or your SSL certificates are incorrect. Can you SSH to your computer and run this: `curl -vL6 https://home-assistant.io/iOS`. If you get an error, that means your IPv6 configuration is bad and must be fixed.
> 
> Let me know!

Oh ! Thanks! The command returned 'curl: (7) Error', and my router really doesn't support IPv6! Now, I can't use the app 'home-assistant-iOS' until my router support IPv6？Is there another solution ?

**Comment by robbiet480** [comment]
@chenyz1984 You can absolutely use the app even if you don't have IPv6, you just need to make sure that Home Assistant isn't trying to use IPv6 when it isn't properly configured. As a next step, i'd suggest figuring out how to disable IPv6 at the OS level.

**Comment by robbiet480** [comment]
Also, `curl -vL https://home-assistant.io/iOS` (notice the missing `6`) should _not_ return any errors.

**Comment by chenyz1984** [comment]
Hi robbiet480:
  Thank you very much! The problem was solved after IPv6 was disabled at the Synology OS!

**Comment by robbiet480** [comment]
Thanks for letting me know, closing this issue.
