### ISSUE TITLE
Onboarding ignores cloud remote connection state

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#260]
Given the following setup:
- Nabu Casa Cloud connected
- Remote Connection set up but disabled
- HA Companion app 2.0b39

After the setup the app sets up it's connection to Home Assistance via the remote connection through Nabu Casa. This is not allowe and we get ssl and connection errors.

The integration needs to check if remote control is enabled in HA and either set up using the remote connection or not use remote connection.

**Comment by robbiet480** [comment]
@olbjan Closing this as I believe it was fixed with that commit and I haven't heard otherwise.
