### ISSUE TITLE
Device tracker ignores Device-ID

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#262]
Upon reset of the app and following setting it up again the device_tracker isn't using the device-id set in the app (iphonename_beta in my case), Instead a new entry get's added to known_devices with a device ID such as 6dc4f9f9d5ed43ada94e3d87d7216a33. This tracker does also get updated but does not get the additional iOS information in its payload (SSID etc.).

**Comment by olbjan** [comment]
Additional info:

This happens in a weird way:
When you upgrade the app e.g. from beta 35, the device tracker will still update the old entity. When you then restart only HA, any further updates will go to a new entity and not include the additional sensor data.

**Comment by robbiet480** [comment]
Fixed in backend via https://github.com/home-assistant/home-assistant/pull/24155#event-2370564240
