### ISSUE TITLE
Siri Shortcuts "Error during api.callService" in iOS 2.0 b40

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#268]
In iOS 2.0 b36(?) to b40 Siri Shortcuts seem to have a several second delay before activating, and they also show the following error below. The shortcuts still seem to execute successfully though despite this error.

My setup in the iOS app is using a Nabu Casa URL and regular user account if that makes any difference.

![image](https://i.imgur.com/Yr4mbwK.jpg)

**Comment by krissen** [comment]
Same issue here. If I’d wager a guess, I’d also say since b36 or so. For the past three, for sure, including current, b40.

**Comment by dcollura83** [comment]
Same exact issue here also.
