### ISSUE TITLE
Restore battery_level sensor in 2.0b

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#269]
Requested this on Discord earlier and was told ok, just posting here so it doesn't get forgotten.

2.0b40 consolidated the battery_state and battery_level into a single "battery" sensor, with the idea being that anyone who still wanted battery level could just create a template sensor. 

That is fine for more advanced users, but a lot of folks won't know how to create a template sensor and will lose basic functionality they already had... The transition from `ios` to `mobile_app` is going to come with a number of breaking changes and this one seems entirely avoidable.

**Comment by robbiet480** [comment]
Fixed
