### ISSUE TITLE
Add "Connected via" app name to Mobile_App Integration

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#270]
Under Integrations -> Hue it says "Connected via Philips hue" and I think it'd be useful to have something similar for the mobile_app integration, so users could know which app the sensors belong to.

A user could have one device with ten different mobile_apps installed on it, so having the app name listed would be a nice way to differentiate them. Here is an example mockup of how it could look (again, based off Hue integration). 

![image](https://i.imgur.com/hElgD6Z.jpg)

And it would be even cooler if you could make the app name link to their official website or HA forum topic or something, so users who might be stuck could easily get support. So I was thinking maybe the developers integrating mobile_app could specify certain info (app name, website, support email) in a json file or something.

This might be more of a Home Assistant enhancement request, so feel free to close this issue if it doesn't belong here.

**Comment by robbiet480** [comment]
Closing this as #265 has been implemented instead which will make the name of the integration the app name.
