### ISSUE TITLE
Use "Cellular" instead of "4G" for connection_type sensor

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#271]
I [posted this on Discord](https://discordapp.com/channels/330944238910963714/551871772484698112/565586383524331530) earlier, but adding it here too so it doesn't get lost. For `sensor.connection_type` I think that it should just report "Cellular" instead of a more specific "4G" designation. 

I think most people just want to know whether they're on Wi-Fi or Cellular and don't really care about the nitty gritty details. But more importantly having the state be 4G makes it a lot more difficult to write automations surrounding it, because now users would have to add more logic to catch all the possible states like 4G/5G/LTE/3G/Edge and whatever gets added in the future.

Having the sensor state report either "Wi-Fi" or "Cellular" seems a lot more simple and also more future proof. The 4G part could always be an attribute of the sensor for people who want that information.

The icon for Cellular could be `mdi:signal-cellular-3` btw.

**Comment by robbiet480** [comment]
Fixed
