### ISSUE TITLE
I’m getting a Token Deleted notification every minute until my limit expires

### ISSUE THREAD

**Issue by simonk83** [home-assistant/home-assistant-iOS#277]
![image](https://user-images.githubusercontent.com/518440/56702317-ada2a580-6746-11e9-9c89-47d1b138b429.png)

I'm not really sure where to start troubleshooting this one.  I did recently add my nginx reverse proxy external address to the app, and the base url details to the HA config, but I just tried removing both of those and just going back to the internal address and it hasn't made a difference, still getting the notifications...

**Comment by robbiet480** [comment]
What version? 1.5 or 2.0 Beta?

**Comment by simonk83** [comment]
Sorry, it's 1.5.1

**Comment by robbiet480** [comment]
So did you write a automation to notify you when a token is deleted? I don't think this is a notification that we currently send automatically.

**Comment by simonk83** [comment]
No I didn't, I'm not completely clear which token it's referring to to be honest (presumably an access token), I've never seen this before...

I do have one notification set up, as below:

# ios app
ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'UNLOCK_DOOR'
            title: 'Unlock Door'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

I use node-RED to trigger this, but the last time that was called was about 15 hours ago:

![image](https://user-images.githubusercontent.com/518440/56702678-a67c9700-6748-11e9-895e-e7aac7c1868d.png)

**Comment by robbiet480** [comment]
The only token I could think of would be the access token yes. Can you try hitting Validate in Settings and logging in again? That will get you a totally fresh token.

**Comment by simonk83** [comment]
> The only token I could think of would be the access token yes. Can you try hitting Validate in Settings and logging in again? That will get you a totally fresh token.

Hmm, they're still coming in.  Weird!

**Comment by robbiet480** [comment]
Hit the reset button in settings, force quit the app and reopen.

**Comment by simonk83** [comment]
> Hit the reset button in settings, force quit the app and reopen.

Ok I'll do that in a sec, I just disabled all my node-RED flows, just in case

**Comment by simonk83** [comment]
Ohhhhhhh I'm an idiot.  Sorry Robbie, this is totally my fault, I'll close this.  I have an automation in NR I totally forgot about as it only fires every 72 hours and this is the first time it's triggered. It's clearly looping and I have accounted for that.
Sorry to waste your time!

**Comment by robbiet480** [comment]
Just glad we got it figured out :)
