### ISSUE TITLE
Suggested value error and wrong keyboard error

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#279]
This is on 2.0b40

Siri Shortcuts -> Call Service:  media_player.volume_mute

for the `is_volume_muted` it has a suggested value of "1" even though the example in Home Assistant Services page has `true` ... I thought it was pulling this data directly from HA. 

When you tap on the `is_volume_muted` row in this screenshot, you get the 0-9 numberpad keyboard instead of the fill-fledged keyboard, so there's no way to type `true` or `false` (the only two accepted values for this service). Even when I tried pasting in `true` it wouldn't save.

So this service is unusable as a Siri Shortcut, at least in b40. There might be other areas with this same issue but this is one that I just ran into. 

Edit: also confirmed on `media_player.shuffle_set` service. I suspect this bug applies to any service that takes `true` / `false` options. 

![image](https://i.imgur.com/G8EgzsX.jpg)

**Comment by robbiet480** [comment]
Issue is that iOS interprets `true` to be `1` and `false` to be `0`.

**Comment by SeanPM5** [comment]
Fixed in b55.
