### ISSUE TITLE
Does not update when device id contains a space

### ISSUE THREAD

**Issue by makzdot** [home-assistant/home-assistant-iOS#28]
I noticed the app wasn't updating (Or hass was not accepting updates, I don't know) but when I changed the device id to something without a space it started working again.

**Comment by cmsimike** [comment]
Same here - I had previously named my device mikeapp. At some point, an update (maybe it was the transition from testflight-> release) my app was named iphone7, which wouldn't update the device named that. After switching back to mikeapp, the location updates started working again.

**Comment by mpjanofsky** [comment]
Also seeing the same issue when the device ID contains a dash - HA was not seeing the phone with mikes-iphone, but mikesiphone works.

**Comment by robbiet480** [comment]
This hasn't been a issue for a long time, since we've enforced certain characters in the field.
