### ISSUE TITLE
Watch App action icons disappear after use

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/home-assistant-iOS#280]
## Issue:
After pressing an action in the the watch app, the assigned icon disappears for an amount time. I'm unsure if this is a set time or somewhat random. In the first screenshot below, the top action was fired roughly 9 hours previously and still has no icon, the lower action has not been used for a few days. Icons on the 3D touch screen of the phone app show correctly and don't disappear after use. Action definition shown in second screenshot

## Steps to reproduce:
1. Create action with icon. 
2. Send actions over to watch from Apple Watch menu of phone app
3. Open watch app and press action.

![IMG_0133](https://user-images.githubusercontent.com/12411302/56861123-eedcc480-6995-11e9-92f4-4ef0a924cff6.JPG)
![IMG_0134](https://user-images.githubusercontent.com/12411302/56861236-e3d66400-6996-11e9-9719-6fa4beade94a.JPG)

**Comment by robbiet480** [comment]
Part of the issue here is that the action background is white and the loading indicator I use is also white.

**Comment by robbiet480** [comment]
Fixed in 6d47e45f295c2e028e7e5781ebf85ef88cb3cd26

**Comment by robbiet480** [comment]
Fixed at 6d47e45f295c2e028e7e5781ebf85ef88cb3cd26
