### ISSUE TITLE
New on boarding does not work when Remote UI is off and nabu casa cloud URL is configured

### ISSUE THREAD

**Issue by derekbelrose** [home-assistant/home-assistant-iOS#281]
Version 2.0.0 (42).  

Nabu Casa remote control is configured but turned off. Onboarding got to configuring sensors and just sat there. After turning Remote Control on, the app immediately completed the process.

After it was configured and working, app continued to work correctly when Remote Control was turned off.

**Comment by astrandb** [comment]
Same problem in (43).
Most of the sensors are created, but not all. When restarting it looks random which are created and which are not.

**Comment by robbiet480** [comment]
Should be fixed in build 44 via https://github.com/home-assistant/home-assistant-iOS/commit/ed5d2d4dbe27ed60ee447344b1ec2522400b846b

Related: #285
