### ISSUE TITLE
Can't press the 'Close' button on the 'For best experience'-screen (iPhone SE)

### ISSUE THREAD

**Issue by Alwik** [home-assistant/home-assistant-iOS#282]
Both in portrait as in landscape mode, clocking 'Close' doesn't work.
Tried multiple times, force-closed etc.
All other buttons in the onboarding-flow work correct
Happend on both 2.0b42 as 2.0b43

**Comment by robbiet480** [comment]
@Alwik Let me know if upcoming build 44 fixes your issues, thanks!

**Comment by christhehoff** [comment]
Still and issue for me. This time it reset all the “Allow” options (which could then be selected) but still unable to hit the “Close” button.

**Comment by Alwik** [comment]
Hi @robbiet480 , indeed, same problem as before (like christhehoff already mentioned)

**Comment by imuncas** [comment]
I confirm, the issue is still there in 44.

**Comment by robbiet480** [comment]
For sure fixed via 0122292d67a982a5a5188c4ffaac90411fcedc2a along with other iPhone SE issues.
