### ISSUE TITLE
[2.0b43] Onboarding stuck on setting up sensors when Nabu Casa Cloud enabled

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#285]
With Nabu Casa cloud enabled (Remote UI not enabled) the onboarding process never finishes the last step: settings up sensors. The Integration is set up though and all sensors are there but onboarding never finishes.

**Comment by jsiemek** [comment]
As Derek wrote:

After turning Remote Control on, the app immediately completed the process.


Wysłane z iPhone'a

**Comment by olbjan** [comment]
That's even worse....

**Comment by robbiet480** [comment]
Should be fixed in build 44 via https://github.com/home-assistant/home-assistant-iOS/commit/ed5d2d4dbe27ed60ee447344b1ec2522400b846b
