### ISSUE TITLE
Activity related sensors are not created.

### ISSUE THREAD

**Issue by astrandb** [home-assistant/home-assistant-iOS#289]
Sensors related to physical activity are not created. Permissions are enabled in IOS setting. I think it worked in b42.

**Comment by olbjan** [comment]
It may be that your localisation/language has activity translated to something containing a non-ASCII character and that keeps the sensor from being created. That's my guess right now as we introduced translation strings for sensors, something some of us decided was a bad idea for this reason as well...

**Comment by olbjan** [comment]
#284

**Comment by astrandb** [comment]
Still not created in Build 44.
I have wiped out all traces of old entries in .storage/ and deleted the app from my iPhone and started over.
With same result.

**Comment by olbjan** [comment]
Can confirm. No sensors created here either with 44

**Comment by robbiet480** [comment]
Probably a timing issue since the sensors wont be created if we don't have the motion permission but we ask for the motion permission after we register sensors.
