### ISSUE TITLE
List of various sensor issues

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#290]
I reported most of these in Discord last night but thought it'd be helpful to also make a list here.

- [X] ~~`sensor.ssid` has the wrong name and entity id. The sensor itself works fine but it's incorrectly named "BSSID" and so the `sensor.ssid` appears to be missing and it also appears to the user that there's a duplicate `sensor.bssid_2` (even though it's really just `sensor.ssid` with wrong name).~~ Fixed via https://github.com/home-assistant/home-assistant-iOS/commit/fcbe20a4923e584b23913a06430ad1213da60882
- [ ] `sensor.distance` does not ever update, has never updated once since my last restart 13 hours ago
- [ ] `sensor.steps` also doesn't ever update, it actually updated one single time with a value of "1" before dropping back down to 0 immediately a minute later. https://i.imgur.com/r94hjvO.png
- [ ] `sensor.floors_ascended` has the same issue as steps sensor above, it never updates and the one time it did update it had a value of "1" for that same exact minute before immediately going back to 0. https://i.imgur.com/oeghWbN.png
- [ ] `sensor.floors_descended` has not updated period.
- [X] ~~Not necessarily a bug, but for `sensor.battery_state` the attribute for battery level is titled simply "Level" when the standard across all other battery sensors (including HA iOS 1.5.1 - there https://i.imgur.com/vDKdBzx.png) I've seen in Home Assistant is "Battery Level". Should probably be changed for consistency sake imo.~~ Fixed via https://github.com/home-assistant/home-assistant-iOS/commit/491c534f516a8135c16474d877a4e0764b390d1a
- [X] ~~Also not necessarily a bug, but the `sensor.cellular_provider_0000000100000001` should imo be `sensor.cellular_provider` ... Seems like it's attaching the Carrier ID attribute to the end of the entity. Not only does this look bad and take up majority of the entity-row but this would probably mean that depending on users carrier they get different entity ID from everyone else? Then it's harder to do support etc too. Unless I am misunderstanding...~~ Fixed via https://github.com/home-assistant/home-assistant-iOS/commit/6235d3ff8ab9447cb6f892ee8ba98c8b4b50d7bd

**Comment by PierpaoloPernici** [comment]
7. `sensor.cellular_provider_0000000100000001` should be `sensor.cellular_provider_SIM1` or something like that. The number It's not related to the provider but it's the same on all of our phones. I guess Xs users have an 0002 too for the eSim.

**Comment by robbiet480** [comment]
@SeanPM5 Are you sure that your motion permission is enabled?

**Comment by robbiet480** [comment]
1 fixed by https://github.com/home-assistant/home-assistant-iOS/commit/fcbe20a4923e584b23913a06430ad1213da60882 (#284)
6 fixed by https://github.com/home-assistant/home-assistant-iOS/commit/491c534f516a8135c16474d877a4e0764b390d1a
7 fixed by https://github.com/home-assistant/home-assistant-iOS/commit/6235d3ff8ab9447cb6f892ee8ba98c8b4b50d7bd

**Comment by mgiako** [comment]
I think that the sensors don't update because they are inherited from a previous version and not really active. In 43 and 44 they're not created at all. See #289.

**Comment by SeanPM5** [comment]
> @SeanPM5 Are you sure that your motion permission is enabled?

Yes 100% sure. I'm fairly certain motion permission is required for `sensor.activity` to work, and that is updating fine for me. It's the various other pedometer ones like steps, distance, floors ascended/descended, and now current active pace that are not updating for me.

**Comment by robbiet480** [comment]
Remaining sensor issues should be fixed by 54d80b2. I wasn't correctly checking if we had the motion permission :(
