### ISSUE TITLE
[2.0b43] Log out button doesn't work on Connection page

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#291]
The "Log Out" button on the connection page does not appear to do anything. 

Tapped that numerous times and was not logged out, or given any type of error or anything. The button turned grey when pressed so it's recognizing the press, but does not appear to be hooked up to anything (yet?).

![image](https://i.imgur.com/aqYfIPK.jpg)

**Comment by robbiet480** [comment]
Not hooked up to anything yet because it requires backend work.
