### ISSUE TITLE
Apple Watch app cannot be installed

### ISSUE THREAD

**Issue by 2092769** [home-assistant/home-assistant-iOS#294]
I installed home assistant for IOS app version 2.0.0 bete (43) on my mobile phone

All the IOS devices, including the iPhone and ipad, ran smoothly during my installation and testing. But when installing on the Apple watch platform, it always shows that the installation is in progress, even if the app on the IOS end matched with the watch is uninstalled and reinstalled, it will not help.

I would like to ask the professionals of R&D team to help me solve this annoying problem. Thank you.

**Comment by lgauthier** [comment]
Found this after a lot of Googling. For whoever starts looking into this issue, you'll probably want to take a look at [this SO post](https://stackoverflow.com/questions/55886569/testflight-couldnt-install-on-apple-watch)

So far, this seems to only be an issue for apple watch apps that use certain CocoaPods. The project I'm working on has this issue with CocoaLumberjack. After I removed it from the watch app, we were able to install the watch app fine from TestFlight again. I also tested out adding different pods to the watch app (I tried Alamofire and AFNetworking) and I was able to install the watch app for those builds as well. The guy who posted on SO is having the issue with ObjectMapper. So, it seems to only be an issue if you're using certain CocoaPods. 

Hopefully this is just an issue on Apple's side of things and they can resolve it soon.

**Comment by lgauthier** [comment]
@robbiet480 Wanted to tag you since it looks like you're working on the watch app for this project?

**Comment by TomBrien** [comment]
Looks like the issue may be that WatchOS now requires UTF-16; see [this Apple Developers Forum post](https://forums.developer.apple.com/thread/99576). I would have a guess that now the name of the Watch App has gone from `Watch App` to `Home Assistant β` this may be the issue. Possibly also an issue with the Dev build?

My `Watch App` is also stuck upgrading to `Home Assistant β`, but is usable.

https://github.com/home-assistant/home-assistant-iOS/blob/9d8b01421482145bd7bfcb2d46cf2164f2936512/HomeAssistant.xcodeproj/project.pbxproj#L4257

https://github.com/home-assistant/home-assistant-iOS/blob/9d8b01421482145bd7bfcb2d46cf2164f2936512/HomeAssistant.xcodeproj/project.pbxproj#L4654

**Comment by robbiet480** [comment]
Reverted in build 44 which is coming shortly, thanks all!

**Comment by lolouk44** [comment]
Thanks @robbiet480 
Just attempted install on watch with build 44 and still get the same error message.
Let me know what you need to help you get this fixed.

**Comment by robbiet480** [comment]
Yeah just saw that myself. Oh well. Saw this error from TestFlight via Console which is a clue at least:

```
Watch Install Update (for iOSAppID: 1228023491, iOSBuildID: 41267607, buildVersion: 2.0.0 (44)):
Could not find a matching profile. Profile bundleIDs: (
    "io.robbie.HomeAssistant.beta.watchkitapp",
    "io.robbie.HomeAssistant.beta.watchkitapp.watchkitextension"
)
```

Will probably have to open a trouble ticket with Apple tomorrow.

**Comment by robbiet480** [comment]
![image](https://user-images.githubusercontent.com/18516/57014558-7b20fe80-6bc5-11e9-992f-f391faeeb946.png)

**Comment by robbiet480** [comment]
Oh just quickly found this https://forums.developer.apple.com/thread/116139

**Comment by lolouk44** [comment]
Great thanks. Above link is exactly what I'm experiencing too.
Shout out if you need any info / logs / other from me

**Comment by robbiet480** [comment]
Full log. Will open a DTS tomorrow.

```
default	04:01:36.472795 -0700	TestFlight	Watch Install Update (for iOSAppID: 1228023491, iOSBuildID: 41267607, buildVersion: -):
Starting Install
default	04:01:36.479530 -0700	TestFlight	Watch Install Update (for iOSAppID: 1228023491, iOSBuildID: -, buildVersion: 2.0.0 (44)):
Downloading iOSBuild based on appID and version
default	04:01:37.337961 -0700	TestFlight	Watch Install Update (for iOSAppID: 1228023491, iOSBuildID: 41267607, buildVersion: 2.0.0 (44)):
Switching install status to 1
default	04:01:37.388762 -0700	TestFlight	Watch Install Update (for iOSAppID: 1228023491, iOSBuildID: 41267607, buildVersion: 2.0.0 (44)):
Downloading Profiles
default	04:01:39.400359 -0700	TestFlight	Watch Install Update (for iOSAppID: 1228023491, iOSBuildID: 41267607, buildVersion: 2.0.0 (44)):
Profiles Downloaded
default	04:01:39.400681 -0700	TestFlight	Watch Install Update (for iOSAppID: 1228023491, iOSBuildID: 41267607, buildVersion: 2.0.0 (44)):
Could not find a matching profile. Profile bundleIDs: (
    "io.robbie.HomeAssistant.beta.watchkitapp",
    "io.robbie.HomeAssistant.beta.watchkitapp.watchkitextension"
)
default	04:01:39.400802 -0700	TestFlight	Watch Install Update (for iOSAppID: 1228023491, iOSBuildID: 41267607, buildVersion: 2.0.0 (44)):
Runner Failed: -
default	04:01:39.410441 -0700	TestFlight	Watch Install Update (for iOSAppID: 1228023491, iOSBuildID: 41267607, buildVersion: 2.0.0 (44)):
Runner Completed - Succeeded:0, FinishReason=3
```

**Comment by robbiet480** [comment]
Apple Developer Support case ID: 20000050632760

**Comment by robbiet480** [comment]
Radar mentioned in forum thread: 50346984

**Comment by robbiet480** [comment]
Apple wants me to submit a bunch of info and maybe it'll get fixed. That forum thread is growing though, so at least it's not just us having this issue.

**Comment by robbiet480** [comment]
@2092769 @lgauthier @TomBrien @lolouk44 Mind providing me your Apple IDs and names? Apple Developer Support needs as many people as possible that are experiencing this. Thanks

**Comment by lolouk44** [comment]
Sure. What name and Id address you after? Where do I get this?

**Comment by robbiet480** [comment]
@lolouk44 If you go into the TestFlight app and click your picture in the top right, just a screenshot of that page should be everything I need.

**Comment by lolouk44** [comment]
Just emailed you a screenshot. Thanks

**Comment by robbiet480** [comment]
https://github.com/CocoaPods/CocoaPods/issues/8754

**Comment by ecam315** [comment]
Just emailed you the info you requested above

**Comment by krissen** [comment]
b49 probably wasn’t expected to fix this, but just chiming in that the Watch app isn’t being installed with that version either.

**Comment by TomBrien** [comment]
I have just succesfully installed the watch app. Running build 54 but I don't believe that has anything to do with it.

**Comment by lolouk44** [comment]
That's interesting, I'm in the same position. Just read @TomBrien 's message and the app is installing on my watch too as I write this

**Comment by davidbb** [comment]
Confirming the watch app installs on build 54.

**Comment by SeanPM5** [comment]
Thanks for all the successful reports, this issue appears to be fixed as of this morning.

If anyone is still **NOT** able to install the Apple Watch app through Testflight with build 54 please reply to this and I'll reopen.
