### ISSUE TITLE
[2.0b43] Cellular Provider Information for empty Sim iPhone Xs

### ISSUE THREAD

**Issue by norges** [home-assistant/home-assistant-iOS#295]
I use only the esim in my iPhone Xs but get the following information:

![IMG_2367](https://user-images.githubusercontent.com/2143057/56982337-628ef500-6b81-11e9-8d3a-10b23427831b.JPG)
![IMG_2368](https://user-images.githubusercontent.com/2143057/56982338-628ef500-6b81-11e9-94b2-df25042b20c9.JPG)

I would expected also the entry Allows VOIP and Carrier Name  N/A for the Carrier ID 0000000100000001 which corresponds with the physical sim slot.

I use the 2.0 beta build 43 with Homeassistant in a hassio install version 0.92.1. If more information are necessary I'm happy to deliver them.

**Comment by robbiet480** [comment]
Did you ever have a SIM in the physical slot? I'm guessing whats happening here is Apple stores whatever the SIM was last in the physical slot.

**Comment by robbiet480** [comment]
Did you ever have a SIM in the physical slot? I'm guessing whats happening here is Apple stores whatever the SIM was last in the physical slot.

**Comment by norges** [comment]
Yes I had a physical Sim in the slot on the first day I had the phone. 
I tried it with a Sim card of another provider and It is as you guessed, even after removing a SIM card from the physical slot the provider name stays at that information. 
I'm thinking it could be useful to write this in the documentation for the time the app will be released, just for the case others will come across this.
Sorry for disturbing you with this.

**Comment by robbiet480** [comment]
@SeanPM5 mind adding this to docco?

@norges Thanks for testing & reporting back!
