### ISSUE TITLE
[2.0b43] device_tracker no longer contains altitude attribute

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#297]
Comparing the device tracker from 2.0b43 to 1.5.1b3 the altitude attribute is missing. I think this might be worth adding back.

**Comment by robbiet480** [comment]
Altitude is being sent if its available. If most of your location updates are due to region entries/exits then you may not be seeing altitude most of the time.

**Comment by olbjan** [comment]
You're right! On a manual update the altitude attribute appeared.
