### ISSUE TITLE
Changing Device ID does not change battery senor names correctly

### ISSUE THREAD

**Issue by bagobones** [home-assistant/home-assistant-iOS#30]
I changed my Device ID from the default (the phones name) to a new name.. While the device tracker name updated, two new sensors where created with the OLD Device ID and sensor.oldname.battery_level_2 and  sensor.oldname.battery_state_2 at the end.

**Comment by cmsimike** [comment]
Good catch - the sensors for battery state and level do not reflect the name of the app. I have noticed this too

**Comment by ntalekt** [comment]
Same here.

**Comment by bagobones** [comment]
Still outstanding. 

Over all it might be better if the iOS clients registered more uniquely and then used the Friendly Name system on the server side that other sensors mostly use.

**Comment by TomBrien** [comment]
This is addressed in the 2.0 version of the app and will be fixed there
