### ISSUE TITLE
notify service not being created

### ISSUE THREAD

**Issue by glassbase** [home-assistant/home-assistant-iOS#300]
First of all, thanks @robbiet480. Your mental health is more important than beta updates/fixes. 

I updated to v44 this morning. Reset app. Deleted all details from .storage. I am not getting the notify service registering. 

On the forum, most people suggested restarting HA a bunch of times with the app open. That hasn't worked for me with v44, but it has in past.

**Comment by glassbase** [comment]
And now all of a sudden it registered a notify service. So weird.

**Comment by olbjan** [comment]
I also had trouble with notify service not being created upon install of 44. I opened notification settings, clicked import categories and then restarted HA and the service was there.

**Comment by robbiet480** [comment]
Possible fix in bc300da64dc9a756f873dcd675cf6de04561494a
