### ISSUE TITLE
Theming Issue - Can't Read Login Page

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#301]
It seems that the app applies current themes background color to more pages like login and loading screens... Which seems good in theory, but does not work well at all with dark themes as you can see in this screenshot (using the "slate" theme here). 

![Login_Issue](https://user-images.githubusercontent.com/9065557/57033302-95d19280-6c1a-11e9-9990-c8452bdf4ce5.jpg)

Not only is it near impossible to read the login text at the top, but definitely impossible to read the user/password fields too - you can tell here by the cursor position that I've entered text, but you can't read it at all.

It's like this for loading screens too, it's impossible to read the text now. Here is 2.0b44 on the left and 1.5.1 on the right:

![Image](https://user-images.githubusercontent.com/9065557/57033578-4049b580-6c1b-11e9-8709-1c3c31350285.png)

Potentially other pages as well...

fyi this was introduced in b42 i think.

**Comment by robbiet480** [comment]
Not gonna fix this issue as it only happens when you are logging in via the web view which should never happen. It's only happening for you because you entered the `ui.nabu.casa` URL which will soon not be possible. Related: #302.
