### ISSUE TITLE
Settings icon covers Save Login button

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#302]
When connecting to an external URL for the first time it asks to login.
Once you login it shows the typical "Do you want to save this login?" prompt.

Problem is the new Settings icon covers at least half of this prompt. See screenshot below:

![IMG_9744](https://user-images.githubusercontent.com/9065557/57034143-cc101180-6c1c-11e9-979a-8db9897431f3.png)

**Comment by robbiet480** [comment]
Not gonna fix this issue as it only happens when you are logging in via the web view which should never happen. It's only happening for you because you entered the `ui.nabu.casa` URL which will soon not be possible. Related: #301.
