### ISSUE TITLE
[2.0b44] Mobile app notification - requested entity not found

### ISSUE THREAD

**Issue by imuncas** [home-assistant/home-assistant-iOS#306]
Hi,

I'm on HA version 0.92.1 and ios beta 44. I had some trouble with the notifications, to fix it, I deleted all the app, and all my mobile integrations.
After several restarts, and importing the configuration the relevant notify.mobile_app_myphone appeared, but when I call it nothing happens, and I see an error in the logs:
2019-05-01 16:31:58 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Requested entity was not found.

Cheers and keep up the good work!

**Comment by PierpaoloPernici** [comment]
Problem due to #293

**Comment by robbiet480** [comment]
Closing in favor of #293 and #300
