### ISSUE TITLE
Can only use volume 1 or 0 for critical notification

### ISSUE THREAD

**Issue by circuuz** [home-assistant/home-assistant-iOS#310]
As the title states I only receive a notification if I use volume set to 1, 1.0 or 0, nothing in between. And no event is logged using anything between 1.0 and 0 either.

The following works great:
```
{
    "message": "ALARM TEST!",
    "data":
    {
        "push":
        {
            "category": "alarm",
            "sound":
            {
                "critical": 1,
                "name": "default",
                "volume": 1.0
            }
        }
    }
}
```

The following does not work at all:
```
{
    "message": "ALARM TEST!",
    "data":
    {
        "push":
        {
            "category": "alarm",
            "sound":
            {
                "critical": 1,
                "name": "default",
                "volume": 0.5
            }
        }
    }
}
```

**Comment by robbiet480** [comment]
Not a issue on my side. Opened a new Firebase ticket, 4-4663000026372. Will report back when I hear something.

**Comment by robbiet480** [comment]
hell yeah

![image](https://user-images.githubusercontent.com/18516/57112612-a9056080-6cf5-11e9-97ba-42f7054adf1c.png)

**Comment by robbiet480** [comment]
Although pretty ominous to say "or if even" :'(

**Comment by riekelt** [comment]
Reported this earlier in https://community.home-assistant.io/t/home-assistant-for-ios-2-0-beta-testing/107511/542

I did get a report of it in my logfile:
`Apr 29 17:35:19 ha scl[31137]: 2019-04-29 17:35:19 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Value type for APS key [volume] is a number.`

Did see it working in one of the versions before with notify.ios, don't know if and how they are still related on the backend side.

**Comment by robbiet480** [comment]
The 1.X backend is entirely different (homegrown but AWS SNS at the core) from the 2.X backend (Firebase Cloud Messaging (FCM)).

**Comment by robbiet480** [comment]
Firebase reports this is fixed and I have confirmed. Closing issue.
