### ISSUE TITLE
Simple mode (surface common uses to top)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#314]
On Discord there was discussion about offering a more "simple mode" in addition to the current way Siri Shortcuts are handled. This would focus on the eight most commonly used domains and commands:

## Commonly Used
Category | Entities Shown | Available Commands
------------ | ------------- | -------------  
Lights | light.* | On / Off / Toggle
Switches | switch.* | On / Off / Toggle
Fans | fan.* | On / Off / Toggle
Input Booleans | input_boolean.* | On / Off / Toggle
Media Players | media_player.* | On / Off / Play / Pause / Stop / Mute
Automations | automation.* | Trigger
Scripts | script.* | Run
Scenes | scene.* | On

> Locks was suggested as a potential idea, no consensus yet. For security reasons might not want to make locks too simple to set up in case less experienced users mess it up?

**Suggested Flow**
When navigating to Siri Shortcuts section, these eight categories would be listed at the very top of the screen. The flow would be like this:
1. Tap on category Lights, which brings you to a screen with alphabetical list of all your entities beginning with `light.*` prefix.
2. After tapping on the light entity you want (`light.floor_lamp` for example) you are taken to the second (and final) screen. This screen would have three options - On / Off / Toggle. Selecting one of the options would display a checkmark to the right of it. 
3. Once it's selected, the standard "Add to Siri" button appears underneath where user can record a voice phrase. 

Here is a quick mockup of how the final screen could potentially look, very simple. 

![image](https://i.imgur.com/YuGmrBR.jpg)

So everything on the above list is able to be set up in just **4 taps**: Tap Category -> Select Entity -> Select Command -> tap Add to Siri. Potentially even the Siri record phrase could be automatically started when user selects a Command which would take it down to **3 taps**.

## Advanced / All Services
The current screen that lists literally all services would still be accessible but under an "Advanced" or "All Services" option. 

The other Generic Shortcut options (Fire Event, Get Camera Image, Render Template) could also maybe be relocated to this Advanced section.

## Benefits
* A much easier setup process for the vast majority of people. If you navigate to the current `light.turn_on` screen it has fields for `white_value`, `rgb_color`, `hs_color`, `kelvin`, `xy_color`, and like a dozen other things - this is very overwhelming when 99% of the time you just wanna turn a light on or off.
* Proposed solution still allows more advanced users to create shortcuts for literally every possible service call, so it is the best of both worlds.
* Once implemented, it should require little to no maintenance going forward because on/off/toggle are core service calls that should never ever change.

**Comment by olbjan** [comment]
Automation would be trigger
