### ISSUE TITLE
App crashes when trying to edit notification category

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/home-assistant-iOS#315]
Summary: If you try to edit a notification category created within the app after importing others from YAML the app crashes. 

Steps to reproduce:
1.  Create a basic notification category.
2.  Save and return to notifications page. 
3.  Press “Import push configuration from server”
4.  Return to category created in Step 1 or any other notification category.
Attempt to edit any field. As soon as a key is pressed , app crashes. 

May require some categories to be present in the YAML. Haven’t tried without.

**Comment by robbiet480** [comment]
Fixed this at f18786384d5be86c0916d18c9e7a54f7f834fa25 which is in the build I cut late last night along with a bunch of other tiny issues like this.
