### ISSUE TITLE
Use Network SSID in the app as a secondary Zone check

### ISSUE THREAD

**Issue by bagobones** [home-assistant/home-assistant-iOS#32]
When a phone is indoors the location radius gets huge, also the background location update service can be very intermittent.

It would be nice for the app to use a network SSID as a secondary lookup for the app to determine what zone it is in.

This could also help prevent flapping in and out of zones at larger campus type locations without having to set a huge radius.

Current SSID should be exposed in the iOS public network APIs.

As for implementation I would suggest that the SSID be added as an attribute to a zone, similar to how beacons work.

Added bonus this would allow NON GPS enabled iOS devices to do zoning. Such as iPods and iPads

**Comment by cgarwood** [comment]
It would be beneficial for the iOS app to send a location update when it connects to a known network SSID, like knowing the SSID of my home network would update me to be in the home zone.

**Comment by bhaap** [comment]
This would be very awesome indeed!

**Comment by blackgold9** [comment]
In my mind this could only signal arrival (inaccurately), as iOS devices tend to disconnect/reconnect from wifi frequently.

**Comment by bagobones** [comment]
That is no different than using the NMAP, or WiFI AP based sensors. It is something you just need to account for in automation.. However that connection event is still useful.

**Comment by robbiet480** [comment]
I've added SSID and connection type to the `device_tracker.see` call in 868dc7d0169b755293e7db70715ecf9279ce5221 and 860afb3070f8979c7660580ab8fb389dfed4df7b.

**Comment by robbiet480** [comment]
@bagobones @cgarwood Mind checking in with me on [Discord](https://discord.gg/GMCtHy) to chat about this ASAP. Not opposed to implementing exactly as suggested but would like some feedback first.

**Comment by robbiet480** [comment]
Implemented two new properties you can set on the `zone` in 6cc3ced11ea72f3571f535066746a4fbdbf54783:

- `ssid_trigger` - an array of SSID strings. If a location update happens and your device is connected to one of the provided SSIDs we forcefully set the zone name in Home Assistant.
- `ssid_filter` - an array of SSID strings. When a region event happens, if your device is connected to one of the provided SSIDs we ignore the region event. This will help to cut down on false positive exits.

They'll be in the 2.0 beta shortly.
