### ISSUE TITLE
no device tracker/no movement entities created

### ISSUE THREAD

**Issue by folrewef** [home-assistant/home-assistant-iOS#322]
When release 49 came I got double sets of the integration (two iPads and two iPhones when I only have one of each). I therefore reset everything:
1. deleted mobile app file in .storage
2. deleted device trackers
3. deleted app from iPhone and iPad
4. deltid integrations from integration page

Then I
1. restarted HA
2. downloaded app to iPhone and iPad and logged in (home assistant on my network was not identified as before so I had to enter url manually)

The integrations have returned but I see o device trackers and no movement entities,
The entities added for each device are:
1. BSSID
2. Battery level
3. Battery state
4. Connection type
5. SSID
6. Sim 1 (carrier) - here the status is "carrier" for my iPad but the correct carrier for my iPhone
7. Last update trigger
8. Geocoded location - here the status is unknown

I have moved to release 51 with no change.

**Comment by jimz011** [comment]
You probably get the HA API not configured error. Robbie is already aware of this I believe, though I think he said that it should have been fixed in build 51. Unfortunately the problem still persists.

**Comment by folrewef** [comment]
Ok - no error message. It all worked for me before (build 46).

**Comment by folrewef** [comment]
Works now in build 54

**Comment by SeanPM5** [comment]
Thanks for confirming it's been fixed!

**Comment by mitsumaui** [comment]
Just wanted to know if this has regressed at all? I'm really struggling to get a device_tracker entity for the IOS 2.0 beta, yet my other devices on 1.5x are fine. 

I also have some entities I am unable to remove from the Device Entities page. Using 0.93.2 HASS.io and build 60 of the iOS app.

Only error on the iOS Logs is: 
`Region monitoring failed for region: zone.home. Error: The operation couldn't be completed. (kCLErrorDomain error 4.)`

**Comment by robbiet480** [comment]
[`kCLErrorDomain error 4` means region monitoring has been denied by the user](https://developer.apple.com/documentation/corelocation/clerror/code/regionmonitoringdenied) (you). Can you double check the location permission is properly enabled? You can confirm by looking at the iOS settings app under the Home Assistant Beta entry.
