### ISSUE TITLE
Adding a second SSID doesn’t save

### ISSUE THREAD

**Issue by benjgos** [home-assistant/home-assistant-iOS#323]
Build 51 - Config - Connections - Add New SSID.
Newly entered SSID isn’t saved.

**Comment by jamieshaw** [comment]
Confirmed; cannot add a second URL for external usage.

**Comment by sgruby** [comment]
On the same screen, entering an External URL doesn't save either.

**Comment by banana-ben** [comment]
Both are also an issue on b52 :/

**Comment by benjgos** [comment]
Confirmed b53 resolves it. Thanks Robbie! :)
