### ISSUE TITLE
[2.0b51] Can't log in any more

### ISSUE THREAD

**Issue by gieljnssns** [home-assistant/home-assistant-iOS#325]
Since 2.0b51 I can't log in any more. I'm on Hassio (generic linux install) 92.2
I've reinstalled the app
I've tried on wifi, cellular, internal ip, duckdns...
Restarted HA dozens of time
![IMG_2711](https://user-images.githubusercontent.com/17234951/57195324-78b9fe00-6f51-11e9-9a88-d2b1b676e6b2.jpg)
![IMG_2712](https://user-images.githubusercontent.com/17234951/57195328-7ce61b80-6f51-11e9-8a99-1030a364d169.jpg)
![IMG_2713](https://user-images.githubusercontent.com/17234951/57195329-7e174880-6f51-11e9-91bc-1a2bc3339e35.PNG)

Also going back to previous versions of 2.0beta don't work anymore

**Comment by gieljnssns** [comment]
I've restarted my router -> OK

**Comment by robbiet480** [comment]
For anyone that finds this in the future, check your home-assistant.log for any errors about `indieauth`. If it also mentions a OS Error, you most likely have a broken IPv6 implementation. You can confirm this by running `curl -v6 https://home-assistant.io/iOS/beta-auth` from the machine you run Home Assistant on. If you receive a error about not being able to connect to the server, your IPv6 stack is broken and you should disable it.

**Comment by knutasund** [comment]
I have the same issue on my installation, running hassio in virtualbox on Win10 host. 
Disabled ipv6 on the host, using bridge virtualbox network - still same. 
Any way of running curl when using hassio?

**Comment by onkytonk** [comment]
> I have the same issue on my installation, running hassio in virtualbox on Win10 host.
> Disabled ipv6 on the host, using bridge virtualbox network - still same.
> Any way of running curl when using hassio?

I'm having the same issue with hassio in virtualbox on win10. 

Did you ever find a solution? Thanks.
