### ISSUE TITLE
Reloading view not working as expected

### ISSUE THREAD

**Issue by XusBadia** [home-assistant/home-assistant-iOS#327]
Since the new pull to refresh action was implemented, I found that when I reload the webpage it won't actually reload (I think what it does is "Refresh" lovelace).
I added custom icons and the only way to have lovelace display them is by Reloading the webview (Refreshing lovelace or Restarting Home Assistant won't work).

I tried it with the original app (the one on the App Store) and it works fine.

**Comment by robbiet480** [comment]
Fixed in 67edbd6772109cd3f4bc2bf436a3d512fa931cdb
