### ISSUE TITLE
Keep attempting to reconnect gracefully 

### ISSUE THREAD

**Issue by jhorwit2** [home-assistant/home-assistant-iOS#33]
Currently, the app will throw an error when it has issues connecting to the home-assistant server. Every single time I simply have to press save and not change anything to fix it. The app should do some type of backoff/retry algorithm.

**Comment by cmsimike** [comment]
Related to #31 I think?

**Comment by jhorwit2** [comment]
It appears very very similar. He didn't mention the error message anywhere, but I think it's implied with how some people were talking. 

Gonna close this and track that ticket.
