### ISSUE TITLE
SSL error has occured

### ISSUE THREAD

**Issue by tinglis1** [home-assistant/home-assistant-iOS#332]
On the latest beta when going through the onboarding process i cannot get past the final connection screen with the checklist.
I get the error "An SSL error has occurred and a secure connection to the server cannot be made"

My details:
- Beta app 52.
- hass.io using Duck DNS addon. Never had any issues with SSL on any other connection to date. Checked and the certificate is current and i can access via safari with no issue.
- iphone XR
- previous beta app (49) was working ans still works if i roll back.
- all of the check list are checked green except the last one for sensors.
- i have cloud remote connection but am using duck dns.

I have tried so far:
- Removed the V1 app from my phone.
- removed and reinstalled the latest beta.
- removed all integration for ios and mobile app in HA.
- if i roll back to build 49. login and then upgrade to 52. I can get to my HA setup but get the same warning in red at the top. Otherwise it seems to work though.
- when logged in the connection shows as remote and using Home Assistant Cloud.

**Comment by robbiet480** [comment]
If you turn on the remote UI does it work?

**Comment by tinglis1** [comment]
That works.

Will streams work though the remote ui in the app?
I have them disabled at the moment so cannot try them

**Comment by robbiet480** [comment]
They will.

**Comment by tinglis1** [comment]
Awesome. Then my case is closed.
Not sure if you want to have some more info as to why the error came up or to allow those who do not use remote ui.
I realise this might have just been because i had the cloud subscription (to support the project) but hadn't used the remote ui to date.

I'll raise anything else i find as a separate issue.

**Comment by robbiet480** [comment]
Planning to add more descriptive errors with links to [our new docs site](https://companion.home-assistant.io/en/next/getting_started/) as well as not failing setup if we have a URL other than remote UI when remote UI is turned off. Thanks for the report & beta testing.
