### ISSUE TITLE
Forced to Quit App (URL Unavailable)

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-iOS#334]
I'm currently unable to open the app since updating to build 52.

When I open it, I get Home Assistant splash/loading screen briefly (less than 1 second), followed by a black screen with an error message that reads:

_URL Unavailable
Expected to have a External URL but none available! Check settings and try again
Quit App_

The error appears twice over itself. There's no where for me to access the settings, I'm forced to close the app. Force closing the app doesn't change much (the only difference is the next open of the app crashes instantly).

This all happens while accessing externally, I haven't tried it locally yet.

**Comment by slippern** [comment]
I have added external URL, but it is not stored when im exiting the configration menu.

**Comment by acateon** [comment]
Got the same problem as initial poster. Downgrading / reinstalling does not fix the issue.

**Comment by hagenuck1** [comment]
Same issue for me when accessing Home Assistant by VPN using internal device name. I didn’t configure any „external url“.

**Comment by wixoff** [comment]
Same problem here, and I'm on build 53.  I had the URL configured in previous betas.

**Comment by fedebruni84** [comment]
Same problem also for me (Build 53)

**Comment by hagak** [comment]
Same issue here

**Comment by mynameisdaniel32** [comment]
Looks like it's resolved in build 54 - but unsure if this is just because I've since been home to set things up. Will close this if someone else can confirm it's working for them too :)

**Comment by mcchots** [comment]
I get it in build 54 as well.

**Comment by hagak** [comment]
I still get this in 54.  I upgraded at home, made sure to set my external URL (note my URL is the same internal as external) yet I get this error if I am not on my home network.

My setup has the domain for my HA server resolve to a local ip if on the local network or an external ip if not.

**Comment by ecam315** [comment]
I am getting the same error on build 54 with 0.92.2

**Comment by jasoncodes** [comment]
Same problem here with build 54 when I’m on my home network with HASS 0.90.2. I originally did not have `http`.`base_url` defined in my config but the problem persisted after adding it. This morning on the office WiFi I the Manual Configuration page shows and seems to be working. (I need to upgrade HASS in order for sensor creation to work.)

**Comment by robbiet480** [comment]
Minor improvement in next build: if you get this popup you are given the opportunity to enter the address. Final fix will be adding this step to onboarding and properly redirecting users to the connection settings screen if the URL fails.

**Comment by maibruno** [comment]
same here:
1)-  since I installed duckdns addon, the internal logon changed from http://hassio.loca:8123l to https://hassion.local:8123. And unfortunatelly the IOS App doesn't allow to change this address.
2) Accessing trough external network option it just freezes (https://xxxxxx.duckdns.org/8123.; 
PS: if I put a wrong password it complains; but with correct password never starts.

**Comment by RezzZ** [comment]
error also appears when you're not connected to wifi but only use it on your local network. The app keeps asking about an external URL but there is no way to cancel the input and get back to the already properly loaded dashboard. I have to force close the app to be able to control anything again.

**Comment by jarrah31** [comment]
Same issue build 62. Entered an IP address, app crashed, but now loads ok. I think it's related to setting up actions for the Apple Watch.

**Comment by mynameisdaniel32** [comment]
This hasn't been an issue for quite a while so closing this off - thanks Robbie!

**Comment by massive** [comment]
I started having this problem today after I tried Nabu Casa URL (which I’m subscribed to). After failed attempts to enter acceptable URL (internal or external) I tried reinstalling the app. Now I’m greeted with the flashing and disappearing prompt described in the initial bug report.

I’m using the latest app in AppStore and HA (hass.io) 105.4
