### ISSUE TITLE
Onboarding fails: require version 0.92.2 when running 0.92.2

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/home-assistant-iOS#335]
With build 53 and current HA release, if you install from a scorched earth state, onboarding fails stating:

> Your Home Assistant version (0.92.2) is too old, you must upgrade to at least version 0.92.2 to use the app.

All sensors and integrations seem to be created on HA but app refuses to progress. Force quitting and reopening restarts onboarding.

![IMG_0220](https://user-images.githubusercontent.com/12411302/57216031-8f5e6480-6fe6-11e9-87eb-fb97b03fcacc.JPG)

**Comment by olbjan** [comment]
I have this same error on an HA instance that does not have a cloud account. So just direct connection via manual address entry.

**Comment by TomBrien** [comment]
I believe error comes from: https://github.com/home-assistant/home-assistant-iOS/blob/93d775180a6221cfa1465c20172612237aae9d3a/Shared/API/HAAPI.swift#L693

Should be:

```swift 
        if HomeAssistantAPI.minimumRequiredVersion > currentVersion {
            return APIError.mustUpgradeHomeAssistant(currentVersion)
        }
```

**Comment by olbjan** [comment]
Created PR #336 to change to your proposed version check logic :)

**Comment by TomBrien** [comment]
Minor addendum: `device_tracker` entity isn't created. Doesn't really matter as app is sadly unusable at build 53 in this way.

**Comment by olbjan** [comment]
The device_tracker entity only get's created on the first push of location data. So it would not be created as long as you can't fully start the app.

**Comment by earth08** [comment]
am unable to go beyond 
sensors configured
does anyone has clue behind it?

**Comment by TomBrien** [comment]
Yep I believe it’s a small error in the definition used in checking installed version. Proposed fix is above.

**Comment by SeanPM5** [comment]
Fixed via https://github.com/home-assistant/home-assistant-iOS/pull/336  / build 54.
