### ISSUE TITLE
Fire event when opening app from background

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/home-assistant-iOS#337]
## Overview

When the app is opened and it is not already open in the background, numerous events are fired as sensors are updated with an `initial` update trigger which can be picked up using `state_changed`. However, if the app was already open in the background no events are necessarily fired. It would be useful if a simple event, such as `mobile_app.app_opened` was fired in both case (clean open and open from background).

## Use case

Some users have expressed an interest in _dynamic_ app badges. The current _static_ badges makes perfect sense to me as it is fundamentally more powerful. It is possible to use an `input_numer` to track the number of notifications sent and set the badge appropriately. However, there needs to be a reliable method of resetting this counter when the app has been opened. A simple event like the one described above should allow for this via a trivial automation.

**Comment by olbjan** [comment]
I think the only reliable way to reset the notification badge would be to create a persistent notification at the same time and count the number of those. The badge number would then have to be reset via a kind of silent notification every time a persistent notification is dismissed.

**Comment by TomBrien** [comment]
Pretty sure I can do it all with the above. I’ll build some MWEs this evening. May even catch their persistent and send those over too.

**Comment by robbiet480** [comment]
New events in next build:

- `ios.finished_launching` - called in [`application(_:didFinishLaunchingWithOptions:)`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application)
- `ios.entered_background` - called in [`applicationDidEnterBackground(_:)`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622997-applicationdidenterbackground)
- `ios.became_active` - called in [`applicationDidEnterBackground(_:)`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622956-applicationdidbecomeactive)

**Comment by TomBrien** [comment]
Those three seem working for me in b55. Will test a little more then document.

**Comment by TomBrien** [comment]
Looks to be working for me. Closing
