### ISSUE TITLE
iOS known_device state should default track: true

### ISSUE THREAD

**Issue by bagobones** [home-assistant/home-assistant-iOS#34]
Considering users must actually activate the feature on the device end I was surprised to find that when devices where eventually added to the known_device file they where defaulted to track: false.

**Comment by robbiet480** [comment]
This can't be controlled by us sadly, but is a configuration option in Home Assistant itself. See `track_new_devices` [here](https://home-assistant.io/components/device_tracker/). By default it's set to `True`.
