### ISSUE TITLE
Can't run "Render template" Siri Shortcut 

### ISSUE THREAD

**Issue by gust1n** [home-assistant/home-assistant-iOS#341]
(I'm sorry if this has already been documented elsewhere)

I simply cannot run the Siri Shortcut "Render text found on clipboard". Creating a simple Shortcut flow with:
1. A text node containing a template
2. Copy to clipboard
3. Render text found on clipboard

simply renders an iOS error, saying "Could not run Render text found on clipboard, an unknown error occurred" (freely translated from Swedish).

Nothing shows up in the iOS app logs, and nothing in the Home Assistant logs (I don't think the request ever leaves the device).

Please let me know how I can assist in further debugging!

**Comment by robbiet480** [comment]
@gust1n Mind providing the template you are using?

**Comment by gust1n** [comment]
Yes sure, I've tried anything I can think of, some examples:
- ```Joakim is at {{ states("device_tracker.joakim") }} ```
- ``` {{ states("device_tracker.joakim") }}```
- ``` states("device_tracker.joakim")```
- ``` Hello```

**Comment by robbiet480** [comment]
Ugh. Stupid minor oversight on my part. Fixed in next build which will be out within the next 8 hours.

**Comment by carterthayer** [comment]
I'm having the same issue. I get "Could Not Run text found on clipboard" "Failed to render template with error: Template not previously set and no template found on pasteboard". [Screenshot of error](https://user-images.githubusercontent.com/381401/69354676-1a7f0f00-0c46-11ea-9bea-448df8845440.PNG).

Although I am not sure I am setting this up correctly. I have it set up from what I understand @gust1n had it set up. 
[Screenshot in shortcuts app](https://user-images.githubusercontent.com/381401/69354783-4d290780-0c46-11ea-9088-d62b59cc8985.PNG). If I am setting this up wrong any guidance would be appreciated.

- iOS 13.2.3
- Home Assistant Companion 2.0.0 (68)
- Home Assistant 0.100.2

**Comment by robbiet480** [comment]
Try build 69 which refactored Siri Shortcuts entirely to use new-in-iOS 13 Shortcut Parameters instead of the pasteboard.
