### ISSUE TITLE
Actions disappear when dragged to top

### ISSUE THREAD

**Issue by sweebee** [home-assistant/home-assistant-iOS#346]
When dragging an action to the top, it disappears. Also when you delete an action, it remains on the apple watch app.

see video for disappearing action: https://cdn.discordapp.com/attachments/551871772484698112/575346392898207745/RPReplay_Final1557243606.MP4

**Comment by robbiet480** [comment]
@sweebee Good catch, fixed in next build. However, newly added rows can be reordered but their new position will not stick. Waiting on a response to https://github.com/xmartlabs/Eureka/issues/1830 for the fix.

**Comment by robbiet480** [comment]
Fixed in build 55
