### ISSUE TITLE
Zones do not appear to auto refresh / iOS map does not seem to refresh on its own

### ISSUE THREAD

**Issue by bagobones** [home-assistant/home-assistant-iOS#35]
Zones do not appear to refresh on the iOS app unless the credential save button is clicked or maybe sometime after a forced location update.

I have been updating my zones to test out the iOS app, however I noticed no new zone appearing even after end tasking the app and re-launching it.

It seems like the zone only update after a credential save for sure, not on app launch, also there does not seem to be a location update on app launch as I have forced one a few times to reset my location.

**Comment by sstratoti** [comment]
I can confirm this bug. Was experiencing the same thing and mentioned it in a review. I thought it was related to upgrading to .48 or something, but this workaround did the trick for me. Thanks.

**Comment by robbiet480** [comment]
This should now be fixed. Zones are updated every time the app opens. Currently we have no reason to update more frequently then that.
