### ISSUE TITLE
Critical notifications should temporarily bypass rate limits

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#354]
There's a rate limit of 150 notifications per day, but critical notifications should be allowed to bypass this limit, at least once or twice. 

This way even if user is rate limited, could still get alerted about their house being on fire or some other crucial alert.

**Comment by robbiet480** [comment]
Implemented. Only bypasses rate limits if volume is > 0 to staunch abuse. Also made the commands (``request_location_update` and `clear_badge`) not count against rate limits.
