### ISSUE TITLE
Custom sounds imported from iTunes do work, but do not show up in app configuration

### ISSUE THREAD

**Issue by ik0adr** [home-assistant/home-assistant-iOS#355]

**Comment by ik0adr** [comment]
Custom sounds imported from iTunes work perfectly, but are not listed in the imported sounds section of the app configuration. Integrated and system sounds do show up.

**Comment by ik0adr** [comment]
The problem is only with iTunes sounds: files directly imported are listed.

**Comment by robbiet480** [comment]
I just tested this and the sound does appear properly after tapping "Import sounds from iTunes File Sharing". Closing as fixed.
