### ISSUE TITLE
Apple watch complication not updating on watch

### ISSUE THREAD

**Issue by Henk72** [home-assistant/home-assistant-iOS#357]
Complications do not update on the AW. On the Simple watch face the complication seem to always revert to the Ring type, also if a template is chosen like Simple Image or Simple Text. 

Also the X-Large clock face does not update and probably more watch faces.

Build 56. Apple Watch 3 latest OS an iPhone 7 latest OS.

**Comment by TomBrien** [comment]
It seems a few people are experiencing this. I would like to propose those affect carry out the following tests:

Create a special watch face for HA testing. I think modular is available on most AWs. Create a "Large" complication with `{{ states("sensor.time") }}` on one line and `{{ states("sensor.date") }}` on another. This will create a complication that will show the time and date the watch last received data from HA.

Now the tricky part, getting it to update in the first place, you should be able to force an update of the sensor data by following these steps:
1.  In the Home Assistant Companion app, navigate to App Configuration -> Apple Watch and stay on that screen.
2.  Now launch the "Home Assistant" Apple Watch app.
3.  Press the Back button inside Home Assistant Companion mobile app, bringing you back to the main settings screen.
4.  Press "Done" in the top right to sync and update the complications on your Apple Watch.

You hay have to swipe to a different face and back to the one you just created but this should update the complication. Now keep an eye on that at let us know roughly how long it was between updates and if you think a particular action caused it to update.

Please also post your watch model as given in Watch App (on phone)>General>About. Tap the "Model" row and the value should change to a value beginning with an A. Please also post the current beta build you are running, the iOS version (iPhone Settings App>About>Software Version) and phone model number (same place as iOS version, again tap to get a number starting with an A).

I'll get things started:

**Time between updates:** 12 hours + no update
**AW model:** A1978
**HA app build:** 56
**iOS:** 12.2
**iPhone model:** A2097

Template for reporting is:

```markdown
**Time between updates:** Time here
**AW model:** AW model number here
**HA app build:** build here
**iOS:** iOS version here
**iPhone model:** iPhone model here
```
```

**Comment by Henk72** [comment]
**Time between updates:** Immediate/couple of second to update when swiping to/from the new Modular/Large watch face created. After making a change to the complication it updates fast, but the variables to be interpreted are printed as text. So you see {{ states("sensor.time") }} on the AW. After tapping the complication and going back to the watch face, the actual data is shown correctly. A third time I had to click the complication to get an update and then I had to wait 6 seconds with a spinning application wheel (like the app is restarting). The fourth time I changed something to the complication, it automatically updated the watch while looking at the AW. The fifth time I had to click the complication and go back from the action level to the AW face. Then it updated instantly (so no app reloading this time). See also related issues at the bottom.
**AW model:** A1859
**HA app build:** 57
**iOS:** 12.2
**iPhone model:** A1778

Related issues:
- Only the Modular watch face seems to work. Other watch faces like Simple always reverts to an empty ring. Same for Activity Analog and Utility. X-large shows nothing.
- The modular watch face only updates the color of the first line, the other 2 lines are default gray and can be changed in the app, but it is not shown on the AW.

**Comment by TomBrien** [comment]
Interestingly I just did a manual forced update and the time it shows is about 6 minutes ago.

**Comment by Henk72** [comment]
Sorry I confused you. The next sensor did not work for me: {{ states("sensor.time") }} so I used a different, being sensor.battery_level. When I talked about time, I meant the time I was waiting to see an update on the watch.

**Comment by TomBrien** [comment]
It's ok I understand I think. The point I was making is that the complication seemed to update but with old data.

**Comment by KentEkl** [comment]
Followed TomBriens instructions to assist.
Reinstalled the watch application first.
Now i’m getting this result?

![Watch](https://user-images.githubusercontent.com/39707712/57567737-0d9f7a00-73de-11e9-807d-0f2cabb7ed0f.png)

**Time between updates:** n/a
**AW model:** A1977
**HA app build:** 58
**iOS:** 12.3 Beta 6
**iPhone model:** A2097

**Comment by TomBrien** [comment]
@KentEkl have you tried swiping to a different face and back a few times. Are you sure you created the correct complication?

**Comment by KentEkl** [comment]
@TomBrien I believe so and I have swiped many times.
The picture is in Swedish and Stor is Large in Swedish, and the preview button shows time and date. 

![Watch 2](https://user-images.githubusercontent.com/39707712/57572858-ae168e00-7420-11e9-8218-fbd23f07a882.PNG)

**Comment by KentEkl** [comment]
Noticed that the complication has a different name than the installed watch app, it has a beta in the name.

**Comment by Henk72** [comment]
The latest build only works for the Modular watch face. Colors on the complication are not according to what is set in the app. 

After changing the color in the app, the Modular complication shows again the code like {{ states("sensor.time") }}, instead of showing the actual value of the sensor.time. Swiping does not update it, neither clicking the complication and going back up.

AW model: A1859
HA app build: 58
iOS: 12.2
iPhone model: A1778

**Comment by TomBrien** [comment]
So just by way of an update, on build 58 may watch complication displayed the sensor value (on Infograph Modular) for a day or so but did not update in that time. It then reverted Jinja2 template.

**Comment by KentEkl** [comment]
@TomBrien any news to share ? About the progress.

**Comment by TomBrien** [comment]
So my complications are now stuck with the template string and have been for several days. I think we're waiting for a new build.

**Comment by Henk72** [comment]
I noticed that selecting an action via a complication is often not firing the action in HA immediately. Only at the moment the HA app is also opened, will the action be executed. So the delay between pressing the action on the AW, until the HA server is actually executing the action is the time between pressing the action and opening the companion app.

AW model: A1859
HA app build: 58
iOS: 12.2
iPhone model: A1778

**Comment by ik0adr** [comment]
It worked almost immediately.

AW model: MU6C2TY/A
HA app build: 58
iOS: 12.3.1
iPhone model: MQAF2QL/A

**Comment by KentEkl** [comment]
After many trial and errors it seems to work for me, I did a lot of mistakes with different faces and configuration of them.
I can now see my sensors updates every 30 min.

Time between updates: 30 min.
AW model: A1977
HA app build: 58
iOS: 12.3 Beta 6
iPhone model: A2097

**Comment by KentEkl** [comment]
It went fine for a couple of hours, now I have to manually trigg the updates with TomBrien’s method.

**Comment by KentEkl** [comment]
The problem persists for me in build 59

**Comment by TomBrien** [comment]
Just confirming that I see no improvement in b59 but I do not believe any way expected.

**Comment by Martinvdm** [comment]
I do get the sensor data on the modulair watch face but it will not Refresh its data. So the first data is ok, but No new data

AW model: A1803
HA app build: 60
iOS: 12.3.1
iPhone model: A1688

**Comment by SeanPM5** [comment]
A development decision was made to delay Watch and Shortcuts support from the 2.0 app and re-implement them in version 2.1 as iOS 13 specific features. 

Not only will this allow 2.0 to be released very soon, but the nice improvements coming with iOS 13 will make the Watch and Shortcuts integration better and easier to use - it'll be worth the wait!

I've been asked to close all existing Watch and Shortcuts-related issues since things will be changing a bit. Stay tuned in the coming weeks.

**Comment by mrmikee** [comment]
Someone PLEASE update the HA Apple Watch documents to reflect that iOS 13 is now required. I wasted three days trying to get my watch app to work on my iOS 12 iPhone 6.

**Comment by TomBrien** [comment]
This was an error in a few builds in that the watch required watchOS 6.2 (which in turn requires iOS 13). 2020.5 reduces this to WatchOS 5 which should work with iOS 12.

**Comment by colethegamer123** [comment]
I tried everything with Apple Watch to make it work, but my complications for example Sensor values, does not refresh anytime. Only way to do that to wait at least half an hour, go to the Apple Watch settings in Home Assistant IOS app, change something and change it back, go back to the Watch and open the HA app a few times. This is the only way to update a sensor value. Any Idea why is this happening with me and with a lot of people? Thank you :)
