### ISSUE TITLE
sensor.sim reports "carrier"

### ISSUE THREAD

**Issue by folrewef** [home-assistant/home-assistant-iOS#359]
I have an iPad and an iPhone. Both use the same operator. One sensor.sim has the name of the operator as state while the other has "carrier" as state.

**Comment by robbiet480** [comment]
@folrewef Is there any way for you to positively confirm which device is sending that as a sensor? Maybe try deleting the other sensor and integration and seeing what causes the update? I'm gonna guess its the iPad but who knows. I assume your iPad is cellular btw?

**Comment by folrewef** [comment]
@robbiet480 I can confirm it is the iPad. It is cellular. I do not know if it in any way matters that the cellular card cannot not be used for calls or sms - only for mobile data.

**Comment by robbiet480** [comment]
@folrewef Based on some clearly broken implementation details in the iOS API that I use to access the data, things that were broken to support eSIM, I would not at all be surprised to learn that Apple just broke the API entirely on iPad. Will test myself to find out.

**Comment by folrewef** [comment]
OK - I reported it more for you to know about it than that the sim entity is important. ;)

**Comment by TomBrien** [comment]
I believe this is addressed now so I’m going to mark as closed. Feel free to reopen if I’m wrong.
