### ISSUE TITLE
Feature Request:  Find my Device

### ISSUE THREAD

**Issue by JasonCarter80** [home-assistant/home-assistant-iOS#36]
Would it be possible to add a 'sound off' feature from Home Assistant to the device to assist in locating the device?

**Comment by robbiet480** [comment]
You can do this by sending a [push notification](https://home-assistant.io/docs/ecosystem/ios/notifications/basic/) with a [sound](https://home-assistant.io/docs/ecosystem/ios/notifications/sounds/), no?

Let me know if I misunderstood and I will re-open this issue.
