### ISSUE TITLE
YAML categories still supported, change ios to mobile_app?

### ISSUE THREAD

**Issue by Swiftnesses** [home-assistant/home-assistant-iOS#361]
Hi @robbiet480 

I have MANY notification categories setup using the old :ios YAML implementation...

Are these no longer supported? - I have many of them and it's not clear if creating them via the new option in-app 'syncs' to all other phones? Further, YAML was fast and offered a chance to duplicate entries easily to use as templates...

Many thanks in advance for any help!

**Comment by Swiftnesses** [comment]
Tested adding via the app and don't see them via other devices...

Further, how do you delete them inside the app once you've created one?

**Comment by robbiet480** [comment]
They’re absolutely still supported and no changes were made to that system between builds 56 and 57. There was a DB reset in build 56 though, so youll need to hit that sync button again.

**Comment by Swiftnesses** [comment]
Hi @robbiet480 I changed the title of this issue as I realised the reason they were not showing was because I commented out `:ios` like a fool at some point.

With regards going forward, will you move 

```
push:
  categories:
```

to the `mobile_app` config from `:ios`?

I'm confused by the categories created via the app as they don't seem to sync to other devices?

**Comment by robbiet480** [comment]
No. Push config will stay under `ios` for the foreseeable future as its syntax is very iOS specific.

Categories created in app don’t sync to other devices, correct. It’s just a easier way for many users to get up and running faster without having to write YAML.

**Comment by Swiftnesses** [comment]
@robbiet480 that's cool, the only issue I have right now is having mobile_app and ios active is some duplicate sensors (namely battery level and state), I assume this will be removed once the beta matures...

**Comment by robbiet480** [comment]
`ios` will continue to support 1.X versions. 2.X is supported via `mobile_app`.
