### ISSUE TITLE
Error sending

### ISSUE THREAD

**Issue by folrewef** [home-assistant/home-assistant-iOS#368]
I get error messages
- sending significant location change
- sending region entered
Request timed out
In the log I get:
Failed to send location after Region enter.
SSID: SSID: "my SSID"

**Comment by TomBrien** [comment]
I believe these were added in the last build for debugging purposes. It quite likely they've been going on in the background all along. How frequently are you getting them? Does, in general, location updating seem to be working.

**Comment by TomBrien** [comment]
Sorry didn't mean to close

**Comment by folrewef** [comment]
I get them one to a few times per day. It has been more frequent when it comes to significant location change. Of course there has to occur a significant location change. Saturday I got 3-4. Yesterday I only got one.

**Comment by folrewef** [comment]
I have not been able to identify that the device_tracker gives wrong status.

**Comment by folrewef** [comment]
I see I also get an error on the HA side:
Error processing web hook
I have identified that the webhook is connected to the same iPhone that reports the sending errors.
I also have an iPad but do not get the same webhook error. The iPad rarely leaves my home so there is no significant location change.
I assume the errors can be related.

**Comment by robbiet480** [comment]
Can you share the specific error that you see in HA?

**Comment by folrewef** [comment]
2019-05-11 18:32:54 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook _redacted_
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/webhook/__init__.py", line 83, in async_handle_webhook
    response = await webhook['handler'](hass, webhook_id, request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/mobile_app/webhook.py", line 273, in handle_webhook
    await hass.data[DOMAIN][DATA_STORE].async_save(safe)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/storage.py", line 119, in async_save
    await self._async_handle_write_data()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/storage.py", line 183, in _async_handle_write_data
    self._write_data, self.path, data)
concurrent.futures._base.CancelledError

**Comment by robbiet480** [comment]
@SeanPM5 reported this the other day in Discord and I thought maybe it was a early SD card failure but maybe I was wrong. Are you consistently getting this error?

**Comment by folrewef** [comment]
I restarted this morning. Since that I have six occurrences - four for my iPad and two for my iPhone.

**Comment by riemers** [comment]
I'am getting the "Error sending significant location change lo..." Response could not be serialized, input data was nil or zero length. Logs say "SSID: SSID: Unavailable" i get this consistently when i enter/join my zone around my house for example. I thought maybe log out log back in again. But the "logout" in connections does nothing. So i did a full reset in the settings (if i go click on done it still thinks i'am logged in but errors with the same serialize error) tried to type internal or external url but can't build api url. Remove the complete app and reinstalled it. Seems to be ok after that. Will have to check on location updates again.  Ticket sounded most like mine hence i added it here.

**Comment by folrewef** [comment]
OK - if you get the same error it would be better to find out the root cause if possible. Reinstalling everything is a mess. I have already done that a few times.

**Comment by riemers** [comment]
After a reinstall i don't get the messages anymore. I had nabu casa, it expired then it failed on me and i signed up again. Reloaded and it worked (so it seems) but then i got those errors too. Reinstall fixed it for me. Just stating the only possible root cause i can think of.

**Comment by folrewef** [comment]
OK - I will try it...thanks!

**Comment by folrewef** [comment]
Reinstalled. Came home after being away with my iPad. Again error sending significant location change.

**Comment by TomBrien** [comment]
I'm going to close this as stale. If anyone here still has these issues, please let us know. Cheers
