### ISSUE TITLE
loading app does not always load interface

### ISSUE THREAD

**Issue by bbrendon** [home-assistant/home-assistant-iOS#37]
https://community.home-assistant.io/t/app-stuck-loading/17925

I've experienced this many times. I use the Safari interface now unless I need something in the app specific version to work around this.

To work around it you can kill the app by swiping up in the app-switcher and then load it again. This resolves the issue until using it again sometime in the future.

**Comment by markgoodyear** [comment]
I've seen similar to this, although using the refresh button in the app does the trick for me.

**Comment by boojew** [comment]
Refresh button doesnt work to resolve this issue for me; however I have noticed in the last 1-2 weeks that this issue has not re-occurered, so I am wondering is HASS 0.45.1 resolved this

**Comment by mnoorenberghe** [comment]
Is anyone still seeing this recently?

**Comment by bbrendon** [comment]
I can't say. I uninstalled the app a long time ago now.

**Comment by arsaboo** [comment]
I have not seen this and have been using the app on a regular basis on two phones.

**Comment by mnoorenberghe** [comment]
ok, since I haven't seen it either and I use the app regularly, I'll close it.
