### ISSUE TITLE
Text too far up, behind iphone notch

### ISSUE THREAD

**Issue by riemers** [home-assistant/home-assistant-iOS#372]
![image](https://user-images.githubusercontent.com/682041/57778260-f46f3400-7723-11e9-957d-ea2910a0a15c.png)

You can see it in the screenshot but normally the notch is in front of it ;)

**Comment by robbiet480** [comment]
What model iPhone?

**Comment by riemers** [comment]
Iphone Xs

Op wo 15 mei 2019 om 21:28 schreef Robbie Trencheny <
notifications@github.com>:

**Comment by riemers** [comment]
I can also mention that the theming doesn't work for the notch bar. I presume it would have the same color but it does not. See example:

![image](https://user-images.githubusercontent.com/682041/57958048-c134cc80-78fe-11e9-971a-e2e715c1b07e.png)

Did see 2 closed issues about theming. Theming does work just not for the top end.

**Comment by TomBrien** [comment]
You need to call the service frontend.set_theme to change the colour of the status (top bar) as that's the only way that generates an event the the app can listen for. I believe the error with text in notch is fixed now too so closing this. If I'm wrong just reply and we can re open

**Comment by riemers** [comment]
I presume so too indeed :)
