### ISSUE TITLE
Latest beta not working with cloudflare

### ISSUE THREAD

**Issue by jonare77** [home-assistant/home-assistant-iOS#375]
When using the app to access HA behind cloudflare I get a SSL error. Working with web browsers from the same IOS unit.

**Comment by robbiet480** [comment]
Mind hitting export log files and sending them to me via iMessage: me@robbiet.us. Just mention this issue in that message as well so I know what the logs relate to.

**Comment by jonare77** [comment]
Will do sir! Thanx

**Comment by robbiet480** [comment]
@jonare77 If you're around right now and want to spend a few minutes on this you can jump into [Discord with me](https://discord.gg/X3Ykcj) and I can (hopefully) workaround this with you in real time. Still need those logs though.

**Comment by robbiet480** [comment]
@jonare77 I saw your message on FBM but can't accept the zip on there, can you actually iMessage it to me@robbiet.us? Thanks

**Comment by jonare77** [comment]
I had actullay turned off the remote ui konfig in HA. Thanks for your help.
