### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by labrunning** [home-assistant/home-assistant-iOS#376]
Hassbian on Raspberry Pi 3B+
Latest Hassbian-Config: (0.13.1)
Home-Assistant: 0.93
iOS App Beta: 2.0.0 (58)

The onboarding process works and finds my local installation, but whether I use a Nabu Casa URL or my external custom domain I get an SSL error after logging in with my username and password. All browsers work with my current install as does the 1.5.1 iOS Companion app. I'm using LetsEncrypt for SSL, currently there are 47 days until the certificate expiry.

**Comment by robbiet480** [comment]
This got fixed by @labrunning using automatic discovery and not entering their Nabu URL into the manual setup screen.

**Comment by ABeumer525** [comment]
Definitely not fixed. Still get this error.

**Comment by robbiet480** [comment]
@ABeumer525 What URL are you entering? What issue specifically are you getting? Can you please open a new issue, as this issue specifically deals with entering a Nabu Casa URL in manual setup.
