### ISSUE TITLE
Bottom bar covers part of UI

### ISSUE THREAD

**Issue by Phontana** [home-assistant/home-assistant-iOS#38]
The bottom bar covers a part of the UI. See attached image. This is the case when the menu is open, but also when you scroll down all the way to the bottom. The last 10-40 (I guess) pixels are covered by the bottom bar. I'm using the latest version (1.0.4).

![img_0902](https://cloud.githubusercontent.com/assets/13638753/26622481/d5cbc336-45ea-11e7-8271-f493d4b1fbbf.PNG)

**Comment by LaStrada** [comment]
I have the same issue

**Comment by hutchwilco** [comment]
Same issue: 
 It seems the bottom bar is not considered when deciding on the default position for the card to sit on the screen - consequently you can't ( or can barely) access drop down items. 
eg:
A climate card, with Operation mode drop down - cannot select the second option in the drop down as it is mostly hidden behind the bottom bar of the app.
screenshot of issue - can just see the sliver of the second dropdown option at the bottom right
![file_000](https://user-images.githubusercontent.com/4792731/31218584-491c52e8-aa17-11e7-8401-4e4eed10beb2.jpeg)


**Expected:**
Expect the card to be able to be scrolled up enough to access drop downs.


**Additional info:**
ios 10 and 11, iphone 5s
