### ISSUE TITLE
allow password safe when login in

### ISSUE THREAD

**Issue by RezzZ** [home-assistant/home-assistant-iOS#382]
HAC v2.0.0 (58):
When trying to connect to HA Local the Username and Password field are setup differently.
I use googles keyboard and that is allowed in the Username field but not in the Password field. I also am not allowed to change the keyboard nor the keyboard language, using the normally available globe icon in the bottom right) which is missing.

As a result (more or less) I also cannot use the nice password safe option for this password field where I should be allowed to enter passwords stored by iOS or by my default password safe Lastpass.

**Comment by robbiet480** [comment]
I don't control the username and password fields there, Apple does. Apple currently is unable to detect password fields when using Shadow DOM. Closing this issue in favor of more relevant one, https://github.com/home-assistant/home-assistant-polymer/issues/1622. Once that one is fixed or Apple fixes their Shadow DOM issues, password manager support will automatically happen.
