### ISSUE TITLE
Add toggles on-device for enabling each sensor

### ISSUE THREAD

**Issue by Joshfindit** [home-assistant/home-assistant-iOS#384]
I'm not actually all that keen on tracking battery percentage or charging status on my iPad.

I'd prefer a menu in the Home Assistant app like:
```
Device sensors >
  - Battery state
  - Battery level
  - Location
  - SSID
  - SIM
  - Etc
```
Where each one is a switch-toggle (or a menu itself with switch-toggles, whatever else makes sense)

I know these sensors can be ignored in homeassistant, but I'd much rather turn off the tap than plug it if that makes sense.

**Comment by AlecRust** [comment]
Dupe of https://github.com/home-assistant/home-assistant-iOS/issues/358.

**Comment by robbiet480** [comment]
Closing as dupe
