### ISSUE TITLE
[2.0b59] Error while creating integration

### ISSUE THREAD

**Issue by adec** [home-assistant/home-assistant-iOS#385]
2.0b59 appears to have broken the initial client registration/on boarding process.  I’m running HA 0.93.2.

After updating the iOS client to 2.0b59, I reset the client and tried to reconnect to home assistant.  During the connection process, the following error was presented: “Error: Response status code was unacceptable: 400” while creating the integration.

![IMG_0508](https://user-images.githubusercontent.com/632277/58482445-449fba80-8156-11e9-842f-8ccb6e489f61.png)

I have tried removing the mobile_app & iOS integrations, all related entities and restarting Home Assistant then trying to connect again but got the same error.

The only way to reconnect was to drop back to the previous beta version (2.0b58) then reconnect.  Once reconnected, I could then update to the latest beta version again.

**Comment by adec** [comment]
Just checked the Home Assistant logs and noticed the following log entries when I try to connect for the first time with the 2.0b59 after resetting the connection:

2019-05-28 14:45:12 ERROR (MainThread) [homeassistant.components.http.data_validator] Data does not match schema: extra keys not allowed @ data['supports_media_player']

Regards,

Adrian.

**Comment by Spankythemusical** [comment]
I am having this exact same issue, including version numbers.  The regular (or older, if prefered) app works as expected.

**Comment by robbiet480** [comment]
Known problem with build 59 during onboarding, fix should be out within 2 hours.

**Comment by adec** [comment]
Thanks Robbie. I really appreciate all the hard work you’re putting into the app. It’s amazing how much it’s come on in such a short space of time.

**Comment by robbiet480** [comment]
Apple took their sweet time on processing this build, just released as build 60. Issue fixed at abf12114fe204daab992d5a33e74506cead2a7b8
