### ISSUE TITLE
Display stops updating after a while

### ISSUE THREAD

**Issue by jjpeet** [home-assistant/home-assistant-iOS#387]
Hi @robbiet480 
This one has been bugging me for a while and I’ve been trying to pinpoint where the issue is before I report it.

I have a wall mounted iPad at the entry hall of my house and it displays HASS (using the iOS app). The home page of HASS for me displays a camera of the front of the house (amongst other things).
Most days when I get up in the morning the display has frozen (the clock on the camera stream will be displaying around 2 or 3am and the seconds not progressing). So I manually fresh it and everything is fine. I’ve noticed the same behaviour on my phone (running 1.5 on both).

For the last week I stopped using the app, and just have Safari displaying the same HASS home page - and it has been fine - it continues to display.

Would you have any hunch what might be causing this?  Happy to try different things to figure out what the issue is...

Thx
JP

**Comment by robbiet480** [comment]
Closing this as its a 1.5.x issue and 2019.1/2.0 has just been released. Please re-open this issue if this action was incorrect. Thanks!
