### ISSUE TITLE
App crash on pop-up dialog

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#390]
On 1.5.1 and 2.0 beta we get an app crash when a dialog in ha opens, eg delete an entity via entity registry.

**Comment by olbjan** [comment]
Actually this isn't happening in 2.0 beta. Just 1.5

**Comment by robbiet480** [comment]
This was a known issue fixed in #206. Is this happening to you in 1.5 or 1.5.1? It was only fixed in 1.5.1.

**Comment by olbjan** [comment]
I get the crash reproducible but only on iPad, not on iPhone. In 1.5.1.

**Comment by robbiet480** [comment]
Good feedback. The iPad specific issue was fixed in a 2.0 beta by setting the correct popover generator view. Not gonna go back and release a 1.5.2 just for that. Closing.
