### ISSUE TITLE
After connecting from Mobile APP sensors stop working

### ISSUE THREAD

**Issue by jsiemek** [home-assistant/home-assistant-iOS#393]
Setup ass follow:

Home Assistant Companion Beta 2.0.0 (60)
Home assistant 0.94 on Ubuntu 18.04.2 LTS
arch | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.3
timezone | Europe/Warsaw
version | 0.94.0
virtualenv | false

After connection from Home Assistant Companion Beta all sensors stops working.
![image](https://user-images.githubusercontent.com/36767404/59060439-69f09f00-88a1-11e9-81ee-da0e37c0deee.png)

In fact, no data is logged into database:
![image](https://user-images.githubusercontent.com/36767404/59060486-842a7d00-88a1-11e9-99cb-e21a4931a65d.png)

As it's dangerous for my daughters reptiles, I did immediately wipe and restore. So no insight whats really happened at HA side. It's working good with app version 1.5.

**Comment by robbiet480** [comment]
Everything started working the moment you wiped out all traces of 2.0?

**Comment by robbiet480** [comment]
Did you see any errors in your HA logs?

**Comment by TomBrien** [comment]
Closing this issue as stale and I cannot reproduce it. @jsiemek if there is still an issue with the current beta (build 68) reply here and I'll reopen and we can try and work out what is going on.

**Comment by jsiemek** [comment]
Hi,

It was still in companion app 64 and HA 0.98.
In CA 68 and HA 0.100.2 it’s resolved, so it’s OK to close as resolved.

Jared

W dniu sob., 19.10.2019 o 16:07 Tom Brien <notifications@github.com>
napisał(a):
