### ISSUE TITLE
Invalid JSON due to IOS Smart Quotes

### ISSUE THREAD

**Issue by clhumphreys** [home-assistant/home-assistant-iOS#398]
I don't know how many people actually use the dev tools area while on mobile.. however if you do, you'll find when attempting to supply some JSON, iOS messes things up by converting regular quotes into 'smart' quotes. 

This can be amended on each user's device through iOS settings, however it may also be possible to turn the option off at the app level - see [this stackexchange post](https://apple.stackexchange.com/questions/362020/how-do-i-type-a-hyphen-in-ios-12)

> A first step, if using a UITextInputTraits conforming control, would be to set smartQuotesType to UITextSmartQuotesTypeNo...

No clue if this is feasible. Thank you for a great app!

**Comment by TomBrien** [comment]
I do and this does bug me. You can select the correct quotemarks manually too but if a fix were to come along I’d be super happy.

**Comment by robbiet480** [comment]
[This would be the fix](https://stackoverflow.com/a/55162016/486182) but it needs to get done in frontend.

**Comment by robbiet480** [comment]
The correct attribute is being set on the service data textarea, but iOS doesn't seem to be respecting the linked fix, which it turns out relates specifically to macOS (that doesn't necessarily mean it wouldn't work for iOS, but doesn't improve the situation). Will leave this open but lower priority for me.

**Comment by TravelinMax** [comment]
I just wanted to add that this is an issue when creating/modifying automations in the GUI as well.

**Comment by TomBrien** [comment]
I believe this is now fixed in the front end (plus you can now use yaml). Feel free to open a new issue over on home-assistant\home-assistant-polymer if it is still present
