### ISSUE TITLE
"default" should be the default sound in 2.0

### ISSUE THREAD

**Issue by Hackworth** [home-assistant/home-assistant-iOS#399]
Silent should not be the default. "default" should be the default. This is a breaking change with no justifiable reason. Not only will it not make a sound, there's no vibration. Ref #377

**Comment by robbiet480** [comment]
I made this change to accomodate #241. I figured it was better in general to opt in for sound instead of having to figure out a (hopefully) elegant way for people to opt _out_ of sound.

**Comment by robbiet480** [comment]
Fuck it.

**Comment by robbiet480** [comment]
Changed back to previous behavior. Sound is on by default.

**Comment by DavidFW1960** [comment]
Thanks Robbie. It never made sense to me removing it....

**Comment by krissen** [comment]
Right decision, I’d say! (To let ‘default’ indeed be ‘default’.)
