### ISSUE TITLE
When the app reconnects, it doesn't know dimensions of a webcam correctly

### ISSUE THREAD

**Issue by riemers** [home-assistant/home-assistant-iOS#40]
This is how it shows when i just clicked on that particular room:

![image](https://user-images.githubusercontent.com/682041/27120689-dd8beb28-50e4-11e7-931f-1b091f87a740.png)

But when i try to scroll down:

![image](https://user-images.githubusercontent.com/682041/27120706-ede6e2c0-50e4-11e7-8be1-8071c15cdb3f.png)

It does not show the full image, it cuts it off. Going to another room and then back resolves the issue though.

If its a polymer issue, just let me know, i'll move it.

**Comment by amarczell** [comment]
If you still experience this issue i would suggest doing the following test. Load the page in Safari and check if you have the same issue.

**Comment by riemers** [comment]
Tried it in safari, same issue.

**Comment by amarczell** [comment]
This is what I expected. I would suggest opening an issue on the main HOME ASSISTANT github page. The video is rendered in a web view that the app has little control over. Sorry I couldn’t help more.

**Comment by riemers** [comment]
Should i not create the issue on the polymer frontend instead?

**Comment by riemers** [comment]
Closed in favor for correct repo https://github.com/home-assistant/home-assistant-polymer/issues/456
