### ISSUE TITLE
IOS Notification issue : Platform application is disabled

### ISSUE THREAD

**Issue by wilfredsmit** [home-assistant/home-assistant-iOS#401]
**Home Assistant release with the issue:**
v0.94.3

**Last working Home Assistant release (if known):**
v0.94.3

**Operating environment (Hass.io/Docker/Windows/etc.):**
HassOS on Proxmox

**Component/platform:**
notify.ios_iphone

**Description of problem:**
Looks like the same problem as last year. Certificate outdated.

`2019-06-19 21:54:11 ERROR (SyncWorker_9) [homeassistant.components.ios.notify] Platform application is disabled`

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
(https://github.com/home-assistant/home-assistant/issues/14555)
```

```

**Additional information:**

**Comment by robbiet480** [comment]
Looking into this within the next 10 minutes.

**Comment by robbiet480** [comment]
Certificate expired as it does once a year. Uploaded renewed certificate to AWS SNS and we are good to go! Apologies all.
