### ISSUE TITLE
2.0 beta does not work with front-end proxy

### ISSUE THREAD

**Issue by AriZuu** [home-assistant/home-assistant-iOS#403]
I have a setup where home assistant is accessed via front-end proxy server (apache + mod_auth_openidc), which requires authentication. It works fine with iOS 1.5 app and also with browser.

However, with 2.0 beta things won't work. App finds the home assistant from my network and even login seems to work. But after that I just get message "ObjectMapper failed to serialize response". Looking at front-end logs I can see that app is making a request that doesn't have cookie issued by front-end proxy:

“POST /auth/token HTTP/2.0” 302 385 “-” "Home Assistant " auth=-

When accessing the same system with 1.5.1 app:
“POST /auth/token HTTP/2.0” 200 234 “-” “Home Assistant/1.5.1 (io.robbie.HomeAssistant; build:4; iOS 12.2.0) Alamofire/4.7.3” auth=95f586c1-1e7d-e911-9998-e069955717cd

Note difference with "auth=" that logs the front-end cookie value. It is missing in 2.0 app request. Missing cookie results in front-end redirecting the it's login page (302 response).

**Comment by robbiet480** [comment]
@torarnv has been investigating this issue for me both on Discord and in issue #389. I think we've identified this as a bug in WKWebView, but he can say for sure.

**Comment by torarnv** [comment]
What you are seeing is the onboarding trying to confirm the server location, by hitting `api/discovery_info`. This is done without any cookies or (non-HA) authentication headers, so the proxy will redirect to the login form. This isn't what the verification-code expects, so you see the error about `"ObjectMapper failed to serialize response"`

I think the goal of that part of the onboarding is to catch various challenges such as HTTP basic auth or client certificate requests _before_ showing the ASWebAuthenticationSession, so it would probably be enough to just assume any non-error-response is good enough to continue. That way the ASWebAuthenticationSession will launch, which allows you to log in via the proxy auth, and finally pull out the required HA token.

That's one step closer, but unfortunately not enough to make HA work behind a proxy. Once onboarding is completed HA uses:

 - A WKWebView for the UI
 - An Alamofire HTTP session for API requests
 - An Alamofire HTTP session for webhooks

These do not inherit the cookies set in the ASWebAuthenticationSession during onboarding.

I worked around this by setting custom headers (Cloudflare Access) on the two Alamofire sessions. The WKWebView for the UI will let you authenticated with the proxy like during the onboarding ASWebAuthenticationSession, but to make Oauth providers like Google accept this you need to override the user agent to match Safari. That's what #389 is about.

One way to improve on this situation would be to make the change to the onboarding as suggested above, and then allow the user to add custom headers via a simple text field (in the advanced onboarding settings). Those headers could then be added to the Alamofire sessions.

Ideally we'd be able to pick up the cookies set during onboarding, and share them with both the WKWebView for the UI, and the Alamofire sessions. And once that cookie expires, HA would detect that (the way it detects that it lost access to HA today), and re-launch the onboarding. I don't know if that's possible though.

**Comment by AriZuu** [comment]
This is not problem with /api/discovery_info, I have opened it to access without authentication. I can see from logs that app gets it succesfully and continues after that. But after login screens, the /auth/token is hit without cookie.

**Comment by torarnv** [comment]
Hmm, then I dont know. Might be you're hitting one of the other issues I listed above.

**Comment by AriZuu** [comment]
I think the problem is that WKWebView and 2 x Alamofire are not inheriting the cookies from ASWebAuthenticationSession. Ideal solution would be that all these objects could somehow share cookies. I'm a programmer, but iOS land is unknown territory for me so I don't know how difficult that would be.

(My OAuth provider is microsoft, it seems that they have no problem with user agent name)

**Comment by Patrik-Hansson** [comment]
I'm also getting this "ObjectMapper failed to serialize response" behind a HAProxy when trying to connect to Home-Assistant for he first time with the app when not on wifi.

**Comment by AriZuu** [comment]
My experience is currently quite the opposite. Home Assistant app automatically updated to 2.0 on all my devices and everything seems to be working with my setup. I think that I haven't changed anything, there must be some fixes to the app since the beta version.

**Comment by Patrik-Hansson** [comment]
Maybe I should have created a new issue since I'm not on beta?
Would you like to test and reinstall the app and make the first setup from external?

**Comment by AriZuu** [comment]
I didn't have beta on my devices any more, kind of gave up with it. After 2.0 update hit my devices automatically, I set up the connection from scratch and was kind of surprised that everything worked.

I'm on iOS 13.2.3 (don't know if it matters).

Note that I'm allowing some URLs without authentication:
/manifest.json
/static/
/frontend_latest/
/service_worker.js

You might want to check your HAProxy logs what request triggers the problem.

**Comment by torarnv** [comment]
> Note that I'm allowing some URLs without authentication

That might explain the difference. I have HA behind Cloudflare Access with no URL exceptions. Will try latest 2.0.

**Comment by Patrik-Hansson** [comment]
My HAProxy have no authentication, it just passes the traffic. I do have some front->back->front->back to be able to have both TCP and HTTP on same IP. (Having RemoteDesktop Gateway and normal http(s) on same ip). It worked a while back on the old companion app.

**Comment by Patrik-Hansson** [comment]
Update to this: I'm using port 443 on the outside and by NOT specifying the port in the App it worked. 
so just https://fqdn and not https://fqdn:443

**Comment by olbjan** [comment]
Ther is now documentation to recommended configuration with nginx reverse proxy. That translates pretty well to other proxies too: https://companion.home-assistant.io/en/troubleshooting/networking#addendum-reverse-proxy-via-nginx

**Comment by AriZuu** [comment]
@olbjan Documentation seems to cover only very basic setup, which offloads ssl processing to NGINX for example ? However, original problem here was not the proxing itself, but performing OAuth/OpenID Connect authentication at proxy level (so one can have a common authentication frontend for all services, Home Assistant is just one of them for me). Proxy frontend with authentication usually throw http cookies in to the mix. 

These cookies (actually lack of them) were the problem, Home Assistant app was not sending them back in all requests. Because of this, I couldn't make beta version to work.

However, the release version works. I don't know if there have been some changes in code or is it because I upgraded to iOS 13.

Maybe I could produce some documentation for setup like mine (Apache, mod_auth_openidc) if that would help others.

**Comment by olbjan** [comment]
I am fairly confident nothing related to auth changed between beta and store app. I would actually not recommend creating documentation for a setup like yours. My reason being that I assume that home assistant will move in a direction where the user login to HA, person entity in HA and the app device tracker and notify services will be somehow connected - based on login at setup time. This would break with external auth.
I deliberately only documented a basic setup as documentation is targeted at the broadest spectrum of users with the idea of needing as little technical knowledge as possible to get it up and running. I think more advanced setups are all fine but users that want them should learn how things work and thus be able to get them running without requiring support.

**Comment by AriZuu** [comment]
Must be iOS 13 that "fixed" it then because I dig out the actual HTTP requests back then and found out that problem was missing cookies. But I think that also the setup pages seemed a little bit different than in the beta I was using. Doesn't really matter as it works now.

Documentation is just fine for most users, I guess. However, when having other services than just Home Assistant it would be nice to be able to use common source for authentication. For example, grafana has a very simple system (AuthProxy) that works ok.

**Comment by AriZuu** [comment]
I think that this issue could be closed because the original problems seems to be resolved.

**Comment by torarnv** [comment]
> Maybe I could produce some documentation for setup like mine (Apache, mod_auth_openidc) if that would help others.

Please do!

**Comment by TomBrien** [comment]
@AriZuu please do. You can add by clicking the edit button on [this page](https://companion.home-assistant.io/en/troubleshooting/networking)
