### ISSUE TITLE
Beta 2.0: Forgetting Login

### ISSUE THREAD

**Issue by dummptyhummpty** [home-assistant/home-assistant-iOS#406]
Every once in a while when I open the Beta 2.0 (62) app, I'm prompted for my HA login even though it should be saved. Forcing a page refresh (swipe down) and I'm logged into HA without entering credentials. It's like the app forgets that it has the login saved until I force a refresh.

**Comment by TravelinMax** [comment]
This happens to me as well. It seems to be whenever I switch networks (WiFi > cell, WiFi > other WiFi). I don’t think it happens _every_ time, but most times.

**Comment by TomBrien** [comment]
This is duplicated by #426 which is on the project for 2019.2. It is understood and due to issues with access token refresh. Closing in favour of #426
