### ISSUE TITLE
Beta 2.0 (62): Can't log in

### ISSUE THREAD

**Issue by wixoff** [home-assistant/home-assistant-iOS#409]
Beta build 62 has been working pretty well for a while, but I wanted to get rid of my superfluous mobile_device entities and integrations from past beta use, so I followed the ["cleaning between builds" instructions](https://companion.home-assistant.io/en/next/troubleshooting/beta-cleaning).  I followed all steps there, including deleting and reinstalling the beta app.

Now I can't log in - I put in the external URL, I hit the "CONNECT" button, and I get a popup that says **Home Assistant β" Wants to use "(null)" to Sign In** [Cancel] [Continue].

Pressing "[Continue]" opens a browser and sends me to **somethingbroke.fake**.  If I cancel out of that, I get another popup (two identical ones, actually, one behind the other and offset diagonally) that both say "URL Unavailable," "Expected to have a External URL but none available!..."

If I put my URL there and hit "[OK]," the app crashes back to the iOS springboard.

This doesn't work with an external URL or with an internal numeric address/port URL when on VPN.  Same results.

Access still works fine from Safari, so this is pretty clearly an app issue.  I'm using an iPhone 7 Plus on iOS 13 public beta 1.  (Companion build 62 was working fine on this iOS beta before I wiped it out and reinstalled.)

**Comment by nnmalex** [comment]
That's the same as issue #374 

I also have this issue.

**Comment by wixoff** [comment]
Yes, thanks - I didn't see that one, and it appears to match my symptoms.  Closing this report as a duplicate.
