### ISSUE TITLE
Beta 2.0.0 (62): notify.{device} entity not-found after switching from local to remote connection 

### ISSUE THREAD

**Issue by jeffkindred** [home-assistant/home-assistant-iOS#413]
Two days ago I noticed that I stopped receiving notifications seemingly out of nowhere in the middle of the day. The issue fixed itself after I followed a few troubleshooting/beta maintenance tips and restarted HA a couple times.

Yesterday, I again stopped receiving notifications and a correlation between the two days showed itself to me. I stopped receiving notifications after leaving my home... when the app switches from its local -> remote connection it appears that the notify.{device} entity disappears. Once I was able to see the correlation, I set the app to 'always use remote connection' and am unable to repro the issue now.

I would be happy to attempt to recreate the issue if there are logs that I can provide or other ways that I can help add data points to the issue... let me know!

**Comment by TomBrien** [comment]
Hi @jeffkindred can you recreate this with the current build (68)?

**Comment by TomBrien** [comment]
Closing this as stale. Please let me know if the issue is still present
