### ISSUE TITLE
No "Allow Always" for location during onbaording, location only updates when forced

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/home-assistant-iOS#414]
After doing a clean install on iOS 13 public beta 1, going through onboarding I saw that "Always Allow" was gone from the location permission request ([as expected](https://9to5mac.com/2019/06/08/ios-13-location-permissions/)). However, if I select "Allow Once" (or any other option) the button next to location does not change from "Allow" to "Allowed". I can complete onboarding but location updates are only sent when forced by pulling down within the app. Even if I change the permission to "Always Allow" in iOS settings the app does not seem to notice this change and does not attempt to automatically send location updates.

#### Workaround
1.  After carrying out clean install on iOS 13 go to iOS settings>Privacy>Location and change the Home Assistant β setting to "Always Allow".
2.  Delete the `mobile_app` integration in HA.
3.  In the App Configuration, tap reset and then force close the app.
4.  Re open the app and go through onboarding again. When you get to the permissions page, everything should already be "Allowed" and no input required.

**Comment by olbjan** [comment]
When the app has no permissions to access location and you run pull to refresh / send location the app shortly throws a "kCLErrorDomain-Error 1" message.

**Comment by TomBrien** [comment]
I don't have this behaviour from what I remember (I now have work around in place). Pull to refresh/send location worked.

**Comment by TomBrien** [comment]
iOS 13 seems to have eased off a little on this. Closing (for now...)
