### ISSUE TITLE
Cannot paste into login form

### ISSUE THREAD

**Issue by michaelwoods** [home-assistant/home-assistant-iOS#421]
I was setting up a new iPhone and went to login (new auth method) and was not able to paste a copied password. I use password managers and copy/paste randomly generated passwords.

I tried to paste into the password field and was not able to, forcing me to type a long and complex password into the form. Maybe not related but I tried twice and observed a "something went wrong" message before giving up and authenticating via the Local Network method. You also cannot paste into the username field.

**Comment by TomBrien** [comment]
Is this with the release app (1.5.x via the the App Store) or the beta (2.0 from TestFlight)

**Comment by iMicknl** [comment]
@TomBrien I have experienced the same behaviour with the latest 2.0 beta from TestFlight on iOS 13.

**Comment by michaelwoods** [comment]
This was observed on the release app via App Store.

**Comment by TomBrien** [comment]
Are you able to paste the password if you access your instance through Safari or Chrome on your device?

**Comment by robbiet480** [comment]
Closing this as its a 1.5.x issue and 2019.1/2.0 has just been released. Please re-open this issue if this action was incorrect. Thanks!
