### ISSUE TITLE
Problem with location presence app 1.5 stable

### ISSUE THREAD

**Issue by koles142** [home-assistant/home-assistant-iOS#424]
Hi, I have problem with tracking my devices. It was working good before update Hass.io to version 0.96.1. I don't change anything in config. On my phone localization presence working when I enter or leave zone or send manual update location. I don't see Backgroud update or significate update. I can force update with ios notification requesting update, but it working only when app is open. On second phone is the same situation. After restart HA tracking is not refresh. I see status "away" even when I'm at home. I have to manual update location for the change or enter/leave zone.

App has all permission in ios. I tried reset app and configure again - no result. How I said I didn't change any config, It stop working after update Hass.io.

Have you any idea?

**Comment by robbiet480** [comment]
Closing this as its a 1.5.x issue and 2019.1/2.0 has just been released. Please re-open this issue if this action was incorrect. Thanks!
