### ISSUE TITLE
[2.0 Beta] unique device identifiers omitted from sensors

### ISSUE THREAD

**Issue by brianhanifin** [home-assistant/home-assistant-iOS#435]
As you can see in this example screenshot, all of the device sensors are missing the named identifier prefix. For example I would expect `sensor.ssid` to be `sensor.brian_iphone_ssid` and `sensor.ssid_2` to be `sensor.brian_ipad_ssid`.

<img width="300" alt="Screen Shot 2019-09-05 at 8 37 25 AM" src="https://user-images.githubusercontent.com/57336/64357226-264d2480-cfb9-11e9-82aa-8d2a81029416.png">

I'm sorry to have not realized this sooner. But it is painfully obvious now that I have reinstalled the beta apps on both my iPhone and my iPad, now there are twice as many duplicates. Its really going to get confusing when I add the app to my wife's iPhone, her iPad, my son's iPads, and both of my in-law's iPhones (as they live with us as well). :)

**Comment by SeanPM5** [comment]
This is a known issue and on the roadmap of things to do, but there's no timetable for it yet. (Robbie is the sole developer on the iOS app and he has a lot on his plate right now.)

In the meantime though it's a fairly easy fix if you're OK with doing it manually. You can head to Configuration > Integrations page and find the "Mobile App" entries where they should be neatly organized by device (e.g. Brian's iPhone, Brian's iPad, etc). 

Once you click through to a device such as "Mobile App: Brian's iPhone" you will see all of the associated sensors. Then you can just click on them one by one and press the "Edit" cog in the top right corner of the more-info dialog, and manually enter whatever prefix you want like `brian_iphone_` for example. Repeat this process for the dozen or so other sensors.

You should only have to do this once and it shouldn't take more than 2-3 minutes per device. And then you will have clean, easy readable, unique entities once again.

**Comment by brianhanifin** [comment]
That's great! I just wanted to do my small part to help make this app the best it can be. :)
