### ISSUE TITLE
iOS Version 2.0.0 (62) expires in 10 hours!

### ISSUE THREAD

**Issue by causefx** [home-assistant/home-assistant-iOS#437]
The TestFlight app says that this beta expires in 10 hours....  Will you be pushing a new version as this version will stop working....

**Comment by SeanPM5** [comment]
Yep Robbie started a new TestFlight build about an hour ago... If all goes well it should be available soon.

**Comment by causefx** [comment]
sweet. thank you.

**Comment by robbiet480** [comment]
Build has failed twice, but I'm still at it!

**Comment by causefx** [comment]
thanks for the heads up :)

**Comment by Spirituss** [comment]
Looking forward for it!
