### ISSUE TITLE
Not able to proceed with installation with newest app

### ISSUE THREAD

**Issue by eterpstra** [home-assistant/home-assistant-iOS#438]
Hi Robbie,

So i tried to install the app on my ipad and iphone with the newest home assistant app which was released today.

However, i am getting this error when the adress of HA is found: 

https://www.mupload.nl/img/uq1nzg.39.22.jpeg

Any idea what this might be?

Regards,
Elroy

**Comment by TomBrien** [comment]
Do you have HA cloud (Nabu Casa) enabled but the Remote UI switched off?

**Comment by eterpstra** [comment]
Hi TomBrien,

That was indeed the problem. It is solved now!

Thanks

**Comment by TomBrien** [comment]
Glad to hear it. This is known so hopefully will be addressed going forwards. Thanks for letting us know and cheers for supporting HA with Manu Casa 🙂
