### ISSUE TITLE
Bug?: Push notification with url to image attachment not working

### ISSUE THREAD

**Issue by aukedejong** [home-assistant/home-assistant-iOS#440]
Hi,
First, I'm not sure the problem is in the companion 2 app. Maybe it's on the server side.

Earlier versions of the beta did show an image in the iOS notification. Lately it stopped working. I'm not sure why and what changed.

Use the JSON in de HA developer tools with service notify.mobile_app_.....

`{
    "title": "Titel",
    "message": "Deurbel!!!",
    "data": {
      "attachment": {
        "url": "https://myhostname:8123/local/camera_stills/deurbel.jpg"
      },
      "subtitle": "Subtitle",
      "push": {
        "thread-id": "deurbel-groep"
      }
    }
}`

What I gathered on from community topics, linked below:
It's not working with the Companion beta 2.0.0 (63) regardless of what HA en iOS version is used.

The notification is received, but without image.

See these topics:
[https://community.home-assistant.io/t/receiving-camera-snapshots-as-a-notification-in-the-ios-app/89579/24](https://community.home-assistant.io/t/receiving-camera-snapshots-as-a-notification-in-the-ios-app/89579/24)
[https://community.home-assistant.io/t/ios-notification-attachment-not-working-anymore-ios-13-issue/139513](https://community.home-assistant.io/t/ios-notification-attachment-not-working-anymore-ios-13-issue/139513)

Thanks for the great work.

**Comment by fillwe** [comment]
Yeah noticed this today as well, still using iOS 12.4 so it doesn’t seem to be an iOS 13 issue

**Comment by bjorn-ha** [comment]
Same here. Seems to be an issue with hassio 0.99+. Reverting back to 0.98 did solve the issue for some users.

**Comment by SeanPM5** [comment]
It's not an issue with Home Assistant or iOS 13, it's an issue with the b63 TestFlight build. Even though the release notes stated no changes, there were actually two regressions - image attachments in notifications not showing, and Siri Shortcuts being broken. (Both were previous bugs that got fixed already but creeped back in somehow.)

Normally with TestFlight you would be able to use the "Previous Builds" option to revert to an earlier working build, but in this case b62 expired so you cannot go back. Unfortunately nothing can be done except to wait for the next build.

**Comment by bart1604** [comment]
Hello everyone,

I have a simillar issue. I get the notification with the attachment on my iPhone but not on my apple watch. I'm sure this worked before. I use this to send a photo of my frontdoor camera when someone rings the doorbell.

I have an iPhone 8 with the new Apple Watch 5. The same thing for my girlfriend, she has the oldest apple watch and a iPhone 8 Plus.

I tried to back my HA down to 98.3, same thing.. Does anyone have a solution?

**Comment by TomBrien** [comment]
If iOS believes you are actively using your phone (screen unlocked or still on etc.) a notification is only sent to the phone not the watch. Are you receiving any notification at all on the watch in these cases?

**Comment by bart1604** [comment]
Thanks for the quick reply.

Everything else is working. The title of the notification as well as the text is showing on the Apple Watch but not the photo. I have the phone locked. When I get my phone, it shows the notification as well but with picture.

I'm used to also get the photo (attachment) on my apple watch.

**Comment by TomBrien** [comment]
I would guess that it’s related to the bug in b63? Just to check this is with the 2.0 beta yes?

**Comment by bart1604** [comment]
No, I don't think so. I've never given myself op for beta testing. 
The only thing that has changed for us is, upgraded to iOS 13.1.1 and updated home assistant to 99.x

**Comment by aukedejong** [comment]
It's fixed in the latest beta, 2.0.0 (66)
