### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by bieniu** [home-assistant/home-assistant-iOS#441]
I can do Polish translation. Please add language pl-PL.
English name: Polish
Native name: Polski

**Comment by olbjan** [comment]
I have added pl_PL to lolalise.co. You should be able to start translating and the translation bundle can be updated independent from the app.

Thank you for your help with the project!

**Comment by bieniu** [comment]
@olbjan Still no pl_PL at lokalise.co
![image](https://user-images.githubusercontent.com/478555/67157329-05ebe600-f32b-11e9-8e58-9ba314800ba8.png)

**Comment by olbjan** [comment]
Sorry, I just learned I need to assign pl-PL as a contributable language.... you should see it now.

Now to find out how everyone else can see it...

**Comment by bieniu** [comment]
Yes, now Polish is available. Thanks.
