### ISSUE TITLE
Siri Shortcuts not working in iOS 13

### ISSUE THREAD

**Issue by tkhan456** [home-assistant/home-assistant-iOS#444]
Using the Home assistant 2.0 beta app, I've created some Siri Shortcuts.  They used to work in iOS 12 but since upgrading, I get the following error "Could Not Run Call switch.turn_on with data" "Failed to call service, Home Assistant is not currently reachable". Anyone else experience this?

**Comment by SeanPM5** [comment]
Yeah, this is a known issue. Build 63 contained a regression with Siri Shortcuts. And unfortunately you can't downgrade to b62 in TestFlight because that build has expired, so the only option is to wait for the fix.

Robbie is hoping to release a new build soon.
