### ISSUE TITLE
Beta 2.0 app (builds 66 and 67) do not work with HA 0.99.3

### ISSUE THREAD

**Issue by KungFuJoe23** [home-assistant/home-assistant-iOS#451]
Not sure if this is by design but the app never gets past the Connect button when setting up the app and locating the server address.  Tried builds 66 and 67 and had to revert back to 63 to get the app functioning again.

Haven't tried upgrading my HA to .100.x due to the beta mobile app crash issue.  Not sure if both HA and the mobile app have to be upgraded at the same time for everything to function but I always like to upgrade and test each component at a time when possible.

**Comment by jorisrymenants** [comment]
I have the same problem.
After upgrading to build 66 my connection data was not retained.
I could not enter new correct external URL.
I removed the app to trigger onboarding process again. My local Wifi network gets detected. My home assistant URL gets detected, but when I push button to connect, nothing happens and the authentication screen is not shown.

updated to build 67 and still same problem.

I am on HA 0.99.3 with DuckDNS add-on.

**Comment by TomBrien** [comment]
Build 68, should fix this. You may need to delete the "Mobile App" integration (Configuration>Integrations) in HA then uninstall the app on you phone before reinstalling. Closing this for now. Feel free to reply on here if problem persists and we can re open.
