### ISSUE TITLE
iOS 13 Dark Mode: Action Editor Icons are blck on grey

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/home-assistant-iOS#454]
In the new App Configuration screen in b68, when Dark Mode is enabled in iOS, the action icon selector shows the icons as black but the background is dark grey making it very hard to see the icons. Perhaps a light grey would be nicer. Screenshot accutally makes it look not as bad as it is at medium screen brightness
![IMG_0107](https://user-images.githubusercontent.com/12411302/67144862-ac74b000-f273-11e9-8a93-ab665b38816c.PNG)

**Comment by na239575-lang** [comment]
New user
