### ISSUE TITLE
Importing system sounds for notifications crashes b68

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/home-assistant-iOS#455]
Importing system sounds in the App Configuration->Notifications section worked in b63, but immediately crashes b68.  When I re-open the app and go back into the System Sounds section, I see that it's imported exactly one new sound.  Successive attempts appear to import one more sound each time.

Home Assistant version: 0.100.2 (Hass.io)
iPhone XS Max running iOS 13.1.3.

I uninstalled the app and cleaned everything in config & .storage related to mobile_app and the iOS device before installing b68.  The app is otherwise working fine.

**Comment by garyak** [comment]
I successfully installed a .wav file through iTunes on an iPhone 8, iOS 13.1.2, HA 0.100.2, and beta build 68 without a crash. Tested with a service call.

**Comment by robbiet480** [comment]
Found answer [here](https://stackoverflow.com/questions/43071654/modifications-to-the-layout-engine-must-not-be-performed-from-a-background-threa#comment102687928_44200030). Fix inbound.
