### ISSUE TITLE
Apple Watch complication icons picker scrolls underneath heading (visual bug)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#457]
iOS 13.1.3. When you scroll the list of icons, they scroll underneath the "heading" part which now seems to be transparent. So these UI elements overlap each other near the top. See screenshot.

![icons](https://i.imgur.com/biI5k14.jpg)

**Comment by TomBrien** [comment]
I believe this is fixed. Reopen if I'm wrong
