### ISSUE TITLE
notify.notify service does not send notifications to all registered mobile_app devices

### ISSUE THREAD

**Issue by talondnb** [home-assistant/home-assistant-iOS#460]
My wife and I both use the mobile app with iOS. Both devices have different names. Wife is using a regular user account, mine admin.

From a clean install (integrations removed), the first registered mobile_app device will appear and get notifications fine under notify.notify service call. After onboarding the second device and restarting home assistant, still only the first registered device will get the notifications.

Resetting to new and reversing the onboarding order exhibits the same behaviour.

**Comment by TomBrien** [comment]
`notify.notify` is not supported for all devices with `mobile_app`. You can create a notification group [see here](https://companion.home-assistant.io/en/notifications/basic#sending-notifications-to-multiple-devices). If that gives you an acceptable way of doing what you're after

**Comment by TomBrien** [comment]
Ok I will close. I believe the reason for not supporting `notify.notify` was to ensure the notification service used could remain free, I may be wrong
