### ISSUE TITLE
Special "delete_alert" notification type not functioning correctly

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#463]
The following doesn't seem to work in the 2.0b app:
 
>You can now send a push with `message` set to `delete_alert` to not show a message.
_Originally posted by @robbiet480 in https://github.com/home-assistant/home-assistant-iOS/issues/92#issuecomment-465548131_

The purpose of this is to update the badge count only without sending a visible message to the lock screen. Not sure if this _ever_ worked in 2.0b, or if this was a recent regression. But when I try it, it's sending the notification with "delete_alert" text.

IIRC something like this happened before with the `request_location_update` early in the 2.0b phase and that was fixed server-side without requiring an updated build.

**Comment by robbiet480** [comment]
`delete_alert` only existed for the v1.x app. I've now re-implemented it for v2.x (only needed a server side change).
