### ISSUE TITLE
Not registered for remote notifications

### ISSUE THREAD

**Issue by huangqingchao** [home-assistant/home-assistant-iOS#465]
Home assistant version: 101.3
iPhone Xr 13.1.3
Mobile App 2.0.0 (68)
Has cleaning between builds
The file `known_devices.yaml` was not created

![image](https://user-images.githubusercontent.com/19640477/68725419-589e8200-05f9-11ea-9521-eb6aa2d5f513.png)

![image](https://user-images.githubusercontent.com/19640477/68725462-7b309b00-05f9-11ea-9e4a-1cb095864a45.png)

![image](https://user-images.githubusercontent.com/19640477/68725498-9ac7c380-05f9-11ea-9371-3267c980c759.png)

![image](https://user-images.githubusercontent.com/19640477/68725527-a915df80-05f9-11ea-912f-624b693c5de7.png)

**Comment by huangqingchao** [comment]
I have cleaning between builds, and I configure the Mobile App (2.0.0.68).
But the file "known_devices.yaml" was not created

**Comment by huangqingchao** [comment]
more info 
![image](https://user-images.githubusercontent.com/19640477/68752671-ab4e5d00-063e-11ea-8bb4-bc5bfb6d7417.png)

**Comment by TomBrien** [comment]
Please try restarting Home Assistant while keeping the app open

**Comment by huangqingchao** [comment]
> Please try restarting Home Assistant while keeping the app open

I has try it more time,but not work for  me

**Comment by TomBrien** [comment]
In your screen shot above you have no push ID, is this still true? If so try resetting the push ID with the “reset” button

**Comment by huangqingchao** [comment]
I tried clicking the reset button, but still can't to display the push ID.
I think the registration push ID is successful. Because in the screenshot above I can see the log of the registration push ID success. But just can't show it.

In the program

`func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        let apnsToken = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()
        Current.Log.verbose("Successfully registered for push notifications! APNS token: \(apnsToken)")

        var tokenType: MessagingAPNSTokenType = .prod

        if Current.appConfiguration == .Debug {
            tokenType = .sandbox
        }

        **Messaging.messaging().setAPNSToken(deviceToken, type: tokenType)**
    }`

It looks like after registering push Id successfully, a message will be sent (maybe sent to the home assistant server)

`extension AppDelegate: MessagingDelegate {
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        Current.Log.info("Firebase registration token refreshed, new token: \(fcmToken)")

        Current.settingsStore.pushID = fcmToken

        guard let api = HomeAssistantAPI.authenticatedAPI() else {
            Current.Log.warning("Could not get authenticated API")
            return
        }

        _ = api.UpdateRegistration()
    }
    // swiftlint:disable:next file_length
}`

After the APP receives the return message, it will store and display the push ID.

I guess
1. The APP fails to send the Push ID to the server.
2, the server returns a message, the APP receives the failure
**3. The server is not configured successfully, and there is no information about this phone, so this message is not processed.**

**Comment by TomBrien** [comment]
I assume the app is working ok otherwise. If a couple more restarts of Home Assistant doesn’t fix it. I would suggest completely removing the integration[see here](https://companion.home-assistant.io/en/troubleshooting/beta-cleaning) and uninstalling the app then trying again. I have seen a few people having issues getting the service running.

**Comment by huangqingchao** [comment]
Wait until Sunday, I will try to reinstall the Raspberry Pi, home assistant and app, and see if it works。

**Comment by TomBrien** [comment]
If home assistant is working properly should be no need to reinstall the Pi

**Comment by huangqingchao** [comment]
Ok, I hope that reinstall can solve the problem.

**Comment by huangqingchao** [comment]
Trying to reinstall Raspberry Pi, home assistant and app, still can't get push Id

**Comment by huangqingchao** [comment]
I found the cause of this problem.
```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        let apnsToken = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()
        Current.Log.verbose("Successfully registered for push notifications! APNS token: \(apnsToken)")

        var tokenType: MessagingAPNSTokenType = .prod

        if Current.appConfiguration == .Debug {
            tokenType = .sandbox
        }

        Messaging.messaging().setAPNSToken(deviceToken, type: tokenType)
    }
```

After registering push Id successfully, a message will be sent.

After the send and server have processed the token, they will call back from the following code.
```
extension AppDelegate: MessagingDelegate {
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        Current.Log.info("Firebase registration token refreshed, new token: \(fcmToken)")

        Current.settingsStore.pushID = fcmToken

        guard let api = HomeAssistantAPI.authenticatedAPI() else {
            Current.Log.warning("Could not get authenticated API")
            return
        }

        _ = api.UpdateRegistration()
    }
    // swiftlint:disable:next file_length
}
```
It seems to be receiving a message from Firebase
In China, communication with Firebase requires VPN.......
After opening the VPN, restart the APP and get the Push Id.
![image](https://user-images.githubusercontent.com/19640477/68914227-ea90c100-0798-11ea-8540-d6d1cf401e3f.png)

After restarting the Home assistant, I also found my mobile phone.
![image](https://user-images.githubusercontent.com/19640477/68914271-0e540700-0799-11ea-8f1d-b627cf2f2a4c.png)

**Comment by liangtailin** [comment]
@huangqingchao Thanks!

**Comment by cynicer** [comment]
Just ran into a similar issue. Same symptoms, but it turned out that my adblocker is blocking the Firebase connection. Couldn't find an error in the log, but temporarily disabling the Adblocker to allow the push id to be fetched solved my issue. Would be really nice if there'd be an error message for this.

**Comment by cristianstoica** [comment]
For the iOS (and possibly Android) notification to work it looks like two (sub)domains are needed to be allowed (if blocked):
[firebaseinstallations.googleapis.com](http://firebaseinstallations.googleapis.com/)
[fcmtoken.googleapis.com](http://fcmtoken.googleapis.com/)
