### ISSUE TITLE
The future of the iOS app

### ISSUE THREAD

**Issue by cmsimike** [home-assistant/home-assistant-iOS#47]
Hi,

First - by no means do I want to step on anyone's toes here. I am just a community member that loves home assistant and its iOS app, and would love to see both continue to evolve together.

I fully understand that work on this project are best-efforts, as time permits. Everyone has a life and there is no expectation of anything.

Saying all that, I am concerned at the lack of updates, and as such, I would like to volunteer as another maintainer for this project, if that at all is a viable idea to @robbiet480 and the community. 

If not, that's fine! But I did want to throw the option out there so that there could be movement on this project.

**Comment by Uksa007** [comment]
The app defiantly needs some love. 
The location tracking is basically unusable, which is a pity as it would be a great all in one solution!
I'm happy to help out where ever I can, testing etc!

**Comment by amarczell** [comment]
Second that. I can also throw in a few hours of coding time per week if we decide on a direction. I found myself not using the app any more. Would be happy to see this app get back on track.

**Comment by arsaboo** [comment]
Any and every PR is welcome. I am sure once a PR is submitted, one of the devs will review and merge it. Once the devs see participation, they are more likely to give us ownership of something.

**Comment by cmsimike** [comment]
@arsaboo I don't disagree with that sentiment, but I guess what drew one of my concerns are the two currently open PRs without activity.

**Comment by arsaboo** [comment]
@cmsimike Unfortunately, both those PRs having failing builds and the original authors have not updated them.

**Comment by cmsimike** [comment]
@arsaboo That makes sense then!

**Comment by cmsimike** [comment]
I am in the middle of a few other personal projects. I do want to address some issues I keep running into with the app. Hopefully I will have an opportunity to dedicate some time to the iOS app in the near future.

**Comment by arsaboo** [comment]
@cmsimike That will be phenomenal. I wish I had the knowledge to work on the iOS app. It definitely needs some love and there are lot of low hanging fruits here.

**Comment by Uksa007** [comment]
@cmsimike @arsaboo
Both PR seems to fail create_keychain with unknown password.
Is there a password that we need to hunt down to allow the build to complete?

 💥   | create_keychain                     | 0           |
+------+-------------------------------------+-------------+
[02:44:12]: fastlane finished with errors
[!] No value found for 'password'

**Comment by TWilb** [comment]
@Uksa007 @arsaboo @cmsimike The builds never seem to pass, so I don't think that this is an issue with the PRs and no reason not to merge them.

**Comment by arsaboo** [comment]
May be @balloob can provide some inputs.

**Comment by mnoorenberghe** [comment]
@cmsimike @amarczell or others following this bug: I just submitted 4 pull requests (for 2 issues plus other cleanup) so I'd appreciate reviews to get some momentum on this repo. Reviewing will be a good way to get familiar with the code and add confidence for the official reviewer. Thanks :)

**Comment by balloob** [comment]
I don't really have any input. Never was involved with the iOS app. This is the problem with marking things "official". It means that when maintainers are not responding, it ends up on my plate 🤔 

I am willing to give write access to both @mnoorenberghe and @cmsimike as I have seen both contributing to the main repo before. @mnoorenberghe and @cmsimike, let me know your thoughts.

**Comment by mnoorenberghe** [comment]
👍  That will be a good step forward to at least be able to land code. We'll still need Robbie's help to be able to release builds at some point.

**Comment by robbiet480** [comment]
Hi all,

The app is not dead. It has a future.

@mnoorenberghe Thank you so much for the PRs, these all look great. I will be reviewing and hopefully merging all of them today and cutting a release shortly thereafter. I agree with @balloob, I am more than happy to provide write access to this repo for you (and @cmsimike). 

FYI, the reasons builds were failing was just because of fastlane/Testflight issues, the failures can be ignored.

I'd like to extend my apologies for the lack of communication. As I said, I was slammed at work and have been for the last few months, to the detriment of the commitments that I have made to Home Assistant. I am now at a point where I am dug out from under my pile of $dayjob work and can begin to commit time to HA once more. I hope to spend a lot of that time on the iOS app as I know it needs a lot of TLC.

Thanks for sticking with me thus far, here's to a brighter future for the iOS app and all of Home Assistant.

**Comment by HFeenstra** [comment]
Hi @robbiet480 glad you were able to come out of the darkness of work ;)

I would say: take your time with others to make the best out of it!

**Comment by cmsimike** [comment]
@robbiet480 Welcome back!!
There are no apologies needed! I'm sure everyone understands that this is not your (or anyone's) primary life efforts, so I/we was/were not expecting anything! I merely wanted to help a project I believe in. This is your project. I just want to be there to help, if you and the community will allow it.
