### ISSUE TITLE
Error on pull to refresh when location permission off

### ISSUE THREAD

**Issue by y0ast** [home-assistant/home-assistant-iOS#474]
In 2019.1 (2.0): when location permissions are off (`never`) and one does pull to refresh a red bar appears on the top with the text:

```
That operation cannot be completed. (kCLError) <more_I_can't_read>
```

When I allow the app to access my location (`always`) the error disappears.

**Comment by TomBrien** [comment]
Flagging this as a bug as if a user decides to revoke location permissions, this will pop up when trying to refresh

**Comment by d0ugal** [comment]
I accidentally denied access and didn’t notice. Then got this error and was confused. Some sort of notification would be good, but this bug helped me figure it out anyway. Thanks!
