### ISSUE TITLE
Can't turn off Firebase Cloud Messaging

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#475]
In privacy settings turning off firebase cloud messaging has no effect through app restarts.

**Comment by amamenu** [comment]
Hi @robbiet480 
Could you fix this bug alone as soon as possible? Because this bug is directly related to privacy issues. If wait to collect more bugs and then work on them together, it could be a long time.

**Comment by TomBrien** [comment]
Just so you know. Robbie is aware of this and it is the top priority fix
