### ISSUE TITLE
Ask for device name during onboarding

### ISSUE THREAD

**Issue by poldim** [home-assistant/home-assistant-iOS#478]
**Feature Request:**
Add a prompt into the onboarding process so that the entities that get created in HA are all named in sync and named in a manner that is best for the user's install.  This will help in locating device entities in the search and using them in other places.  Additionally, it would avoid having ambiguous entity IDs.

**Some possible considerations:**
- The user would be prompted to name the device that is being added to Home Assistant before the device is registered.  
- This device name would be used in all of the entities created by the `mobile_app` registration as a prefix.  
- This would apply to all entities created as a result of this registration including sensors, device_trackers, etc
- In the example below, it is `nms_iphone` to which a `_` is added before the entity name, rather than the current entity ID which do not have any association with the device and often conflict so they are suffixed by a number.

<img width="692" alt="Home Assistant 2019-11-26 11-55-16" src="https://user-images.githubusercontent.com/16869713/69668930-bc876880-1045-11ea-8605-5cef3892c409.png">

**Comment by hairychris** [comment]
As a temporary work around is there a quicker way than doing this than via the UI? For example could I edit device_registry or entity_registry in a text editor?
