### ISSUE TITLE
Cannot disable ”Firebase Cloud Messaging“ on iOS app 2.0

### ISSUE THREAD

**Issue by amamenu** [home-assistant/home-assistant-iOS#480]
I tried to disable "Firebase Cloud Messaging" and it didn't work.
When I closed it, I opened the app again, and it was still enabled.

**Comment by SeanPM5** [comment]
Appreciate the report, but this was opened few hours earlier here: https://github.com/home-assistant/home-assistant-iOS/issues/475 so I am closing this one as duplicate. 

You can add any additional observations to that issue and/or subscribe to it to follow the progress. Thanks.

**Comment by amamenu** [comment]
Could you fix this bug alone as soon as possible? Because this bug is directly related to privacy issues. If you wait to collect more bugs and then work on them together, it could be a long time. @SeanPM5

**Comment by SeanPM5** [comment]
Robbie is the sole developer of the iOS app, so it's entirely up to him on which bug fixes to prioritize and when to release an update. 

After he submits the update it also has to go through a review process at Apple before it gets released on the App Store. So I cannot give you a time frame except to say he's been made aware of the issue.

You can post any additional comments/concerns on the existing issue that I linked: #475
