### ISSUE TITLE
Unable to initialize ios app. Invalid client id or redirect url. 2019.1

### ISSUE THREAD

**Issue by limp2449** [home-assistant/home-assistant-iOS#487]
I just recently upgrade to 2019.1 I needed to reinitialize the app and keep getting stuck with the authentication step. It try to use the IOS website user/password prompt but I cannot see any input box to type my username and password.  I see an error message stating "Error: invalid client id or redirect uri" . The page say it is trying to give access to https://home-assistant.io/iOS which is not the correct uri for my setup. 
I expose my setup via duckdns and let'sencrypt. I have no problem loging in via any browser (including my phone).

**Comment by SeanPM5** [comment]
Check the instructions on the first part of [this page](https://companion.home-assistant.io/en/troubleshooting/errors#invalid-client-id-or-redirect-uri--or--os-error-while-looking-up-redirect_uri) and see if that helps at all.

**Comment by limp2449** [comment]
Thanks for the link to the post. Indeed, I get an error to curl using ipv6. I disabled IPV6 on the raspberry pi but am still experiencing the issue. Here are the information I observed in my logs...

2019-11-28 00:20:02 ERROR (MainThread) [homeassistant.core] Error doing job: SSL error in data received
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
2019-11-28 00:20:03 ERROR (MainThread) [homeassistant.components.auth.indieauth] OS error while looking up redirect_uri https://home-assistant.io/iOS: Address family not supported by protocol 

Any idea?

**Comment by SeanPM5** [comment]
Sorry I'm not too great with this stuff, @olbjan is the networking expert so maybe he can point you in the right direction.

But I think you're making some progress towards a fix at least. Might want to also [check this out too](https://companion.home-assistant.io/en/troubleshooting/setup#i-receive-an-ssl-error-andor-i-am-unable-to-connect-to-my-home-assistant-instance-when-away-from-home).

**Comment by olbjan** [comment]
You may need to update more of your Pi install. Your error now is that your python / raspbian install does not have an up-to-date list of trusted certificate authorities and thus fails the connection to home-assistant.io

It may be as simple as running an apt-get update && apt-get dist-upgrade but I can't say for certain what your setup looks like.

**Comment by limp2449** [comment]
I am still using a docker image that maybe out of date. Will try to update everything to the latest over the next few days. Thanks for the quick responses.

**Comment by TomBrien** [comment]
@limp2449 is this now resolved?

**Comment by TomBrien** [comment]
Closing this as stale. Hope you got everything sorted. Let us know if not
