### ISSUE TITLE
Node Red Notification API Error

### ISSUE THREAD

**Issue by artaxx81** [home-assistant/home-assistant-iOS#491]
Hi there,

the next problem with the iOS Companion App:

Since the v2 I am getting an API Error in Node RED wenn I want to send a push notification to the iPhone. My settings are:

![Unbenannt](https://user-images.githubusercontent.com/53049594/69801137-e15f1580-11d6-11ea-9a64-00575aefc516.JPG)

My HA version is: Home Assistant 0.102.2

Thank you!

Greets
Daniel

**Comment by TomBrien** [comment]
Looks like your service is wrong. New notify services start with `mobile_app`. Please check what service is listed in services in developer tools

**Comment by artaxx81** [comment]
THANK YOU :-)
