### ISSUE TITLE
Slovene translation

### ISSUE THREAD

**Issue by sirotkaslo** [home-assistant/home-assistant-iOS#492]
Hi,
please add Slovene translation. 
thank you!

**Comment by robbiet480** [comment]
`sl` has been added to Lokalise. Please sign up and select `sl` as a language you wish to translate for. If you have already signed up, let me know what your email is and I will add it for you.

Thanks for volunteering!

**Comment by sirotkaslo** [comment]
yeah, i've already signed up, my email is davor.baselj[at]gmail.com please add it for me. Thanks!

**Comment by robbiet480** [comment]
Done
