### ISSUE TITLE
Missing input validation in onboarding

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#493]
Users are reporting getting a http 404 error when manually entering their HA URL with a trailing /:

'https://myhome.duckdns.org/' -> http 404
'https://myhome.duckdns.org' -> Success!

The app should check for the trailing slash and remove it from the FQDN. At the same time both during onboarding and on manual entry in the connection settings (just to be safe both in internal and external url fields) the app should not accept manual entries of *.nabu.casa and prompt users to set up from inside their network if they want to use nabu casa.

**Comment by robbiet480** [comment]
The fix came from carefully reading this paragraph of the [appendingPathComponent](https://developer.apple.com/documentation/foundation/nsurl/1410614-appendingpathcomponent) docs:

> If the original URL does not end with a forward slash and pathComponent does not begin with a forward slash, a forward slash is inserted between the two parts of the returned URL, unless the original URL is the empty string.

Removing the first slash from `/auth/token` was the fix.
