### ISSUE TITLE
Can not setup connection "Object Mapper failed to serialize response"

### ISSUE THREAD

**Issue by CaCu15** [home-assistant/home-assistant-iOS#495]
First of all: Thank oyu for the great app, I'm using it since 2 years without any problems. 

But after the upgrade to 2019.1 I'm facing a problem: 

I've got a problem connecting to my home assistant instance from my iPad (running iPadOS 13.2.3).
The app runs fine on my iPhone 8, but the same configuration does not work on my iPad.
 
After I upgraded to HA Companion Version 2019.1 I can not connect to my HA instance any longer. When I enter the URl manually and click "connect" ("Verbinden") I end up with the error screen below. Saying : "Unkown error. Transaction could not be finished. Object Mapper failed to serialize response". Any idea's? 

![19-11-30 08-19-08 0303](https://user-images.githubusercontent.com/34535696/69897359-4fc4e480-134b-11ea-961e-4efdb663ec9b.png)

**Comment by TomBrien** [comment]
What version of Home Assistant are you running please.

**Comment by CaCu15** [comment]
I just updated to Home Assistant 0.102.2 in a Docker container (not HASSIO!) behind a Traefik reverse proxy (running as Docker container as well).  Traefik is terminating the SSL connection and communicates with HA via http (not https!).

**Comment by TomBrien** [comment]
Ok well if it’s working on another device set up in exactly the same way it seems unlikely that it’s a HA-side issue. `Object Mapper` in the past has been due to outdated HA (not true here) or invalid JSON being sent. Do you get as far as the log in page?

**Comment by CaCu15** [comment]
No, the error page pops up right after clicking the connect button

**Comment by CaCu15** [comment]
OK, now I feel bad. Somehow the IP of my iPad was listed in the ip_bans.yml of HA, thus the requests have been rejected by HA. After removing the IP from ip_bans.yml everything works fine. Sorry & thanks for the support!

**Comment by TomBrien** [comment]
No worries. Thanks for posting the cause. We should try and make that error more descriptive.

**Comment by ghazlewood** [comment]
I also had this problem, thanks for the write up! My phone's local IP address had been added to the ip_bans.yml file months ago and was preventing the iOS client from connecting...

**Comment by 230delphi** [comment]
you'll also get this error if you have any content after in your remote_url configuration!
https://.....ui.nabu.casa/

**Comment by rasgeek** [comment]
> you'll also get this error if you have any content after in your remote_url configuration!
> https://.....ui.nabu.casa/

Thanks this solved an issue i was having for months now after enabling duck DNS and SSL
