### ISSUE TITLE
No feedback for Entity Button presses

### ISSUE THREAD

**Issue by mback2k** [home-assistant/home-assistant-iOS#500]
Hello everyone,

I would like to request changes to the way the Entity Button (and maybe other "stateless" buttons) currently work from a UI perspective. At the moment there is no feedback on the Entity Button being pressed, because on mobile there is no mouse down/press and up/release. Instead there is only a single event for the button being touched and that does not make it react in any optical way.

I think it would be a great UI improvement if there was some animation happening on successful button interactions on mobile. But may this is something to be handled in https://github.com/home-assistant/home-assistant-polymer, I don't know.

Best regards,
Marc

**Comment by TomBrien** [comment]
Hi @mback2k this is predominately a UI issue so I'm going to throw it over to the polymer repo. The app support haptics. Make sure these are enabled although the support for haptics in the UI is still being rolled out.
