### ISSUE TITLE
kCL error when pulling to refresh if location is disabled

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/home-assistant-iOS#509]
When users have location permissions blocked, if the pull down to refresh they receive a kCL Error banner.

**Comment by y0ast** [comment]
https://github.com/home-assistant/home-assistant-iOS/issues/474

duplicate?

**Comment by TomBrien** [comment]
Correct. I’m just leaving this until I can get to a desktop to switch the issue in the project
