### ISSUE TITLE
Feature request: Update on power state

### ISSUE THREAD

**Issue by riemers** [home-assistant/home-assistant-iOS#51]
I want to know when i go to bed, or when i wake up. But the same goes for the wife. I tried lots of things and then something simple hit me.

If ater XX:XX hours and XX is home and phone is Plugged in to power, assume person is going to sleep. Same applies for waking up, if after say 06:00 and unplugged, assume woken up.

Sadly the app doesn't trigger instantly on power change. It would be great if the unplugged/plugged in would update instantly on those types of actions. That way one could make use of it in automation!

**Comment by mnoorenberghe** [comment]
This should be possible with [UIDeviceBatteryStateDidChange](https://developer.apple.com/documentation/foundation/nsnotification.name/1620052-uidevicebatterystatedidchange).

**Comment by riemers** [comment]
That would be a really cool feature if it will do that in the app!

**Comment by robbiet480** [comment]
Sadly we don't get these notifications while in the background, so theres no way to implement the request at this time :(

**Comment by riemers** [comment]
https://developer.apple.com/documentation/uikit/uidevice/1620051-batterystate is a new variant i read on the internets. Presume also not background. Beacons can be used to trigger stuff maybe? Would think we can use 'something' to make it happen.
