### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by fuzunspm** [home-assistant/home-assistant-iOS#511]
Hi,

Please add Turkish translation project so i can start on it.

English Name: Turkish
Native Name: Türkçe

**Comment by olbjan** [comment]
Hi, I have added the language to Lokalise and given you translator permission to it.

**Comment by fuzunspm** [comment]
Thank you but I can't see Turkish language in project page

**Comment by olbjan** [comment]
On lokalise you're added with your @me.com mail address - maybe that's it? I've send out an invite to your address on your github profile as well now.

**Comment by fuzunspm** [comment]
Now I got the access. Thanks!
