### ISSUE TITLE
[FR] notification action implementation

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/home-assistant-iOS#515]
Please implement notification actions.
I've implemented this with custom components currently (iirc it's called Actionable notifications)
In Android (and presumably IOS) you can receive notification with one or more actions included.
These actions would be just labeled URI's, which will trigger HA automations.
Example: heater is on and window is open. Keep heater on? Yes / no

I'm currently on mobile but can elaborate if needed!

**Comment by TomBrien** [comment]
We all ready have actionable notifications, please have a look at the documentation [here](https://companion.home-assistant.io/notifications/actionable). I’m going to close this but if I’ve misunderstood your request, please let me know.
