### ISSUE TITLE
hamburger(left) and ellipsis(right) overlap tab names

### ISSUE THREAD

**Issue by kmycek** [home-assistant/home-assistant-iOS#518]
This might only be affecting users like me that use the CCH add on - but the menu “hamburger” icon and the “configure UI” ellipsis icons are overlaid with the Lovelace tabs (see attached picture).

![526AF605-9883-401B-A8AF-5B337D0612C9](https://user-images.githubusercontent.com/5732030/70840760-cd6c0400-1dd1-11ea-977d-6cee1ccdf16c.png)

**Comment by TomBrien** [comment]
I believe when this was seen before it was due to an out of date version of CCH. Can you check you’re running the latest version of CCH

**Comment by kmycek** [comment]
Yes, that appears to have fixed it. Even though I was running CCH, it must have got corrupted, as I couldn’t even get into the settings. I reinstalled a newer version of CCH, and it works fine now.
