### ISSUE TITLE
Issue with Lovelace Dimmer 

### ISSUE THREAD

**Issue by Trefex** [home-assistant/home-assistant-iOS#523]
Hi,

When switching off a dimming light, there is a huge artefact appearing on the Lovelace interface on the iOS app, i guess it should not be this way?

![B9D0846D-B0FB-4BE8-8CE2-CE8EE50C8E00](https://user-images.githubusercontent.com/2877665/71488769-93afea00-2822-11ea-9568-39877640c0b8.png)

**Comment by TomBrien** [comment]
Can you please show a screenshot or video capture. Does this also occur in safari? It is most likely not related directly to the app

**Comment by Trefex** [comment]
@TomBrien I posted a screenshot in my original post.

I tried on Safari and it works great. (i will edit this comment to attach the screenshot)

**Comment by TomBrien** [comment]
Sorry yes I did see. GitHub app just showed an empty space. Ok it’s very strange that safari is different as the app is essential just showing a safari view there.

**Comment by Trefex** [comment]
That is strange. It is however still there even after upgrade to latest HA but it never shows in a browser. Is it WebKIT showing or really a safari window itself? It does look like the Lovelace css has some issue. 

The big dot is in fact the small dot of the slider that goes huge when it is at 0.

**Comment by TomBrien** [comment]
It is webkit but there should be no real difference as all iOS browsers are just webkit. I remember this was seen across iOS devices a while back and I thought was fixed. Certainly sounds like a CSS issue

**Comment by TomBrien** [comment]
See: home-assistant/home-assistant-polymer#4273

**Comment by Trefex** [comment]
That seems to be the issue. 

@TomBrien is there some cache of some sorts I should clear out? 

I’m not gonna completely wipe my HA install so the problem vanishes “magically” ?

**Comment by thomasloven** [comment]
There's a button at the bottom of the setting screen in the app to clear browser cache. Try that.

**Comment by TomBrien** [comment]
@Trefex did clearing the frontend cache fix the issue?

**Comment by Trefex** [comment]
@TomBrien just tried and indeed now it works as intended. 

Great software. Thanks for the support.
