### ISSUE TITLE
Documentation is confusing about firebase and does not explain consequences

### ISSUE THREAD

**Issue by gdt** [home-assistant/home-assistant-iOS#537]
The documentation at https://companion.home-assistant.io/ is confusing on several points.

One is that it seems to 99% be about the iOS app, and then talks about firebase.  This comes across as an editing error when cutting/pasting from the Android version.  I realize it's not, but the presence of firebase is so surprising that it deserves an explicit explanation that acknowledges the surprising nature of the situation.  I had the impression Apple had their own push service, which means an obvious question is why that isn't being used.

The documentation does not go on to explain the security consequences of firebase use.   There is a comment about notification content not being "stored" on "remote servers", but this is hard to understand precisely and unclear.

If you mean that there is a session key negotiated between the app and the HA instance, and that all notification content is encrypted, so that the firebase service and anything else sees only the fact that there was an encrypted notification, and the size, then it would be nice to say that.  If you mean something else, then I hope the above perhaps-clarification is helpful in phrasing it.

There is also the tracking concern of the device registering with firebase and/or apple push.  I am really unclear how this works, but it would be nice to explain what information is sent to firebase on registration.  I suspect that firebase can associate registrations from a device togther, getting a history of IP address use over time from a single phone, but that's it.   A link to any privacy policy that explains whether they promise not to disclose/use this information, or if they say they will fuse it with other information for ad tracking, would be nice to ad also.

**Comment by gdt** [comment]
Another question to answer is if firebase can tell that home assistant is in use, and whether firebase can associate the IP address of the HA instance with the IP address history of the phone.

**Comment by robbiet480** [comment]
We use Firebase because there's only so many hours in the day. We welcome anyone that is able to build and maintain a competing service that doesn't require using Firebase for push.

**Comment by gdt** [comment]
I didn't mean to say it was terrible that firebase was used.   Where I am coming from is that in theory Home Assistant is about hosting one's own automation data instead of disclosing one's information to some nebulous cloud.  Here, a push service operated by an advertising company is being used, and as a prospective user reading the available information about the app, I can't tell how bad the consequences are.
