### ISSUE TITLE
Android Fullscreen mode not wokring with phone with a screen "Notch"

### ISSUE THREAD

**Issue by Hellestyle** [home-assistant/home-assistant-iOS#538]
Hello there,

I am very pleased with the android companion app, one small little issue for the next release is to look at the fullscreen not showing correctly if you have a phone with a " Notch ". I have the Huawei Mate P20 Pro and some of the top page is going under the "Notch" as seen in the photo. The very top i just basicly clipped of and hidden behind the notch. 

Sorry for bad photo, taken with my laptop webcam right after i tried screenshoting the app with my phone! Doh! ( To clerify the notch isn't in the picture when taking a screenshot, ugh silly me)

Possible root for the issue is that i have custom header installed.
![WIN_20200129_15_18_21_Pro](https://user-images.githubusercontent.com/57177898/73364342-b498ae80-42aa-11ea-98cf-6fbb3df69c21.jpg)

**Comment by dshokouhi** [comment]
This should be filed in: https://github.com/home-assistant/home-assistant-android
