### ISSUE TITLE
mobile_app wrong battery_level icon battery-0

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant-iOS#543]
**Home Assistant release with the issue:**

102.2

**Last working Home Assistant release (if known):**
nut sure

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hassio Rpi4
**Integration:**

mobile app
**Description of problem:**

 all of a sudden I noticed several of my battery_level sensors of the mobile_app integration not having icon.
Checking the state I see they are supposed to set the icon to mdi:battery-0. which doesnt exist, it should probably be battery-outline?
![Schermafbeelding 2019-12-05 om 23 48 22](https://user-images.githubusercontent.com/33354141/70281247-db5ecb00-17ba-11ea-8347-4274fadbe563.jpg)
![Schermafbeelding 2019-12-05 om 23 50 51](https://user-images.githubusercontent.com/33354141/70281248-db5ecb00-17ba-11ea-9add-c30e9a947fa4.jpg)
![Schermafbeelding 2019-12-05 om 23 51 54](https://user-images.githubusercontent.com/33354141/70281249-db5ecb00-17ba-11ea-9770-3e08ec78b2aa.jpg)
![Schermafbeelding 2019-12-05 om 23 52 08](https://user-images.githubusercontent.com/33354141/70281251-db5ecb00-17ba-11ea-8f53-8cd7c44e1ac4.jpg)

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**
maybe related to https://github.com/home-assistant/home-assistant/issues/29460 ?

**Comment by robbiet480** [comment]
@Mariusthvdb Just let me know that you are still having this issue and i'll dig in this afternoon.

**Comment by Mariusthvdb** [comment]
cool, no battery just below ten at the moment, but I do see this odd behavior:
<img width="1220" alt="Schermafbeelding 2020-02-12 om 23 23 49" src="https://user-images.githubusercontent.com/33354141/74383081-d176cb00-4dee-11ea-9e17-df19ae3dd961.png">

note the top 2 are unplugged, but have a charging icon, and the third is on 76% and has icon 70, while the middle is on 71% and has icon 80...

will wait for my current battery to drop down to below 10% and report further. whatever the case, battery-0 doesn't exist.

and isn't that what happens when dropping below 11?

<img width="735" alt="Schermafbeelding 2020-02-12 om 23 31 54" src="https://user-images.githubusercontent.com/33354141/74383708-06cfe880-4df0-11ea-8f50-4158d1569f7b.png">

**Comment by Mariusthvdb** [comment]
> is this still an issue in 0.105? I believe the icon was updated in the latest MDI icons update.
> 
> edit: or is it that aliases for icon names don't work? I see it was changed to `battery-outline` but the alias for `battery-0` is still there

yeah the alias has been there before but that works in the search bar at mdi, not when using that in the HA icon field.

for reference here:

<img width="359" alt="Schermafbeelding 2020-02-12 om 23 50 52" src="https://user-images.githubusercontent.com/33354141/74384958-b7d78280-4df2-11ea-8473-d9b1850e053c.png">
as per feb 12 2020

**Comment by Krocko** [comment]
@robbiet480 i am still having this problem too.

**Comment by Mariusthvdb** [comment]
commented on the commit, while should have done here, sorry:

thanks for picking this up!
Wouldn't it be possible to keep the mdi:battery-alert for level <= 5 and from >5 do as you changed now? That way we do get to see the alert icon as a final warning after battery-outline. Maybe even better would be battery-alert-variant-outline, since that is an outline icon too, and fits better to the battery-outline used when <10

**Comment by Krocko** [comment]
@robbiet480 i think it is the same for the charging icon.

**Comment by Mariusthvdb** [comment]
not really sure if this was supposed to be fixed yet but I still see this in Ha 106.6 with the latest iOS app:

<img width="426" alt="Schermafbeelding 2020-03-20 om 17 20 06" src="https://user-images.githubusercontent.com/33354141/77186401-1d461f80-6ad3-11ea-9e40-6bb86e4dc8c0.png">

<img width="404" alt="Schermafbeelding 2020-03-20 om 17 20 29" src="https://user-images.githubusercontent.com/33354141/77186405-1fa87980-6ad3-11ea-92dc-3e3b43e7de3a.png">

hope this helps
