### ISSUE TITLE
Option to clear delivered notification

### ISSUE THREAD

**Issue by parrel** [home-assistant/home-assistant-iOS#544]
Wouldn't it be nice to have an option to clear a delivered notification that uses the same `apns-collapse-id`? I was reading the [documentation ](https://companion.home-assistant.io/docs/notifications/notifications-basic#replacing-notifications) today and saw that the Android app already has the option to send `clear_notification`.

This can be useful if you send an actionable notification to multiple people, but want to prevent to have the action execute multiple times. 

Would this be possible to implement? It looks like the UserNotifications class has [a method](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649500-removedeliverednotifications) for it. 

Thank you for the amazing app!

**Comment by TomBrien** [comment]
This sounds similar to #258 to me. Does that sound right?

**Comment by parrel** [comment]
Yes, sorry for the duplicate.
