### ISSUE TITLE
Request: Use consistent user agent for all requests

### ISSUE THREAD

**Issue by efirestone** [home-assistant/home-assistant-iOS#554]
I'd like to reverse proxy HA requests, but this is harder than it should be as there is no support for paths (subfolders) in the `base_url`, and apparently [never will be](https://github.com/home-assistant/architecture/issues/156#issuecomment-478183627).

For me, supporting proxying for just the iOS app would be sufficient, and I believe that can be achieved by proxying based on the user agent of the request. The issue right now is that many requests come through with a custom agent from the app, like so:

```
Home%20Assistant/69 CFNetwork/1121.2.2 Darwin/19.3.0
```

But many others come through with a more generic one:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
```

Presumably the latter is coming from requests that are initiated by a WKWebView instance directly (and the types of requests, like images and other resources) would support this.

It looks like we can use the custom user agent for these requests as well by setting it via [`WKWebView.customUserAgent`](https://developer.apple.com/documentation/webkit/wkwebview/1414950-customuseragent).

Thanks for your consideration!

**Comment by efirestone** [comment]
I can't seem to get the dev app to launch in the sim for some reason, but I believe this might be the entire change:
```
 import UIKit
+import Alamofire
 import WebKit
 import KeychainAccess
 import PromiseKit
@@ -117,6 +118,7 @@ class WebViewController: UIViewController, WKNavigationDelegate, WKUIDelegate {
         config.userContentController = userContentController
 
         self.webView = WKWebView(frame: self.view!.frame, configuration: config)
+        self.webView.customUserAgent = SessionManager.defaultHTTPHeaders["User-Agent"]
         self.webView.isOpaque = false
         self.view!.addSubview(webView)
```

**Comment by robbiet480** [comment]
I guess i'm not opposed. It's not like the built in browser ever sees much more than Home Assistant UI and afaik we don't do any UA detection there. Mind submitting a PR for this so you get the credit? I'll test it locally first.

**Comment by efirestone** [comment]
PR's open. Thanks!

**Comment by BigCabbage** [comment]
@efirestone , can you share how you configured how you used the distinct user agent to reverse proxy HA? There are many, many users who are looking for a way to do this without using a subdomain.

If you can share an example, you or I might be able to contribute to the page which currently described how to reverse proxy using a subdomain so it will be available for everyone...

**Comment by efirestone** [comment]
Happy to share. Here's my *desired* Nginx config:

```
      location / {
         if ($http_user_agent ~ "^Home(?:%20| )Assistant/") {
            proxy_pass https://homeassistant.my.internal.domain:8123;
         }
         
         proxy_set_header Host $host;

         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
      }
```

Currently I have this working "well enough" by also handling a bunch of edge cases, like redirecting certain folder names to HA, but it's tricky, less secure, and not everything works. Having the above work would be great.

**Comment by BigCabbage** [comment]
Thanks, 

I'll test it the moment the above PR has made it into the next release and report back my findings. Hopefully this will allow everyone to integrate HA into a sub-page of their site, instead of using sub-domains.

**Comment by efirestone** [comment]
Appreciate the testing help! To be clear, this doesn't technically get HA working behind its own subdomain, but it lets you use a single domain for all services as long as the other services are behind their own subdomains. HA still sits at the root of the domain, but the user agent lets the reverse proxy route things appropriately. Anything with the HA mobile user agent routes to the HA machine/service/port, and anything else passes through to the normal nginx routing.
