### ISSUE TITLE
Battery level not updating on iPhone XS

### ISSUE THREAD

**Issue by artkrz** [home-assistant/home-assistant-iOS#556]
Hi,

I'm running latest app on iPhone XS (13.4 latest public beta) and the battery level sensor isn't updating. It did initially when I installed the app but it never updated after that. The error I'm seeing in the logs is:

`Received invalid webhook payload: required key not provided @ data[11][‘state’]`

Location updates work fine though.

**Comment by Krocko** [comment]
Please see #547

**Comment by TomBrien** [comment]
Closing as duplicate of #547
