### ISSUE TITLE
Sensor "timestamp" badly parsed

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/home-assistant-iOS#566]
Hi, I have a sensor of type timestamp that works fine on PC broser but not on the iOS mobile app.
Here the situation:

PC browser:

![image](https://user-images.githubusercontent.com/57354320/76655470-a5757380-656d-11ea-9f5b-dac2d9f64fde.png)

iOS app:

![image](https://user-images.githubusercontent.com/57354320/76655547-d5247b80-656d-11ea-8c87-f94f82e84f08.png)

Simone

**Comment by TomBrien** [comment]
Do you see the same behaviour in Safari on iOS?

**Comment by chemelli74** [comment]
> Do you see the same behaviour in Safari on iOS?

Yes, same in Safari for iOS

Simone

**Comment by chemelli74** [comment]
> > Do you see the same behaviour in Safari on iOS?
> 
> Yes, same in Safari for iOS
> 
> Simone

And same issue on Safari for MacOs as well.

Simone

**Comment by TomBrien** [comment]
In that case this is a general home assistant issue so I’ll forward it over to the appropriate repo
