### ISSUE TITLE
Switches missing "handles"

### ISSUE THREAD

**Issue by wixoff** [home-assistant/home-assistant-iOS#62]
A number of switches in the UI are sometimes missing their "handles" and it has been like this for the last couple of HASS releases.  I'm currently using iOS app 1.04, HASS 0.55.2, and iOS 11.1 public beta 4 on an iPhone 7+ (HASS runs in Docker, accessed from the outside world via NGINX reverse proxy and Let's Encrypt in a separate container).  Please see the attached screenshot.  This occurred in the non-beta iOS 11 release as well.

I wish I could be more precise, but a number of releases ago I never saw the problem, but that would have also been under iOS 10.x.

![img_5633](https://user-images.githubusercontent.com/945097/32012656-9904faac-b986-11e7-97bb-2ef8f4986928.PNG)

**Comment by arsaboo** [comment]
I have started seeing those too. It only happens to switches/input_boolean in the `off` position.

**Comment by lindsaymarkward** [comment]
I have seen this a lot, but intermittently.
Also, Robbie asked me to post: 
I just updated an icon for a view that doesn't show on iOS but does on Chrome. It's the brand new `door` icon:
```
Rooms:
  view: yes
  icon: mdi:door
```
![img_8170f4d75b78-1](https://user-images.githubusercontent.com/7665042/32473281-884abbd0-c3b2-11e7-967b-6abc4eb74b63.jpeg)
See the gap between HOME and the camera icon?

**Comment by mnoorenberghe** [comment]
If you hit the refresh button at the bottom of the webview does it change anything?

**Comment by lindsaymarkward** [comment]
Refreshing does not make the missing icon appear (neither does closing and restarting).

**Comment by wixoff** [comment]
I'm not seeing the "missing handles" problem any more in 1.1.1 (or for that matter 1.1.0 I think).

**Comment by lindsaymarkward** [comment]
I now see the `mdi:door` icon in my HA UI on my phone app @robbiet480  
I have not seen any missing handles for some time now.
Thanks.

**Comment by robbiet480** [comment]
I haven't changed anything! So yay! I'm still pretty sure it is/was a frontend issue, especially with the recent Polymer 2 upgrade and all kinds of work going on over there.

**Comment by mnoorenberghe** [comment]
I haven't seen complaints of this recently so I'm closing it. Comment if it's still happening.
