### ISSUE TITLE
Use different 'category' key for actionable notifications and dynamic content?

### ISSUE THREAD

**Issue by jamieshaw** [home-assistant/home-assistant-iOS#64]
In my setup I have a camera by the front door for monitoring people coming and going; which is also triggered by a magnetic sensor that monitors it's physical state.  Door opens, send notification with camera state — simple.

However, when the home is vacant, this magnetic switch is also used to trigger the security alarm for the house, with a different messaging and a different `category` that gives the option to silence or stop the alarm.

It would be nice if I could use my custom category for the security alarm controls _and_ the ability to monitor the camera.  I understand this can be done by setting up notification actions for the `camera` category, but I'd rather not have the security notifications fire just when the front door is opened.

Is it possible to split custom categories and dynamic categories? Or is this more engrained into the iOS notification API?

**Comment by TheCellMC** [comment]
+1 for this

**Comment by robbiet480** [comment]
This will be in 2.0!
