### ISSUE TITLE
Support iPhone X screen size

### ISSUE THREAD

**Issue by chriskacerguis** [home-assistant/home-assistant-iOS#65]
It would be nice to get the current app supporting the new resolution of the iPhone X

**Comment by mnoorenberghe** [comment]
The status bar issue was fixed in #54 so landscape should be fine with the master branch. Landscape isn't ideal but it's not clear what the ideal solution is… it seems like ideally we'd need to adjust the contents of the web view.

**Comment by chriskacerguis** [comment]
Cools.  Thanks for the follow up :)

Any idea when an update will be released to the App Store, or could I get added to Test Flight?

**Comment by robbiet480** [comment]
Appears working for me now on my iPhone X and in Simulator. Update with this should be out in the next few days.

**Comment by chriskacerguis** [comment]
Thanks @robbiet480 !!

I really appreciate you working on this project.  Would it be possible to be added to the Test Flight group?

**Comment by robbiet480** [comment]
@chriskacerguis new version out now!

I don't currently have a Testflight beta group but maybe i'll get one going soon since development is ramping up again. Will make sure to add you if I do.

**Comment by chriskacerguis** [comment]
@robbiet480 thanks.  Got the new version.  It's GREAT.

**Comment by chriskacerguis** [comment]
thanks again for all your hard work.
