### ISSUE TITLE
Bottom toolbar missing icons

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/home-assistant-iOS#69]
https://community.home-assistant.io/t/bottom-menu-with-settings-gear-is-missing/32028

**Comment by robbiet480** [comment]
@mnoorenberghe Any ideas?

**Comment by robbiet480** [comment]
User is no longer experiencing this after uninstalling, rebooting and reinstalling. No other reports since/ever.

**Comment by travislreno** [comment]
I have this issue too.
