### ISSUE TITLE
Can't come back from settings screen

### ISSUE THREAD

**Issue by hahmann** [home-assistant/home-assistant-iOS#7]
iPhone 7 10.2
Hass 0.37.0
App Build 50

When I click on the settings button, all icons at the bottom will disappear, so there is no way to come back or choose other icons, I have to kill the app and open it again to be able to do anything else than settings.

**Comment by hahmann** [comment]
Don't know if it has any relevance but is is an iPhone 7 Plus.

**Comment by viruzofficial** [comment]
Can confirm this behaviour on an iPhone 7 Plus.
@robbiet480 you have to fix that before contributing to Apple Store.

**Comment by hahmann** [comment]
Ok, done some additional tests today. If you have just a few items you wont need to organize your screen and the last icon will be Settings and the issue will happen. If you have more than 4 items, you last icon will be ... (More), you can select it, select settings and there will be a back arrow so you wont see the issue.

Probably most of the people wont see the issue as they have dozens of items, switchs, etc.
