### ISSUE TITLE
Missing Bottom Icons

### ISSUE THREAD

**Issue by travislreno** [home-assistant/home-assistant-iOS#75]
Issue 69 previously closed as not reproducible.  
https://github.com/home-assistant/home-assistant-iOS/issues/69

This issue still exists in version 1.1.1
![img_3124](https://user-images.githubusercontent.com/24857691/33000062-60da5afc-cd6b-11e7-8b25-b81683741648.jpg)

**Comment by robbiet480** [comment]
@travislreno Thanks for the report. I just started getting error logs of this problem this morning and updated the thread linked in the initial issue but forgot to re-open the issue. I've added some safety checks and logging which should either fix or help track down the problem). Hope to have this fixed before Thanksgiving.

**Comment by bhaap** [comment]
Im still getting this issue with newest IOS on a Iphone 7 Plus.
![img_4513](https://user-images.githubusercontent.com/2168003/36928605-89a3a426-1e87-11e8-96b9-b2489019d4cd.PNG)

**Comment by andrewjfreyer** [comment]
I have also had this issue for a long while. iPhone X.

**Comment by bhaap** [comment]
After My latest reboot i got it to work again.

**Comment by andrewjfreyer** [comment]
@bhaap a restart of the phone, app, or HA? The buttons appear briefly if I reinstall the App, but no restarting/relaunching combination works to show the buttons for me.

**Comment by Banditen01** [comment]
Same problem for me on HA for iOS 1.5.0 and Hassbian 0.87.1 and iOS 12.1.4

https://1drv.ms/u/s!Avcxv0ohVeYLiiey_m6tk8hoe_sP

https://1drv.ms/u/s!Avcxv0ohVeYLiijXIhvyn_XwxI5h

**Comment by robbiet480** [comment]
This will hopefully be fixed in 2.0 as we have moved to a new system for generating these icons

**Comment by robbiet480** [comment]
Closing this as 2.0 removed the toolbar entirely.
