### ISSUE TITLE
thermostats operation mode "cut off"on iPhone

### ISSUE THREAD

**Issue by reimerm** [home-assistant/home-assistant-iOS#79]
It looks like on iOS at least on an iPhone the thermostats opertation modes are not fully selectable. First screenshot is taken on iOS 11.2 - iPhone 6S, 2nd one on Chrome - HA version is running on 0.59.1

![img_2196](https://user-images.githubusercontent.com/8930202/33796243-ebd4dad0-dcf0-11e7-8159-cb9fc4b15cb7.PNG)
![chrome_2017-12-09_14-50-10](https://user-images.githubusercontent.com/8930202/33796254-fe15b8ae-dcf0-11e7-9d72-29231d30a6aa.png)

**Comment by boojew** [comment]
This issue seems to affect all dropdowns. Affects my fans as well :(

**Comment by reimerm** [comment]
The Z-Wave Options section almost works fine so I think it also has something to do with the Graph being displayed - does the fan also display some kinde of state history?

**Comment by boojew** [comment]
No, it shows the normal bar chart for on/off and then a dropdown for off/low/med/high

**Comment by sea3pea0** [comment]
I am seeing this same problem on both the iPad and iPhone screens. This problem didn't occur until I added group views (tabs). I'm seeing this on ios 9.3.5 also.

**Comment by talondnb** [comment]
Pretty sure this issue was resolved in a newer HA release as I no longer see the issue.

Has development stopped/slowed big time on this app now?

**Comment by cmsimike** [comment]
@talondnb I think the issue was with home assistant front end, not the app? I feel like I was seeing similar on my iphone using the browser directly, so had nothing to do with the ios app?

**Comment by mnoorenberghe** [comment]
> Has development stopped/slowed big time on this app now?

I occasionally make some fixes but have been busy the last few months and get demotivated when the fixes I do make don't get released.
