### ISSUE TITLE
Not able to save a new password

### ISSUE THREAD

**Issue by hahmann** [home-assistant/home-assistant-iOS#8]
iPhone 7 Plus 10.2
Hass 0.37.0
App Build 50

I've been using the app inside my network only, doing some tests and was not using an API password.
I tried to enable it now, when I oppened the app it will give a 401 error, that fine but I'm not able to save a password.

I add my newly created password, which works on a browser as expected, but if I add it to the settings screen there is no way to save it, no save button and nothing that I do will make the app try to connect.

If I close the app and open it again, the password field will be blank, which means it is not saving it.

Tried to look at Settings App -> Home Assistant but there is no configuration there as well.

**Comment by pascalmattes** [comment]
Can confirm this behaviour also when changing the password. Then you have to install the app again.
Also for changing the adress.

**Comment by LaStrada** [comment]
I have the same problem. I tried to reinstall the app, but the app remembers the IP-address and password! I tried to remove the app, reboot and then install it again, but it did not help.

What about implementing this?
http://stackoverflow.com/questions/4747404/delete-keychain-items-when-an-app-is-uninstalled

**Comment by OnFreund** [comment]
This problem still persists with the latest version on the app store. Tried re-installing, changing the URL to a different one. Neither worked.
