### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant-iOS#83]
Please add Slovak language (sk_SK) for iOS app to lokalise.

**Comment by mnoorenberghe** [comment]
@robbiet480 Was this addressed yet? I don't have an account on Lokalise to check.

https://lokalise.co/signup/834452985a05254348aee2.46389241/all/

**Comment by robbiet480** [comment]
@mnoorenberghe just added Slovak but seems the user who requested this has deleted their GitHub account so I don't expect anyone to add it anytime soon :(

**Comment by robbiet480** [comment]
Changed my mind on this one. Since there's no one around to translate it (because the reporting user deleted their GitHub) I'm removing the translation from Lokalise. If you wish to translate into Slovak in the future please re-open this issue.

Thanks!
