### ISSUE TITLE
Clicking on Settings/URL field will erase the whole URL and take it back to standard https://

### ISSUE THREAD

**Issue by hahmann** [home-assistant/home-assistant-iOS#9]
iPhone 7 Plus 10.2
Hass 0.37.0
App Build 50

Maybe that's an expected behavior but I'd suggest that when the user clicks on URL field to be able to change it and not erase the whole URL so the user has to add it again. Sometimes we just need to change the end portion of the IP or the initial hostname from a DynDNS service or even the port so this makes the process a little bit annoying.

**Comment by LaStrada** [comment]
I agree. What about implementing a clear button?
https://developer.apple.com/reference/uikit/uitextfield/1619622-clearbuttonmode
