### ISSUE TITLE
Allow updating of notification badges only

### ISSUE THREAD

**Issue by jamieshaw** [home-assistant/home-assistant-iOS#92]
This is more an issue with Home Assistant at large, but it would be nice if the ability to push a blank message to iOS to silently update the badge of the icon in the background.

An instance of this would be to set an automation to monitor states of `persistent_notification` components; and have the count of them dynamically pushed to iOS as they are created and dismissed.

The issue is that blank messages cannot be pushed from Home Assistant. Perhaps allow special circumstances for `notify.ios`?

**Comment by robbiet480** [comment]
You can now send a push with `message` set to `delete_alert` to not show a message.

**Comment by jamieshaw** [comment]
Apologies for the silence on this; just got around to setting this up and can confirm it works. Thanks!

It has flagged another point; which I'll create a separate issue for – it doesn't seem possible to send notifications without sound? Just so the badge updates silently, without vibration, in the background.

**Comment by jamieshaw** [comment]
Finally getting around to testing the new `mobile_app` notification system and noticed this is broken – is there a new key for similar functionality; or are features still being ported to the new system?

**Comment by robbiet480** [comment]
This has been re-implemented for 2.0 as noted in #463.
