### ISSUE TITLE
Cannot reset App (and remove stored data)

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/home-assistant-iOS#95]
I was using the app and I cancelled instead of entering a username and password when trying to access the Configurator.

Now I ALWAYS get the error no auth header received when trying to access this. (Hassio)

I tried deleting the App but there seems to be NOTHING I can do to get a prompt to enter user/pass again.

I posted about this a few times on the Forum in the iOS section but zero responses. Note: Using Chrome I can get in no issue. Just the app not working

**Comment by robbiet480** [comment]
Fixed via 14d64f3f5f4399cec0cec70ec6c5b931b3e01273
