### ISSUE TITLE
Feature Request: Disable device location tracker

### ISSUE THREAD

**Issue by janvanhelvoort** [home-assistant/home-assistant-iOS#98]
Hello,

I use an other device tracker platform, but i like the notifications from the app.
Is there an option to disable location tracking from / with the ios app?

When you disable the location tracker, `Device Tracker Component Loaded` = false in the setting section. 

Thank you.

**Comment by cmsimike** [comment]
Is there a reason why the location tracking of the app can't just be ignored?

**Comment by janvanhelvoort** [comment]
The card of the entity, will always show the data like battery level and state and things like GPS, but they are not up-to-date or accurate.

**Comment by robbiet480** [comment]
@janvanhelvoort I think this should be possible already by removing the `.ios.conf` file, disabling location on your device, and then reconnecting to your HA.

**Comment by janvanhelvoort** [comment]
Hello Robbie,

Yes, it works. Thank you!

Only, the battery state / value are displayed, but never updated any more. How can I remove / disable this entities as they are not anymore accurate.
